import os

DAGSTER_S3_BUCKET: str = os.getenv("DAGSTER_S3_BUCKET", "insights-dags")
DAGSTER_DEFAULT_SLACK_ALERTS_CHANNEL: str = os.getenv("DAGSTER_DEFAULT_SLACK_ALERTS_CHANNEL", "#alerts-datastore")
DAGSTER_DATA_EXPORT_S3_BUCKET: str = os.getenv("DAGSTER_DATA_EXPORT_S3_BUCKET", "dagster-data-export")
DATASTORE_BACKUPS_BUCKET: str | None = os.getenv("DATASTORE_BACKUPS_BUCKET")

DATASTORE_FULL_BACKUP_SCHEDULE: str = os.getenv("DATASTORE_FULL_BACKUP_SCHEDULE", "0 22 * * 5")
DATASTORE_INCREMENTAL_BACKUP_SCHEDULE: str = os.getenv("DATASTORE_INCREMENTAL_BACKUP_SCHEDULE", "0 22 * * 0-4,6")
SQUASH_PERSON_OVERRIDES_SCHEDULE: str = os.getenv(
    "SQUASH_PERSON_OVERRIDES_SCHEDULE", "0 22 * * 6"
)  # At 22:00 (10 PM) on Saturday
DAGSTER_DOMAIN: str | None = os.getenv("DAGSTER_DOMAIN")

DAGSTER_UI_HOST: str = os.getenv("DAGSTER_UI_HOST", "localhost")
DAGSTER_UI_PORT: int = int(os.getenv("DAGSTER_UI_PORT", 3030))

DAGSTER_AI_EVALS_S3_BUCKET: str = os.getenv("DAGSTER_AI_EVALS_S3_BUCKET", "ai-evals")

DAGSTER_FAVICONS_S3_BUCKET: str = os.getenv("DAGSTER_FAVICONS_S3_BUCKET", "insights")
