// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:35 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ExportedData } from './types'
import type { CommonFilters, HeatmapFilters, HeatmapFixedPositionMode } from '../lib/components/heatmaps/types'
import type { HrefMatchType } from '../lib/components/heatmaps/heatmapDataLogic'

export interface exporterViewLogicType extends Logic {
    actionCreators: {
        setCommonFilters: (filters: CommonFilters) => {
            type: 'set common filters (exporter.exporterViewLogic)'
            payload: {
                filters: CommonFilters
            }
        }
        setHeatmapFilters: (filters: HeatmapFilters) => {
            type: 'set heatmap filters (exporter.exporterViewLogic)'
            payload: {
                filters: HeatmapFilters
            }
        }
        setHeatmapFixedPositionMode: (mode: HeatmapFixedPositionMode) => {
            type: 'set heatmap fixed position mode (exporter.exporterViewLogic)'
            payload: {
                mode: HeatmapFixedPositionMode
            }
        }
        setHeatmapColorPalette: (palette: string | null) => {
            type: 'set heatmap color palette (exporter.exporterViewLogic)'
            payload: {
                palette: string | null
            }
        }
        setHref: (href: string) => {
            type: 'set href (exporter.exporterViewLogic)'
            payload: {
                href: string
            }
        }
        setHrefMatchType: (matchType: HrefMatchType) => {
            type: 'set href match type (exporter.exporterViewLogic)'
            payload: {
                matchType: HrefMatchType
            }
        }
        setIsLoading: (isLoading: boolean) => {
            type: 'set is loading (exporter.exporterViewLogic)'
            payload: {
                isLoading: boolean
            }
        }
        setScreenshotUrl: (screenshotUrl: string) => {
            type: 'set screenshot url (exporter.exporterViewLogic)'
            payload: {
                screenshotUrl: string
            }
        }
        fetchScreenshotUrl: () => {
            type: 'fetch screenshot url (exporter.exporterViewLogic)'
            payload: {
                value: true
            }
        }
    }
    actionKeys: {
        'set common filters (exporter.exporterViewLogic)': 'setCommonFilters'
        'set heatmap filters (exporter.exporterViewLogic)': 'setHeatmapFilters'
        'set heatmap fixed position mode (exporter.exporterViewLogic)': 'setHeatmapFixedPositionMode'
        'set heatmap color palette (exporter.exporterViewLogic)': 'setHeatmapColorPalette'
        'set href (exporter.exporterViewLogic)': 'setHref'
        'set href match type (exporter.exporterViewLogic)': 'setHrefMatchType'
        'set is loading (exporter.exporterViewLogic)': 'setIsLoading'
        'set screenshot url (exporter.exporterViewLogic)': 'setScreenshotUrl'
        'fetch screenshot url (exporter.exporterViewLogic)': 'fetchScreenshotUrl'
    }
    actionTypes: {
        setCommonFilters: 'set common filters (exporter.exporterViewLogic)'
        setHeatmapFilters: 'set heatmap filters (exporter.exporterViewLogic)'
        setHeatmapFixedPositionMode: 'set heatmap fixed position mode (exporter.exporterViewLogic)'
        setHeatmapColorPalette: 'set heatmap color palette (exporter.exporterViewLogic)'
        setHref: 'set href (exporter.exporterViewLogic)'
        setHrefMatchType: 'set href match type (exporter.exporterViewLogic)'
        setIsLoading: 'set is loading (exporter.exporterViewLogic)'
        setScreenshotUrl: 'set screenshot url (exporter.exporterViewLogic)'
        fetchScreenshotUrl: 'fetch screenshot url (exporter.exporterViewLogic)'
    }
    actions: {
        setCommonFilters: (filters: CommonFilters) => void
        setHeatmapFilters: (filters: HeatmapFilters) => void
        setHeatmapFixedPositionMode: (mode: HeatmapFixedPositionMode) => void
        setHeatmapColorPalette: (palette: string | null) => void
        setHref: (href: string) => void
        setHrefMatchType: (matchType: HrefMatchType) => void
        setIsLoading: (isLoading: boolean) => void
        setScreenshotUrl: (screenshotUrl: string) => void
        fetchScreenshotUrl: () => void
    }
    asyncActions: {
        setCommonFilters: (filters: CommonFilters) => Promise<any>
        setHeatmapFilters: (filters: HeatmapFilters) => Promise<any>
        setHeatmapFixedPositionMode: (mode: HeatmapFixedPositionMode) => Promise<any>
        setHeatmapColorPalette: (palette: string | null) => Promise<any>
        setHref: (href: string) => Promise<any>
        setHrefMatchType: (matchType: HrefMatchType) => Promise<any>
        setIsLoading: (isLoading: boolean) => Promise<any>
        setScreenshotUrl: (screenshotUrl: string) => Promise<any>
        fetchScreenshotUrl: () => Promise<any>
    }
    defaults: {
        isLoading: boolean
        screenshotUrl: string | null
    }
    events: {}
    key: undefined
    listeners: {
        fetchScreenshotUrl: ((
            action: {
                type: 'fetch screenshot url (exporter.exporterViewLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['exporter', 'exporterViewLogic']
    pathString: 'exporter.exporterViewLogic'
    props: ExportedData
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        isLoading: boolean
        screenshotUrl: string | null
    }
    reducers: {
        isLoading: (state: boolean, action: any, fullState: any) => boolean
        screenshotUrl: (state: string | null, action: any, fullState: any) => string | null
    }
    selector: (state: any) => {
        isLoading: boolean
        screenshotUrl: string | null
    }
    selectors: {
        isLoading: (state: any, props?: any) => boolean
        screenshotUrl: (state: any, props?: any) => string | null
        exportedData: (state: any, props?: any) => ExportedData
    }
    sharedListeners: {}
    values: {
        isLoading: boolean
        screenshotUrl: string | null
        exportedData: ExportedData
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        exportedData: (arg: ExportedData) => ExportedData
    }
}
