// Generated by kea-typegen on Sun, 02 Aug 2026 21:35:25 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ApprovalPolicy, AvailableFeature } from '../../types'

export interface approvalsGateLogicType extends Logic {
    actionCreators: {
        loadActivePolicies: () => {
            type: 'load active policies (lib.approvals.approvalsGateLogic)'
            payload: any
        }
        loadActivePoliciesSuccess: (
            activePolicies: ApprovalPolicy[],
            payload?: any
        ) => {
            type: 'load active policies success (lib.approvals.approvalsGateLogic)'
            payload: {
                activePolicies: ApprovalPolicy[]
                payload?: any
            }
        }
        loadActivePoliciesFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load active policies failure (lib.approvals.approvalsGateLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'load active policies (lib.approvals.approvalsGateLogic)': 'loadActivePolicies'
        'load active policies success (lib.approvals.approvalsGateLogic)': 'loadActivePoliciesSuccess'
        'load active policies failure (lib.approvals.approvalsGateLogic)': 'loadActivePoliciesFailure'
    }
    actionTypes: {
        loadActivePolicies: 'load active policies (lib.approvals.approvalsGateLogic)'
        loadActivePoliciesSuccess: 'load active policies success (lib.approvals.approvalsGateLogic)'
        loadActivePoliciesFailure: 'load active policies failure (lib.approvals.approvalsGateLogic)'
    }
    actions: {
        loadActivePolicies: () => void
        loadActivePoliciesSuccess: (activePolicies: ApprovalPolicy[], payload?: any) => void
        loadActivePoliciesFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadActivePolicies: () => Promise<any>
        loadActivePoliciesSuccess: (activePolicies: ApprovalPolicy[], payload?: any) => Promise<any>
        loadActivePoliciesFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        activePolicies: ApprovalPolicy[]
        activePoliciesLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['lib', 'approvals', 'approvalsGateLogic']
    pathString: 'lib.approvals.approvalsGateLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        activePolicies: ApprovalPolicy[]
        activePoliciesLoading: boolean
    }
    reducers: {
        activePolicies: (state: ApprovalPolicy[], action: any, fullState: any) => ApprovalPolicy[]
        activePoliciesLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        activePolicies: ApprovalPolicy[]
        activePoliciesLoading: boolean
    }
    selectors: {
        activePolicies: (state: any, props?: any) => ApprovalPolicy[]
        activePoliciesLoading: (state: any, props?: any) => boolean
        hasAvailableFeature: (
            state: any,
            props?: any
        ) => (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        isApprovalsFeatureEnabled: (state: any, props?: any) => boolean
        isApprovalRequired: (state: any, props?: any) => (actionKey: string) => boolean
    }
    sharedListeners: {}
    values: {
        activePolicies: ApprovalPolicy[]
        activePoliciesLoading: boolean
        hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        isApprovalsFeatureEnabled: boolean
        isApprovalRequired: (actionKey: string) => boolean
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        isApprovalsFeatureEnabled: (
            hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        ) => boolean
        isApprovalRequired: (
            isApprovalsFeatureEnabled: boolean,
            activePolicies: ApprovalPolicy[]
        ) => (actionKey: string) => boolean
    }
}
