// Generated by kea-typegen on Sun, 02 Aug 2026 21:38:42 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic, BreakPointFunction } from 'kea'

import type { FeatureFlagsSet } from '../../lib/logic/featureFlagLogic'
import type { Variable } from '../../queries/nodes/DataVisualization/types'
import type { DataColorTheme } from '../../lib/colors'
import type { DashboardLoadAction, DashboardLogicProps, RefreshDashboardItemsAction, RefreshStatus } from './dashboardLogic'
import type { AnyPropertyFilter, Breadcrumb, DashboardLayoutSize, DashboardMode, DashboardPlacement, DashboardTemplateEditorType, DashboardTile, DashboardType, InsightShortId, ProjectTreeRef, QueryBasedInsightModel } from '../../types'
import type { BreakdownFilter, DashboardFilter, InsightsQLVariable, RefreshType } from '../../queries/schema/schema-general'
import type { Dayjs } from '../../lib/dayjs'
import type { DashboardEventSource } from '../../lib/utils/eventUsageLogic'
import type { Layout, Layouts } from '../../../../node_modules/.pnpm/@types+react-grid-layout@1.3.2/node_modules/@types/react-grid-layout/index'
import type { BreakdownColorConfig } from './DashboardInsightColorsModal'
import type { SidePanelSceneContext } from '../../layout/navigation-3000/sidepanel/types'
import type { MaxContextInput } from '../max/maxTypes'

export interface dashboardLogicType extends Logic {
    actionCreators: {
        loadDashboard: (payload: { action: DashboardLoadAction }) => {
            type: 'load dashboard (scenes.dashboard.dashboardLogic)'
            payload: {
                action: DashboardLoadAction
            }
        }
        loadDashboardStreaming: (payload: { action: DashboardLoadAction; manualDashboardRefresh?: boolean }) => {
            type: 'load dashboard streaming (scenes.dashboard.dashboardLogic)'
            payload: {
                action: DashboardLoadAction
                manualDashboardRefresh?: boolean | undefined
            }
        }
        loadDashboardMetadataSuccess: (dashboard: DashboardType<QueryBasedInsightModel> | null) => {
            type: 'load dashboard metadata success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
            }
        }
        receiveTileFromStream: (data: { order: number; tile: any }) => {
            type: 'receive tile from stream (scenes.dashboard.dashboardLogic)'
            payload: {
                order: number
                tile: any
            }
        }
        tileStreamingComplete: () => {
            type: 'tile streaming complete (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        tileStreamingFailure: (error: any) => {
            type: 'tile streaming failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: any
            }
        }
        loadingDashboardItemsStarted: (action: DashboardLoadAction) => {
            type: 'loading dashboard items started (scenes.dashboard.dashboardLogic)'
            payload: {
                action: DashboardLoadAction
            }
        }
        setInitialLoadResponseBytes: (responseBytes: number) => {
            type: 'set initial load response bytes (scenes.dashboard.dashboardLogic)'
            payload: {
                responseBytes: number
            }
        }
        triggerDashboardRefresh: () => {
            type: 'trigger dashboard refresh (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        refreshDashboardItem: (payload: { tile: DashboardTile<QueryBasedInsightModel> }) => {
            type: 'refresh dashboard item (scenes.dashboard.dashboardLogic)'
            payload: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        }
        refreshDashboardItems: (payload: {
            action: DashboardLoadAction | RefreshDashboardItemsAction
            forceRefresh?: boolean
        }) => {
            type: 'refresh dashboard items (scenes.dashboard.dashboardLogic)'
            payload: {
                action: DashboardLoadAction | RefreshDashboardItemsAction
                forceRefresh?: boolean | undefined
            }
        }
        setRefreshStatus: (
            shortId: InsightShortId,
            loading?: any,
            queued?: any
        ) => {
            type: 'set refresh status (scenes.dashboard.dashboardLogic)'
            payload: {
                loading: any
                queued: any
                shortId: InsightShortId
            }
        }
        setRefreshStatuses: (
            shortIds: InsightShortId[],
            loading?: any,
            queued?: any
        ) => {
            type: 'set refresh statuses (scenes.dashboard.dashboardLogic)'
            payload: {
                loading: any
                queued: any
                shortIds: InsightShortId[]
            }
        }
        setRefreshError: (
            shortId: InsightShortId,
            error?: Error
        ) => {
            type: 'set refresh error (scenes.dashboard.dashboardLogic)'
            payload: {
                error: Error | undefined
                shortId: InsightShortId
            }
        }
        abortQuery: (payload: { queryId: string; queryStartTime: number }) => {
            type: 'abort query (scenes.dashboard.dashboardLogic)'
            payload: {
                queryId: string
                queryStartTime: number
            }
        }
        abortAnyRunningQuery: () => {
            type: 'abort any running query (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        cancelDashboardRefresh: () => {
            type: 'cancel dashboard refresh (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        setAutoRefresh: (
            enabled: boolean,
            interval: number
        ) => {
            type: 'set auto refresh (scenes.dashboard.dashboardLogic)'
            payload: {
                enabled: boolean
                interval: number
            }
        }
        resetInterval: () => {
            type: 'reset interval (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        setDates: (
            date_from: string | null,
            date_to: string | null | undefined,
            explicitDate?: boolean
        ) => {
            type: 'set dates (scenes.dashboard.dashboardLogic)'
            payload: {
                date_from: string | null
                date_to: string | null | undefined
                explicitDate: boolean | undefined
            }
        }
        setProperties: (properties: AnyPropertyFilter[] | null) => {
            type: 'set properties (scenes.dashboard.dashboardLogic)'
            payload: {
                properties: AnyPropertyFilter[] | null
            }
        }
        setBreakdownFilter: (breakdown_filter: BreakdownFilter | null) => {
            type: 'set breakdown filter (scenes.dashboard.dashboardLogic)'
            payload: {
                breakdown_filter: BreakdownFilter | null
            }
        }
        setExternalFilters: (filters: DashboardFilter) => {
            type: 'set external filters (scenes.dashboard.dashboardLogic)'
            payload: {
                filters: DashboardFilter
            }
        }
        saveEditModeChanges: () => {
            type: 'save edit mode changes (scenes.dashboard.dashboardLogic)'
            payload: boolean
        }
        resetUrlFilters: () => {
            type: 'reset url filters (scenes.dashboard.dashboardLogic)'
            payload: boolean
        }
        resetIntermittentFilters: () => {
            type: 'reset intermittent filters (scenes.dashboard.dashboardLogic)'
            payload: boolean
        }
        applyFilters: () => {
            type: 'apply filters (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        resetUrlVariables: () => {
            type: 'reset url variables (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        setInitialVariablesLoaded: (initialVariablesLoaded: boolean) => {
            type: 'set initial variables loaded (scenes.dashboard.dashboardLogic)'
            payload: {
                initialVariablesLoaded: boolean
            }
        }
        updateDashboardLastRefresh: (lastDashboardRefresh: Dayjs) => {
            type: 'update dashboard last refresh (scenes.dashboard.dashboardLogic)'
            payload: {
                lastDashboardRefresh: Dayjs
            }
        }
        overrideVariableValue: (
            variableId: string,
            value: any,
            isNull: boolean
        ) => {
            type: 'override variable value (scenes.dashboard.dashboardLogic)'
            payload: {
                isNull: boolean
                value: any
                variableId: string
            }
        }
        setAccessDeniedToDashboard: () => {
            type: 'set access denied to dashboard (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        triggerDashboardUpdate: (payload: any) => {
            type: 'trigger dashboard update (scenes.dashboard.dashboardLogic)'
            payload: {
                payload: any
            }
        }
        updateDashboardTags: (tags: string[]) => {
            type: 'update dashboard tags (scenes.dashboard.dashboardLogic)'
            payload: {
                tags: string[]
            }
        }
        setPageVisibility: (visible: boolean) => {
            type: 'set page visibility (scenes.dashboard.dashboardLogic)'
            payload: {
                visible: boolean
            }
        }
        setSubscriptionMode: (
            enabled: boolean,
            id?: number | 'new'
        ) => {
            type: 'set subscription mode (scenes.dashboard.dashboardLogic)'
            payload: {
                enabled: boolean
                id: number | 'new' | undefined
            }
        }
        setDashboardMode: (
            mode: DashboardMode | null,
            source: DashboardEventSource | null
        ) => {
            type: 'set dashboard mode (scenes.dashboard.dashboardLogic)'
            payload: {
                mode: DashboardMode | null
                source: DashboardEventSource | null
            }
        }
        updateLayouts: (layouts: Layouts) => {
            type: 'update layouts (scenes.dashboard.dashboardLogic)'
            payload: {
                layouts: Layouts
            }
        }
        updateContainerWidth: (
            containerWidth: number,
            columns: number
        ) => {
            type: 'update container width (scenes.dashboard.dashboardLogic)'
            payload: {
                columns: number
                containerWidth: number
            }
        }
        updateTileColor: (
            tileId: number,
            color: string | null
        ) => {
            type: 'update tile color (scenes.dashboard.dashboardLogic)'
            payload: {
                color: string | null
                tileId: number
            }
        }
        duplicateTile: (tile: DashboardTile<QueryBasedInsightModel>) => {
            type: 'duplicate tile (scenes.dashboard.dashboardLogic)'
            payload: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        }
        removeTile: (tile: DashboardTile<QueryBasedInsightModel>) => {
            type: 'remove tile (scenes.dashboard.dashboardLogic)'
            payload: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        }
        moveToDashboard: (
            tile: DashboardTile<QueryBasedInsightModel>,
            fromDashboard: number,
            toDashboard: number,
            toDashboardName: string,
            allowUndo?: boolean
        ) => {
            type: 'move to dashboard (scenes.dashboard.dashboardLogic)'
            payload: {
                allowUndo: boolean
                fromDashboard: number
                tile: DashboardTile<QueryBasedInsightModel>
                toDashboard: number
                toDashboardName: string
            }
        }
        setTextTileId: (textTileId: number | 'new' | null) => {
            type: 'set text tile id (scenes.dashboard.dashboardLogic)'
            payload: {
                textTileId: number | 'new' | null
            }
        }
        setTileOverride: (tile: DashboardTile<QueryBasedInsightModel>) => {
            type: 'set tile override (scenes.dashboard.dashboardLogic)'
            payload: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        }
        setShouldReportOnAPILoad: (shouldReport: boolean) => {
            type: 'set should report on a p i load (scenes.dashboard.dashboardLogic)'
            payload: {
                shouldReport: boolean
            }
        }
        reportDashboardViewed: () => {
            type: 'report dashboard viewed (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        reportInsightsViewed: (insights: QueryBasedInsightModel[]) => {
            type: 'report insights viewed (scenes.dashboard.dashboardLogic)'
            payload: {
                insights: QueryBasedInsightModel[]
            }
        }
        setBreakdownColorConfig: (config: BreakdownColorConfig) => {
            type: 'set breakdown color config (scenes.dashboard.dashboardLogic)'
            payload: {
                config: BreakdownColorConfig
            }
        }
        setDataColorThemeId: (dataColorThemeId: number | null) => {
            type: 'set data color theme id (scenes.dashboard.dashboardLogic)'
            payload: {
                dataColorThemeId: number | null
            }
        }
        setLoadLayoutFromServerOnPreview: (loadLayoutFromServerOnPreview: boolean) => {
            type: 'set load layout from server on preview (scenes.dashboard.dashboardLogic)'
            payload: {
                loadLayoutFromServerOnPreview: boolean
            }
        }
        dashboardNotFound: () => {
            type: 'dashboard not found (scenes.dashboard.dashboardLogic)'
            payload: {
                value: true
            }
        }
        loadDashboardSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                action: DashboardLoadAction
            }
        ) => {
            type: 'load dashboard success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: {
                    action: DashboardLoadAction
                }
            }
        }
        loadDashboardFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load dashboard failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadDashboardStreamingSuccess: (
            dashboard: null,
            payload?: {
                action: DashboardLoadAction
                manualDashboardRefresh?: boolean | undefined
            }
        ) => {
            type: 'load dashboard streaming success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: null
                payload?: {
                    action: DashboardLoadAction
                    manualDashboardRefresh?: boolean | undefined
                }
            }
        }
        loadDashboardStreamingFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load dashboard streaming failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        saveEditModeChangesSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: boolean
        ) => {
            type: 'save edit mode changes success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: boolean
            }
        }
        saveEditModeChangesFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'save edit mode changes failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        updateTileColorSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                color: string | null
                tileId: number
            }
        ) => {
            type: 'update tile color success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: {
                    color: string | null
                    tileId: number
                }
            }
        }
        updateTileColorFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'update tile color failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        removeTileSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        ) => {
            type: 'remove tile success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: {
                    tile: DashboardTile<QueryBasedInsightModel>
                }
            }
        }
        removeTileFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'remove tile failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        setDashboardModeSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                mode: DashboardMode | null
                source: DashboardEventSource | null
            }
        ) => {
            type: 'set dashboard mode success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: {
                    mode: DashboardMode | null
                    source: DashboardEventSource | null
                }
            }
        }
        setDashboardModeFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'set dashboard mode failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        duplicateTileSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        ) => {
            type: 'duplicate tile success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: {
                    tile: DashboardTile<QueryBasedInsightModel>
                }
            }
        }
        duplicateTileFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'duplicate tile failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        moveToDashboardSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                allowUndo: boolean
                fromDashboard: number
                tile: DashboardTile<QueryBasedInsightModel>
                toDashboard: number
                toDashboardName: string
            }
        ) => {
            type: 'move to dashboard success (scenes.dashboard.dashboardLogic)'
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null
                payload?: {
                    allowUndo: boolean
                    fromDashboard: number
                    tile: DashboardTile<QueryBasedInsightModel>
                    toDashboard: number
                    toDashboardName: string
                }
            }
        }
        moveToDashboardFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'move to dashboard failure (scenes.dashboard.dashboardLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'load dashboard (scenes.dashboard.dashboardLogic)': 'loadDashboard'
        'load dashboard streaming (scenes.dashboard.dashboardLogic)': 'loadDashboardStreaming'
        'load dashboard metadata success (scenes.dashboard.dashboardLogic)': 'loadDashboardMetadataSuccess'
        'receive tile from stream (scenes.dashboard.dashboardLogic)': 'receiveTileFromStream'
        'tile streaming complete (scenes.dashboard.dashboardLogic)': 'tileStreamingComplete'
        'tile streaming failure (scenes.dashboard.dashboardLogic)': 'tileStreamingFailure'
        'loading dashboard items started (scenes.dashboard.dashboardLogic)': 'loadingDashboardItemsStarted'
        'set initial load response bytes (scenes.dashboard.dashboardLogic)': 'setInitialLoadResponseBytes'
        'trigger dashboard refresh (scenes.dashboard.dashboardLogic)': 'triggerDashboardRefresh'
        'refresh dashboard item (scenes.dashboard.dashboardLogic)': 'refreshDashboardItem'
        'refresh dashboard items (scenes.dashboard.dashboardLogic)': 'refreshDashboardItems'
        'set refresh status (scenes.dashboard.dashboardLogic)': 'setRefreshStatus'
        'set refresh statuses (scenes.dashboard.dashboardLogic)': 'setRefreshStatuses'
        'set refresh error (scenes.dashboard.dashboardLogic)': 'setRefreshError'
        'abort query (scenes.dashboard.dashboardLogic)': 'abortQuery'
        'abort any running query (scenes.dashboard.dashboardLogic)': 'abortAnyRunningQuery'
        'cancel dashboard refresh (scenes.dashboard.dashboardLogic)': 'cancelDashboardRefresh'
        'set auto refresh (scenes.dashboard.dashboardLogic)': 'setAutoRefresh'
        'reset interval (scenes.dashboard.dashboardLogic)': 'resetInterval'
        'set dates (scenes.dashboard.dashboardLogic)': 'setDates'
        'set properties (scenes.dashboard.dashboardLogic)': 'setProperties'
        'set breakdown filter (scenes.dashboard.dashboardLogic)': 'setBreakdownFilter'
        'set external filters (scenes.dashboard.dashboardLogic)': 'setExternalFilters'
        'save edit mode changes (scenes.dashboard.dashboardLogic)': 'saveEditModeChanges'
        'reset url filters (scenes.dashboard.dashboardLogic)': 'resetUrlFilters'
        'reset intermittent filters (scenes.dashboard.dashboardLogic)': 'resetIntermittentFilters'
        'apply filters (scenes.dashboard.dashboardLogic)': 'applyFilters'
        'reset url variables (scenes.dashboard.dashboardLogic)': 'resetUrlVariables'
        'set initial variables loaded (scenes.dashboard.dashboardLogic)': 'setInitialVariablesLoaded'
        'update dashboard last refresh (scenes.dashboard.dashboardLogic)': 'updateDashboardLastRefresh'
        'override variable value (scenes.dashboard.dashboardLogic)': 'overrideVariableValue'
        'set access denied to dashboard (scenes.dashboard.dashboardLogic)': 'setAccessDeniedToDashboard'
        'trigger dashboard update (scenes.dashboard.dashboardLogic)': 'triggerDashboardUpdate'
        'update dashboard tags (scenes.dashboard.dashboardLogic)': 'updateDashboardTags'
        'set page visibility (scenes.dashboard.dashboardLogic)': 'setPageVisibility'
        'set subscription mode (scenes.dashboard.dashboardLogic)': 'setSubscriptionMode'
        'set dashboard mode (scenes.dashboard.dashboardLogic)': 'setDashboardMode'
        'update layouts (scenes.dashboard.dashboardLogic)': 'updateLayouts'
        'update container width (scenes.dashboard.dashboardLogic)': 'updateContainerWidth'
        'update tile color (scenes.dashboard.dashboardLogic)': 'updateTileColor'
        'duplicate tile (scenes.dashboard.dashboardLogic)': 'duplicateTile'
        'remove tile (scenes.dashboard.dashboardLogic)': 'removeTile'
        'move to dashboard (scenes.dashboard.dashboardLogic)': 'moveToDashboard'
        'set text tile id (scenes.dashboard.dashboardLogic)': 'setTextTileId'
        'set tile override (scenes.dashboard.dashboardLogic)': 'setTileOverride'
        'set should report on a p i load (scenes.dashboard.dashboardLogic)': 'setShouldReportOnAPILoad'
        'report dashboard viewed (scenes.dashboard.dashboardLogic)': 'reportDashboardViewed'
        'report insights viewed (scenes.dashboard.dashboardLogic)': 'reportInsightsViewed'
        'set breakdown color config (scenes.dashboard.dashboardLogic)': 'setBreakdownColorConfig'
        'set data color theme id (scenes.dashboard.dashboardLogic)': 'setDataColorThemeId'
        'set load layout from server on preview (scenes.dashboard.dashboardLogic)': 'setLoadLayoutFromServerOnPreview'
        'dashboard not found (scenes.dashboard.dashboardLogic)': 'dashboardNotFound'
        'load dashboard success (scenes.dashboard.dashboardLogic)': 'loadDashboardSuccess'
        'load dashboard failure (scenes.dashboard.dashboardLogic)': 'loadDashboardFailure'
        'load dashboard streaming success (scenes.dashboard.dashboardLogic)': 'loadDashboardStreamingSuccess'
        'load dashboard streaming failure (scenes.dashboard.dashboardLogic)': 'loadDashboardStreamingFailure'
        'save edit mode changes success (scenes.dashboard.dashboardLogic)': 'saveEditModeChangesSuccess'
        'save edit mode changes failure (scenes.dashboard.dashboardLogic)': 'saveEditModeChangesFailure'
        'update tile color success (scenes.dashboard.dashboardLogic)': 'updateTileColorSuccess'
        'update tile color failure (scenes.dashboard.dashboardLogic)': 'updateTileColorFailure'
        'remove tile success (scenes.dashboard.dashboardLogic)': 'removeTileSuccess'
        'remove tile failure (scenes.dashboard.dashboardLogic)': 'removeTileFailure'
        'set dashboard mode success (scenes.dashboard.dashboardLogic)': 'setDashboardModeSuccess'
        'set dashboard mode failure (scenes.dashboard.dashboardLogic)': 'setDashboardModeFailure'
        'duplicate tile success (scenes.dashboard.dashboardLogic)': 'duplicateTileSuccess'
        'duplicate tile failure (scenes.dashboard.dashboardLogic)': 'duplicateTileFailure'
        'move to dashboard success (scenes.dashboard.dashboardLogic)': 'moveToDashboardSuccess'
        'move to dashboard failure (scenes.dashboard.dashboardLogic)': 'moveToDashboardFailure'
    }
    actionTypes: {
        loadDashboard: 'load dashboard (scenes.dashboard.dashboardLogic)'
        loadDashboardStreaming: 'load dashboard streaming (scenes.dashboard.dashboardLogic)'
        loadDashboardMetadataSuccess: 'load dashboard metadata success (scenes.dashboard.dashboardLogic)'
        receiveTileFromStream: 'receive tile from stream (scenes.dashboard.dashboardLogic)'
        tileStreamingComplete: 'tile streaming complete (scenes.dashboard.dashboardLogic)'
        tileStreamingFailure: 'tile streaming failure (scenes.dashboard.dashboardLogic)'
        loadingDashboardItemsStarted: 'loading dashboard items started (scenes.dashboard.dashboardLogic)'
        setInitialLoadResponseBytes: 'set initial load response bytes (scenes.dashboard.dashboardLogic)'
        triggerDashboardRefresh: 'trigger dashboard refresh (scenes.dashboard.dashboardLogic)'
        refreshDashboardItem: 'refresh dashboard item (scenes.dashboard.dashboardLogic)'
        refreshDashboardItems: 'refresh dashboard items (scenes.dashboard.dashboardLogic)'
        setRefreshStatus: 'set refresh status (scenes.dashboard.dashboardLogic)'
        setRefreshStatuses: 'set refresh statuses (scenes.dashboard.dashboardLogic)'
        setRefreshError: 'set refresh error (scenes.dashboard.dashboardLogic)'
        abortQuery: 'abort query (scenes.dashboard.dashboardLogic)'
        abortAnyRunningQuery: 'abort any running query (scenes.dashboard.dashboardLogic)'
        cancelDashboardRefresh: 'cancel dashboard refresh (scenes.dashboard.dashboardLogic)'
        setAutoRefresh: 'set auto refresh (scenes.dashboard.dashboardLogic)'
        resetInterval: 'reset interval (scenes.dashboard.dashboardLogic)'
        setDates: 'set dates (scenes.dashboard.dashboardLogic)'
        setProperties: 'set properties (scenes.dashboard.dashboardLogic)'
        setBreakdownFilter: 'set breakdown filter (scenes.dashboard.dashboardLogic)'
        setExternalFilters: 'set external filters (scenes.dashboard.dashboardLogic)'
        saveEditModeChanges: 'save edit mode changes (scenes.dashboard.dashboardLogic)'
        resetUrlFilters: 'reset url filters (scenes.dashboard.dashboardLogic)'
        resetIntermittentFilters: 'reset intermittent filters (scenes.dashboard.dashboardLogic)'
        applyFilters: 'apply filters (scenes.dashboard.dashboardLogic)'
        resetUrlVariables: 'reset url variables (scenes.dashboard.dashboardLogic)'
        setInitialVariablesLoaded: 'set initial variables loaded (scenes.dashboard.dashboardLogic)'
        updateDashboardLastRefresh: 'update dashboard last refresh (scenes.dashboard.dashboardLogic)'
        overrideVariableValue: 'override variable value (scenes.dashboard.dashboardLogic)'
        setAccessDeniedToDashboard: 'set access denied to dashboard (scenes.dashboard.dashboardLogic)'
        triggerDashboardUpdate: 'trigger dashboard update (scenes.dashboard.dashboardLogic)'
        updateDashboardTags: 'update dashboard tags (scenes.dashboard.dashboardLogic)'
        setPageVisibility: 'set page visibility (scenes.dashboard.dashboardLogic)'
        setSubscriptionMode: 'set subscription mode (scenes.dashboard.dashboardLogic)'
        setDashboardMode: 'set dashboard mode (scenes.dashboard.dashboardLogic)'
        updateLayouts: 'update layouts (scenes.dashboard.dashboardLogic)'
        updateContainerWidth: 'update container width (scenes.dashboard.dashboardLogic)'
        updateTileColor: 'update tile color (scenes.dashboard.dashboardLogic)'
        duplicateTile: 'duplicate tile (scenes.dashboard.dashboardLogic)'
        removeTile: 'remove tile (scenes.dashboard.dashboardLogic)'
        moveToDashboard: 'move to dashboard (scenes.dashboard.dashboardLogic)'
        setTextTileId: 'set text tile id (scenes.dashboard.dashboardLogic)'
        setTileOverride: 'set tile override (scenes.dashboard.dashboardLogic)'
        setShouldReportOnAPILoad: 'set should report on a p i load (scenes.dashboard.dashboardLogic)'
        reportDashboardViewed: 'report dashboard viewed (scenes.dashboard.dashboardLogic)'
        reportInsightsViewed: 'report insights viewed (scenes.dashboard.dashboardLogic)'
        setBreakdownColorConfig: 'set breakdown color config (scenes.dashboard.dashboardLogic)'
        setDataColorThemeId: 'set data color theme id (scenes.dashboard.dashboardLogic)'
        setLoadLayoutFromServerOnPreview: 'set load layout from server on preview (scenes.dashboard.dashboardLogic)'
        dashboardNotFound: 'dashboard not found (scenes.dashboard.dashboardLogic)'
        loadDashboardSuccess: 'load dashboard success (scenes.dashboard.dashboardLogic)'
        loadDashboardFailure: 'load dashboard failure (scenes.dashboard.dashboardLogic)'
        loadDashboardStreamingSuccess: 'load dashboard streaming success (scenes.dashboard.dashboardLogic)'
        loadDashboardStreamingFailure: 'load dashboard streaming failure (scenes.dashboard.dashboardLogic)'
        saveEditModeChangesSuccess: 'save edit mode changes success (scenes.dashboard.dashboardLogic)'
        saveEditModeChangesFailure: 'save edit mode changes failure (scenes.dashboard.dashboardLogic)'
        updateTileColorSuccess: 'update tile color success (scenes.dashboard.dashboardLogic)'
        updateTileColorFailure: 'update tile color failure (scenes.dashboard.dashboardLogic)'
        removeTileSuccess: 'remove tile success (scenes.dashboard.dashboardLogic)'
        removeTileFailure: 'remove tile failure (scenes.dashboard.dashboardLogic)'
        setDashboardModeSuccess: 'set dashboard mode success (scenes.dashboard.dashboardLogic)'
        setDashboardModeFailure: 'set dashboard mode failure (scenes.dashboard.dashboardLogic)'
        duplicateTileSuccess: 'duplicate tile success (scenes.dashboard.dashboardLogic)'
        duplicateTileFailure: 'duplicate tile failure (scenes.dashboard.dashboardLogic)'
        moveToDashboardSuccess: 'move to dashboard success (scenes.dashboard.dashboardLogic)'
        moveToDashboardFailure: 'move to dashboard failure (scenes.dashboard.dashboardLogic)'
    }
    actions: {
        loadDashboard: (payload: { action: DashboardLoadAction }) => void
        loadDashboardStreaming: (payload: { action: DashboardLoadAction; manualDashboardRefresh?: boolean }) => void
        loadDashboardMetadataSuccess: (dashboard: DashboardType<QueryBasedInsightModel> | null) => void
        receiveTileFromStream: (data: { order: number; tile: any }) => void
        tileStreamingComplete: () => void
        tileStreamingFailure: (error: any) => void
        loadingDashboardItemsStarted: (action: DashboardLoadAction) => void
        setInitialLoadResponseBytes: (responseBytes: number) => void
        triggerDashboardRefresh: () => void
        refreshDashboardItem: (payload: { tile: DashboardTile<QueryBasedInsightModel> }) => void
        refreshDashboardItems: (payload: {
            action: DashboardLoadAction | RefreshDashboardItemsAction
            forceRefresh?: boolean
        }) => void
        setRefreshStatus: (shortId: InsightShortId, loading?: any, queued?: any) => void
        setRefreshStatuses: (shortIds: InsightShortId[], loading?: any, queued?: any) => void
        setRefreshError: (shortId: InsightShortId, error?: Error) => void
        abortQuery: (payload: { queryId: string; queryStartTime: number }) => void
        abortAnyRunningQuery: () => void
        cancelDashboardRefresh: () => void
        setAutoRefresh: (enabled: boolean, interval: number) => void
        resetInterval: () => void
        setDates: (date_from: string | null, date_to: string | null | undefined, explicitDate?: boolean) => void
        setProperties: (properties: AnyPropertyFilter[] | null) => void
        setBreakdownFilter: (breakdown_filter: BreakdownFilter | null) => void
        setExternalFilters: (filters: DashboardFilter) => void
        saveEditModeChanges: () => void
        resetUrlFilters: () => void
        resetIntermittentFilters: () => void
        applyFilters: () => void
        resetUrlVariables: () => void
        setInitialVariablesLoaded: (initialVariablesLoaded: boolean) => void
        updateDashboardLastRefresh: (lastDashboardRefresh: Dayjs) => void
        overrideVariableValue: (variableId: string, value: any, isNull: boolean) => void
        setAccessDeniedToDashboard: () => void
        triggerDashboardUpdate: (payload: any) => void
        updateDashboardTags: (tags: string[]) => void
        setPageVisibility: (visible: boolean) => void
        setSubscriptionMode: (enabled: boolean, id?: number | 'new') => void
        setDashboardMode: (mode: DashboardMode | null, source: DashboardEventSource | null) => void
        updateLayouts: (layouts: Layouts) => void
        updateContainerWidth: (containerWidth: number, columns: number) => void
        updateTileColor: (tileId: number, color: string | null) => void
        duplicateTile: (tile: DashboardTile<QueryBasedInsightModel>) => void
        removeTile: (tile: DashboardTile<QueryBasedInsightModel>) => void
        moveToDashboard: (
            tile: DashboardTile<QueryBasedInsightModel>,
            fromDashboard: number,
            toDashboard: number,
            toDashboardName: string,
            allowUndo?: boolean
        ) => void
        setTextTileId: (textTileId: number | 'new' | null) => void
        setTileOverride: (tile: DashboardTile<QueryBasedInsightModel>) => void
        setShouldReportOnAPILoad: (shouldReport: boolean) => void
        reportDashboardViewed: () => void
        reportInsightsViewed: (insights: QueryBasedInsightModel[]) => void
        setBreakdownColorConfig: (config: BreakdownColorConfig) => void
        setDataColorThemeId: (dataColorThemeId: number | null) => void
        setLoadLayoutFromServerOnPreview: (loadLayoutFromServerOnPreview: boolean) => void
        dashboardNotFound: () => void
        loadDashboardSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                action: DashboardLoadAction
            }
        ) => void
        loadDashboardFailure: (error: string, errorObject?: any) => void
        loadDashboardStreamingSuccess: (
            dashboard: null,
            payload?: {
                action: DashboardLoadAction
                manualDashboardRefresh?: boolean | undefined
            }
        ) => void
        loadDashboardStreamingFailure: (error: string, errorObject?: any) => void
        saveEditModeChangesSuccess: (dashboard: DashboardType<QueryBasedInsightModel> | null, payload?: boolean) => void
        saveEditModeChangesFailure: (error: string, errorObject?: any) => void
        updateTileColorSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                color: string | null
                tileId: number
            }
        ) => void
        updateTileColorFailure: (error: string, errorObject?: any) => void
        removeTileSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        ) => void
        removeTileFailure: (error: string, errorObject?: any) => void
        setDashboardModeSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                mode: DashboardMode | null
                source: DashboardEventSource | null
            }
        ) => void
        setDashboardModeFailure: (error: string, errorObject?: any) => void
        duplicateTileSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        ) => void
        duplicateTileFailure: (error: string, errorObject?: any) => void
        moveToDashboardSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                allowUndo: boolean
                fromDashboard: number
                tile: DashboardTile<QueryBasedInsightModel>
                toDashboard: number
                toDashboardName: string
            }
        ) => void
        moveToDashboardFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadDashboard: (payload: { action: DashboardLoadAction }) => Promise<any>
        loadDashboardStreaming: (payload: {
            action: DashboardLoadAction
            manualDashboardRefresh?: boolean
        }) => Promise<any>
        loadDashboardMetadataSuccess: (dashboard: DashboardType<QueryBasedInsightModel> | null) => Promise<any>
        receiveTileFromStream: (data: { order: number; tile: any }) => Promise<any>
        tileStreamingComplete: () => Promise<any>
        tileStreamingFailure: (error: any) => Promise<any>
        loadingDashboardItemsStarted: (action: DashboardLoadAction) => Promise<any>
        setInitialLoadResponseBytes: (responseBytes: number) => Promise<any>
        triggerDashboardRefresh: () => Promise<any>
        refreshDashboardItem: (payload: { tile: DashboardTile<QueryBasedInsightModel> }) => Promise<any>
        refreshDashboardItems: (payload: {
            action: DashboardLoadAction | RefreshDashboardItemsAction
            forceRefresh?: boolean
        }) => Promise<any>
        setRefreshStatus: (shortId: InsightShortId, loading?: any, queued?: any) => Promise<any>
        setRefreshStatuses: (shortIds: InsightShortId[], loading?: any, queued?: any) => Promise<any>
        setRefreshError: (shortId: InsightShortId, error?: Error) => Promise<any>
        abortQuery: (payload: { queryId: string; queryStartTime: number }) => Promise<any>
        abortAnyRunningQuery: () => Promise<any>
        cancelDashboardRefresh: () => Promise<any>
        setAutoRefresh: (enabled: boolean, interval: number) => Promise<any>
        resetInterval: () => Promise<any>
        setDates: (date_from: string | null, date_to: string | null | undefined, explicitDate?: boolean) => Promise<any>
        setProperties: (properties: AnyPropertyFilter[] | null) => Promise<any>
        setBreakdownFilter: (breakdown_filter: BreakdownFilter | null) => Promise<any>
        setExternalFilters: (filters: DashboardFilter) => Promise<any>
        saveEditModeChanges: () => Promise<any>
        resetUrlFilters: () => Promise<any>
        resetIntermittentFilters: () => Promise<any>
        applyFilters: () => Promise<any>
        resetUrlVariables: () => Promise<any>
        setInitialVariablesLoaded: (initialVariablesLoaded: boolean) => Promise<any>
        updateDashboardLastRefresh: (lastDashboardRefresh: Dayjs) => Promise<any>
        overrideVariableValue: (variableId: string, value: any, isNull: boolean) => Promise<any>
        setAccessDeniedToDashboard: () => Promise<any>
        triggerDashboardUpdate: (payload: any) => Promise<any>
        updateDashboardTags: (tags: string[]) => Promise<any>
        setPageVisibility: (visible: boolean) => Promise<any>
        setSubscriptionMode: (enabled: boolean, id?: number | 'new') => Promise<any>
        setDashboardMode: (mode: DashboardMode | null, source: DashboardEventSource | null) => Promise<any>
        updateLayouts: (layouts: Layouts) => Promise<any>
        updateContainerWidth: (containerWidth: number, columns: number) => Promise<any>
        updateTileColor: (tileId: number, color: string | null) => Promise<any>
        duplicateTile: (tile: DashboardTile<QueryBasedInsightModel>) => Promise<any>
        removeTile: (tile: DashboardTile<QueryBasedInsightModel>) => Promise<any>
        moveToDashboard: (
            tile: DashboardTile<QueryBasedInsightModel>,
            fromDashboard: number,
            toDashboard: number,
            toDashboardName: string,
            allowUndo?: boolean
        ) => Promise<any>
        setTextTileId: (textTileId: number | 'new' | null) => Promise<any>
        setTileOverride: (tile: DashboardTile<QueryBasedInsightModel>) => Promise<any>
        setShouldReportOnAPILoad: (shouldReport: boolean) => Promise<any>
        reportDashboardViewed: () => Promise<any>
        reportInsightsViewed: (insights: QueryBasedInsightModel[]) => Promise<any>
        setBreakdownColorConfig: (config: BreakdownColorConfig) => Promise<any>
        setDataColorThemeId: (dataColorThemeId: number | null) => Promise<any>
        setLoadLayoutFromServerOnPreview: (loadLayoutFromServerOnPreview: boolean) => Promise<any>
        dashboardNotFound: () => Promise<any>
        loadDashboardSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                action: DashboardLoadAction
            }
        ) => Promise<any>
        loadDashboardFailure: (error: string, errorObject?: any) => Promise<any>
        loadDashboardStreamingSuccess: (
            dashboard: null,
            payload?: {
                action: DashboardLoadAction
                manualDashboardRefresh?: boolean | undefined
            }
        ) => Promise<any>
        loadDashboardStreamingFailure: (error: string, errorObject?: any) => Promise<any>
        saveEditModeChangesSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: boolean
        ) => Promise<any>
        saveEditModeChangesFailure: (error: string, errorObject?: any) => Promise<any>
        updateTileColorSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                color: string | null
                tileId: number
            }
        ) => Promise<any>
        updateTileColorFailure: (error: string, errorObject?: any) => Promise<any>
        removeTileSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        ) => Promise<any>
        removeTileFailure: (error: string, errorObject?: any) => Promise<any>
        setDashboardModeSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                mode: DashboardMode | null
                source: DashboardEventSource | null
            }
        ) => Promise<any>
        setDashboardModeFailure: (error: string, errorObject?: any) => Promise<any>
        duplicateTileSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                tile: DashboardTile<QueryBasedInsightModel>
            }
        ) => Promise<any>
        duplicateTileFailure: (error: string, errorObject?: any) => Promise<any>
        moveToDashboardSuccess: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            payload?: {
                allowUndo: boolean
                fromDashboard: number
                tile: DashboardTile<QueryBasedInsightModel>
                toDashboard: number
                toDashboardName: string
            }
        ) => Promise<any>
        moveToDashboardFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        dashboard: DashboardType<QueryBasedInsightModel> | null
        dashboardLoading: boolean
        dashboardStreaming: boolean
        loadingPreview: boolean
        cancellingPreview: boolean
        pageVisibility: boolean
        accessDeniedToDashboard: boolean
        dashboardFailedToLoad: boolean
        dashboardLayouts: Record<DashboardTile['id'], DashboardTile['layouts']>
        temporaryBreakdownColors: BreakdownColorConfig[]
        dataColorThemeId: number | null
        loadTimer: Date | null
        dashboardLoadData: {
            action: DashboardLoadAction | undefined
            dashboardQueryId: string
            responseBytes: number
            startTime: number
        }
        refreshStatus: Record<string, RefreshStatus>
        columns: number | null
        containerWidth: number | null
        dashboardMode: DashboardMode | null
        loadLayoutFromServerOnPreview: boolean
        autoRefresh: {
            enabled: boolean
            interval: number
        }
        shouldReportOnAPILoad: boolean
        showSubscriptions: boolean
        subscriptionId: number | 'new' | null
        showTextTileModal: boolean
        textTileId: number | 'new' | null
        lastDashboardRefresh: Dayjs | null
        error404: boolean
        initialVariablesLoaded: boolean
        externalFilters: DashboardFilter
        intermittentFilters: DashboardFilter
        isSavingTags: boolean
    }
    events: {
        afterMount: () => void
        beforeUnmount: () => void
    }
    key: number
    listeners: {
        setRefreshError: ((
            action: {
                type: 'set refresh error (scenes.dashboard.dashboardLogic)'
                payload: {
                    error: Error | undefined
                    shortId: InsightShortId
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setRefreshStatuses: ((
            action: {
                type: 'set refresh statuses (scenes.dashboard.dashboardLogic)'
                payload: {
                    loading: any
                    queued: any
                    shortIds: InsightShortId[]
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setRefreshStatus: ((
            action: {
                type: 'set refresh status (scenes.dashboard.dashboardLogic)'
                payload: {
                    loading: any
                    queued: any
                    shortId: InsightShortId
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setPageVisibility: ((
            action: {
                type: 'set page visibility (scenes.dashboard.dashboardLogic)'
                payload: {
                    visible: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadDashboardFailure: ((
            action: {
                type: 'load dashboard failure (scenes.dashboard.dashboardLogic)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        tileStreamingFailure: ((
            action: {
                type: 'tile streaming failure (scenes.dashboard.dashboardLogic)'
                payload: {
                    error: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        'duplicate insight success (models.insightsModel)': ((
            action: {
                payload: {
                    item: QueryBasedInsightModel
                }
                type: 'duplicate insight success (models.insightsModel)'
            },
            previousState: any
        ) => void | Promise<void>)[]
        'tile added to dashboard (models.dashboardsModel)': ((
            action: {
                payload: {
                    dashboardId: number
                }
                type: 'tile added to dashboard (models.dashboardsModel)'
            },
            previousState: any
        ) => void | Promise<void>)[]
        'update dashboard insight (models.dashboardsModel)': ((
            action: {
                payload: {
                    extraDashboardIds: number[] | undefined
                    insight: QueryBasedInsightModel
                }
                type: 'update dashboard insight (models.dashboardsModel)'
            },
            previousState: any
        ) => void | Promise<void>)[]
        moveToDashboardSuccess: ((
            action: {
                type: 'move to dashboard success (scenes.dashboard.dashboardLogic)'
                payload: {
                    dashboard: DashboardType<QueryBasedInsightModel> | null
                    payload?: {
                        allowUndo: boolean
                        fromDashboard: number
                        tile: DashboardTile<QueryBasedInsightModel>
                        toDashboard: number
                        toDashboardName: string
                    }
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        triggerDashboardUpdate: ((
            action: {
                type: 'trigger dashboard update (scenes.dashboard.dashboardLogic)'
                payload: {
                    payload: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        triggerDashboardRefresh: ((
            action: {
                type: 'trigger dashboard refresh (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        refreshDashboardItem: ((
            action: {
                type: 'refresh dashboard item (scenes.dashboard.dashboardLogic)'
                payload: {
                    tile: DashboardTile<QueryBasedInsightModel>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        refreshDashboardItems: ((
            action: {
                type: 'refresh dashboard items (scenes.dashboard.dashboardLogic)'
                payload: {
                    action: DashboardLoadAction | RefreshDashboardItemsAction
                    forceRefresh?: boolean | undefined
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        saveEditModeChanges: ((
            action: {
                type: 'save edit mode changes (scenes.dashboard.dashboardLogic)'
                payload: boolean
            },
            previousState: any
        ) => void | Promise<void>)[]
        setDashboardMode: ((
            action: {
                type: 'set dashboard mode (scenes.dashboard.dashboardLogic)'
                payload: {
                    mode: DashboardMode | null
                    source: DashboardEventSource | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setAutoRefresh: ((
            action: {
                type: 'set auto refresh (scenes.dashboard.dashboardLogic)'
                payload: {
                    enabled: boolean
                    interval: number
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        resetInterval: ((
            action: {
                type: 'reset interval (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadDashboardSuccess: ((
            action: {
                type: 'load dashboard success (scenes.dashboard.dashboardLogic)'
                payload: {
                    dashboard: DashboardType<QueryBasedInsightModel> | null
                    payload?: {
                        action: DashboardLoadAction
                    }
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadDashboardMetadataSuccess: ((
            action: {
                type: 'load dashboard metadata success (scenes.dashboard.dashboardLogic)'
                payload: {
                    dashboard: DashboardType<QueryBasedInsightModel> | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        tileStreamingComplete: ((
            action: {
                type: 'tile streaming complete (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportInsightsViewed: ((
            action: {
                type: 'report insights viewed (scenes.dashboard.dashboardLogic)'
                payload: {
                    insights: QueryBasedInsightModel[]
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportDashboardViewed: ((
            action: {
                type: 'report dashboard viewed (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        abortAnyRunningQuery: ((
            action: {
                type: 'abort any running query (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        cancelDashboardRefresh: ((
            action: {
                type: 'cancel dashboard refresh (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        abortQuery: ((
            action: {
                type: 'abort query (scenes.dashboard.dashboardLogic)'
                payload: {
                    queryId: string
                    queryStartTime: number
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        applyFilters: ((
            action: {
                type: 'apply filters (scenes.dashboard.dashboardLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setProperties: ((
            action: {
                type: 'set properties (scenes.dashboard.dashboardLogic)'
                payload: {
                    properties: AnyPropertyFilter[] | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setDates: ((
            action: {
                type: 'set dates (scenes.dashboard.dashboardLogic)'
                payload: {
                    date_from: string | null
                    date_to: string | null | undefined
                    explicitDate: boolean | undefined
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setBreakdownFilter: ((
            action: {
                type: 'set breakdown filter (scenes.dashboard.dashboardLogic)'
                payload: {
                    breakdown_filter: BreakdownFilter | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setExternalFilters: ((
            action: {
                type: 'set external filters (scenes.dashboard.dashboardLogic)'
                payload: {
                    filters: DashboardFilter
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        overrideVariableValue: ((
            action: {
                type: 'override variable value (scenes.dashboard.dashboardLogic)'
                payload: {
                    isNull: boolean
                    value: any
                    variableId: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        'get variables success (queries.nodes.DataVisualization.Components.Variables.variableDataLogic)': ((
            action: {
                payload: {
                    payload?: any
                    variables: Variable[]
                }
                type: 'get variables success (queries.nodes.DataVisualization.Components.Variables.variableDataLogic)'
            },
            previousState: any
        ) => void | Promise<void>)[]
        updateDashboardLastRefresh: ((
            action: {
                type: 'update dashboard last refresh (scenes.dashboard.dashboardLogic)'
                payload: {
                    lastDashboardRefresh: Dayjs
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        updateDashboardTags: ((
            action: {
                type: 'update dashboard tags (scenes.dashboard.dashboardLogic)'
                payload: {
                    tags: string[]
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setTileOverride: ((
            action: {
                type: 'set tile override (scenes.dashboard.dashboardLogic)'
                payload: {
                    tile: DashboardTile<QueryBasedInsightModel>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'dashboard', 'dashboardLogic']
    pathString: 'scenes.dashboard.dashboardLogic'
    props: DashboardLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        dashboard: DashboardType<QueryBasedInsightModel> | null
        dashboardLoading: boolean
        dashboardStreaming: boolean
        loadingPreview: boolean
        cancellingPreview: boolean
        pageVisibility: boolean
        accessDeniedToDashboard: boolean
        dashboardFailedToLoad: boolean
        dashboardLayouts: Record<DashboardTile['id'], DashboardTile['layouts']>
        temporaryBreakdownColors: BreakdownColorConfig[]
        dataColorThemeId: number | null
        loadTimer: Date | null
        dashboardLoadData: {
            action: DashboardLoadAction | undefined
            dashboardQueryId: string
            responseBytes: number
            startTime: number
        }
        refreshStatus: Record<string, RefreshStatus>
        columns: number | null
        containerWidth: number | null
        dashboardMode: DashboardMode | null
        loadLayoutFromServerOnPreview: boolean
        autoRefresh: {
            enabled: boolean
            interval: number
        }
        shouldReportOnAPILoad: boolean
        showSubscriptions: boolean
        subscriptionId: number | 'new' | null
        showTextTileModal: boolean
        textTileId: number | 'new' | null
        lastDashboardRefresh: Dayjs | null
        error404: boolean
        initialVariablesLoaded: boolean
        externalFilters: DashboardFilter
        intermittentFilters: DashboardFilter
        isSavingTags: boolean
    }
    reducers: {
        dashboard: (
            state: DashboardType<QueryBasedInsightModel> | null,
            action: any,
            fullState: any
        ) => DashboardType<QueryBasedInsightModel> | null
        dashboardLoading: (state: boolean, action: any, fullState: any) => boolean
        dashboardStreaming: (state: boolean, action: any, fullState: any) => boolean
        loadingPreview: (state: boolean, action: any, fullState: any) => boolean
        cancellingPreview: (state: boolean, action: any, fullState: any) => boolean
        pageVisibility: (state: boolean, action: any, fullState: any) => boolean
        accessDeniedToDashboard: (state: boolean, action: any, fullState: any) => boolean
        dashboardFailedToLoad: (state: boolean, action: any, fullState: any) => boolean
        dashboardLayouts: (
            state: Record<DashboardTile['id'], DashboardTile['layouts']>,
            action: any,
            fullState: any
        ) => Record<DashboardTile['id'], DashboardTile['layouts']>
        temporaryBreakdownColors: (state: BreakdownColorConfig[], action: any, fullState: any) => BreakdownColorConfig[]
        dataColorThemeId: (state: number | null, action: any, fullState: any) => number | null
        loadTimer: (state: Date | null, action: any, fullState: any) => Date | null
        dashboardLoadData: (
            state: {
                action: DashboardLoadAction | undefined
                dashboardQueryId: string
                responseBytes: number
                startTime: number
            },
            action: any,
            fullState: any
        ) => {
            action: DashboardLoadAction | undefined
            dashboardQueryId: string
            responseBytes: number
            startTime: number
        }
        refreshStatus: (
            state: Record<string, RefreshStatus>,
            action: any,
            fullState: any
        ) => Record<string, RefreshStatus>
        columns: (state: number | null, action: any, fullState: any) => number | null
        containerWidth: (state: number | null, action: any, fullState: any) => number | null
        dashboardMode: (state: DashboardMode | null, action: any, fullState: any) => DashboardMode | null
        loadLayoutFromServerOnPreview: (state: boolean, action: any, fullState: any) => boolean
        autoRefresh: (
            state: {
                enabled: boolean
                interval: number
            },
            action: any,
            fullState: any
        ) => {
            enabled: boolean
            interval: number
        }
        shouldReportOnAPILoad: (state: boolean, action: any, fullState: any) => boolean
        showSubscriptions: (state: boolean, action: any, fullState: any) => boolean
        subscriptionId: (state: number | 'new' | null, action: any, fullState: any) => number | 'new' | null
        showTextTileModal: (state: boolean, action: any, fullState: any) => boolean
        textTileId: (state: number | 'new' | null, action: any, fullState: any) => number | 'new' | null
        lastDashboardRefresh: (state: Dayjs | null, action: any, fullState: any) => Dayjs | null
        error404: (state: boolean, action: any, fullState: any) => boolean
        initialVariablesLoaded: (state: boolean, action: any, fullState: any) => boolean
        externalFilters: (state: DashboardFilter, action: any, fullState: any) => DashboardFilter
        intermittentFilters: (state: DashboardFilter, action: any, fullState: any) => DashboardFilter
        isSavingTags: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        dashboard: DashboardType<QueryBasedInsightModel> | null
        dashboardLoading: boolean
        dashboardStreaming: boolean
        loadingPreview: boolean
        cancellingPreview: boolean
        pageVisibility: boolean
        accessDeniedToDashboard: boolean
        dashboardFailedToLoad: boolean
        dashboardLayouts: Record<DashboardTile['id'], DashboardTile['layouts']>
        temporaryBreakdownColors: BreakdownColorConfig[]
        dataColorThemeId: number | null
        loadTimer: Date | null
        dashboardLoadData: {
            action: DashboardLoadAction | undefined
            dashboardQueryId: string
            responseBytes: number
            startTime: number
        }
        refreshStatus: Record<string, RefreshStatus>
        columns: number | null
        containerWidth: number | null
        dashboardMode: DashboardMode | null
        loadLayoutFromServerOnPreview: boolean
        autoRefresh: {
            enabled: boolean
            interval: number
        }
        shouldReportOnAPILoad: boolean
        showSubscriptions: boolean
        subscriptionId: number | 'new' | null
        showTextTileModal: boolean
        textTileId: number | 'new' | null
        lastDashboardRefresh: Dayjs | null
        error404: boolean
        initialVariablesLoaded: boolean
        externalFilters: DashboardFilter
        intermittentFilters: DashboardFilter
        isSavingTags: boolean
    }
    selectors: {
        dashboard: (state: any, props?: any) => DashboardType<QueryBasedInsightModel> | null
        dashboardLoading: (state: any, props?: any) => boolean
        dashboardStreaming: (state: any, props?: any) => boolean
        loadingPreview: (state: any, props?: any) => boolean
        cancellingPreview: (state: any, props?: any) => boolean
        pageVisibility: (state: any, props?: any) => boolean
        accessDeniedToDashboard: (state: any, props?: any) => boolean
        dashboardFailedToLoad: (state: any, props?: any) => boolean
        dashboardLayouts: (state: any, props?: any) => Record<DashboardTile['id'], DashboardTile['layouts']>
        temporaryBreakdownColors: (state: any, props?: any) => BreakdownColorConfig[]
        dataColorThemeId: (state: any, props?: any) => number | null
        loadTimer: (state: any, props?: any) => Date | null
        dashboardLoadData: (
            state: any,
            props?: any
        ) => {
            action: DashboardLoadAction | undefined
            dashboardQueryId: string
            responseBytes: number
            startTime: number
        }
        refreshStatus: (state: any, props?: any) => Record<string, RefreshStatus>
        columns: (state: any, props?: any) => number | null
        containerWidth: (state: any, props?: any) => number | null
        dashboardMode: (state: any, props?: any) => DashboardMode | null
        loadLayoutFromServerOnPreview: (state: any, props?: any) => boolean
        autoRefresh: (
            state: any,
            props?: any
        ) => {
            enabled: boolean
            interval: number
        }
        shouldReportOnAPILoad: (state: any, props?: any) => boolean
        showSubscriptions: (state: any, props?: any) => boolean
        subscriptionId: (state: any, props?: any) => number | 'new' | null
        showTextTileModal: (state: any, props?: any) => boolean
        textTileId: (state: any, props?: any) => number | 'new' | null
        lastDashboardRefresh: (state: any, props?: any) => Dayjs | null
        error404: (state: any, props?: any) => boolean
        initialVariablesLoaded: (state: any, props?: any) => boolean
        externalFilters: (state: any, props?: any) => DashboardFilter
        intermittentFilters: (state: any, props?: any) => DashboardFilter
        isSavingTags: (state: any, props?: any) => boolean
        currentTeamId: (state: any, props?: any) => number | null
        featureFlags: (state: any, props?: any) => FeatureFlagsSet
        variables: (state: any, props?: any) => Variable[]
        getTheme: (state: any, props?: any) => (themeId: number | string | null | undefined) => DataColorTheme | null
        shouldUseStreaming: (state: any, props?: any) => boolean
        canAutoPreview: (state: any, props?: any) => boolean
        hasIntermittentFilters: (state: any, props?: any) => boolean
        hasUrlFilters: (state: any, props?: any) => boolean
        showEditBarApplyPopover: (state: any, props?: any) => boolean
        urlFilters: (state: any, props?: any) => DashboardFilter
        filtersOverrideForLoad: (state: any, props?: any) => DashboardFilter
        effectiveEditBarFilters: (state: any, props?: any) => DashboardFilter
        effectiveRefreshFilters: (state: any, props?: any) => DashboardFilter
        effectiveDashboardVariableOverrides: (
            state: any,
            props?: any
        ) => {
            [x: string]: InsightsQLVariable
        }
        effectiveVariablesAndAssociatedInsights: (
            state: any,
            props?: any
        ) => {
            insightNames: string[]
            variable: Variable
        }[]
        urlVariables: (state: any, props?: any) => Record<string, InsightsQLVariable>
        hasVariables: (state: any, props?: any) => boolean
        asDashboardTemplate: (state: any, props?: any) => DashboardTemplateEditorType | undefined
        placement: (state: any, props?: any) => DashboardPlacement
        apiUrl: (
            state: any,
            props?: any
        ) => (
            refresh?: RefreshType | undefined,
            filtersOverride?: DashboardFilter | undefined,
            variablesOverride?: Record<string, InsightsQLVariable> | undefined,
            layoutSize?: 'sm' | 'xs' | undefined
        ) => string
        currentLayoutSize: (state: any, props?: any) => 'sm' | 'xs'
        tiles: (state: any, props?: any) => DashboardTile<QueryBasedInsightModel>[]
        insightTiles: (state: any, props?: any) => DashboardTile<QueryBasedInsightModel>[]
        textTiles: (state: any, props?: any) => DashboardTile<QueryBasedInsightModel>[]
        itemsLoading: (state: any, props?: any) => boolean
        isRefreshingQueued: (state: any, props?: any) => (id: string) => boolean
        isRefreshing: (state: any, props?: any) => (id: string) => boolean
        highlightedInsightId: (state: any, props?: any) => any
        sortedDates: (state: any, props?: any) => Dayjs[]
        oldestRefreshed: (state: any, props?: any) => Dayjs | null
        effectiveLastRefresh: (state: any, props?: any) => Dayjs | null
        nextAllowedDashboardRefresh: (state: any, props?: any) => Dayjs | null
        blockRefresh: (state: any, props?: any) => boolean
        canEditDashboard: (state: any, props?: any) => boolean
        canRestrictDashboard: (state: any, props?: any) => boolean
        sizeKey: (state: any, props?: any) => DashboardLayoutSize | undefined
        layouts: (state: any, props?: any) => Partial<Record<DashboardLayoutSize, Layout[]>>
        layout: (state: any, props?: any) => Layout[] | undefined
        layoutForItem: (state: any, props?: any) => Record<string, Layout>
        refreshMetrics: (
            state: any,
            props?: any
        ) => {
            completed: number
            total: number
        }
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
        projectTreeRef: (state: any, props?: any) => ProjectTreeRef
        sidePanelContext: (state: any, props?: any) => SidePanelSceneContext | null
        dataColorTheme: (state: any, props?: any) => DataColorTheme | null
        maxContext: (state: any, props?: any) => MaxContextInput[]
    }
    sharedListeners: {
        reportRefreshTiming: (
            payload: any,
            breakpoint: BreakPointFunction,
            action: {
                type: string
                payload: any
            },
            previousState: any
        ) => void | Promise<void>
        reportLoadTiming: (
            payload: any,
            breakpoint: BreakPointFunction,
            action: {
                type: string
                payload: any
            },
            previousState: any
        ) => void | Promise<void>
        handleDashboardLoadComplete: (
            payload: any,
            breakpoint: BreakPointFunction,
            action: {
                type: string
                payload: any
            },
            previousState: any
        ) => void | Promise<void>
    }
    values: {
        dashboard: DashboardType<QueryBasedInsightModel> | null
        dashboardLoading: boolean
        dashboardStreaming: boolean
        loadingPreview: boolean
        cancellingPreview: boolean
        pageVisibility: boolean
        accessDeniedToDashboard: boolean
        dashboardFailedToLoad: boolean
        dashboardLayouts: Record<DashboardTile['id'], DashboardTile['layouts']>
        temporaryBreakdownColors: BreakdownColorConfig[]
        dataColorThemeId: number | null
        loadTimer: Date | null
        dashboardLoadData: {
            action: DashboardLoadAction | undefined
            dashboardQueryId: string
            responseBytes: number
            startTime: number
        }
        refreshStatus: Record<string, RefreshStatus>
        columns: number | null
        containerWidth: number | null
        dashboardMode: DashboardMode | null
        loadLayoutFromServerOnPreview: boolean
        autoRefresh: {
            enabled: boolean
            interval: number
        }
        shouldReportOnAPILoad: boolean
        showSubscriptions: boolean
        subscriptionId: number | 'new' | null
        showTextTileModal: boolean
        textTileId: number | 'new' | null
        lastDashboardRefresh: Dayjs | null
        error404: boolean
        initialVariablesLoaded: boolean
        externalFilters: DashboardFilter
        intermittentFilters: DashboardFilter
        isSavingTags: boolean
        currentTeamId: number | null
        featureFlags: FeatureFlagsSet
        variables: Variable[]
        getTheme: (themeId: number | string | null | undefined) => DataColorTheme | null
        shouldUseStreaming: boolean
        canAutoPreview: boolean
        hasIntermittentFilters: boolean
        hasUrlFilters: boolean
        showEditBarApplyPopover: boolean
        urlFilters: DashboardFilter
        filtersOverrideForLoad: DashboardFilter
        effectiveEditBarFilters: DashboardFilter
        effectiveRefreshFilters: DashboardFilter
        effectiveDashboardVariableOverrides: {
            [x: string]: InsightsQLVariable
        }
        effectiveVariablesAndAssociatedInsights: {
            insightNames: string[]
            variable: Variable
        }[]
        urlVariables: Record<string, InsightsQLVariable>
        hasVariables: boolean
        asDashboardTemplate: DashboardTemplateEditorType | undefined
        placement: DashboardPlacement
        apiUrl: (
            refresh?: RefreshType | undefined,
            filtersOverride?: DashboardFilter | undefined,
            variablesOverride?: Record<string, InsightsQLVariable> | undefined,
            layoutSize?: 'sm' | 'xs' | undefined
        ) => string
        currentLayoutSize: 'sm' | 'xs'
        tiles: DashboardTile<QueryBasedInsightModel>[]
        insightTiles: DashboardTile<QueryBasedInsightModel>[]
        textTiles: DashboardTile<QueryBasedInsightModel>[]
        itemsLoading: boolean
        isRefreshingQueued: (id: string) => boolean
        isRefreshing: (id: string) => boolean
        highlightedInsightId: any
        sortedDates: Dayjs[]
        oldestRefreshed: Dayjs | null
        effectiveLastRefresh: Dayjs | null
        nextAllowedDashboardRefresh: Dayjs | null
        blockRefresh: boolean
        canEditDashboard: boolean
        canRestrictDashboard: boolean
        sizeKey: DashboardLayoutSize | undefined
        layouts: Partial<Record<DashboardLayoutSize, Layout[]>>
        layout: Layout[] | undefined
        layoutForItem: Record<string, Layout>
        refreshMetrics: {
            completed: number
            total: number
        }
        breadcrumbs: Breadcrumb[]
        projectTreeRef: ProjectTreeRef
        sidePanelContext: SidePanelSceneContext | null
        dataColorTheme: DataColorTheme | null
        maxContext: MaxContextInput[]
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        shouldUseStreaming: (
            featureFlags: import('/home/z/work/hanzo/insights/frontend/src/lib/logic/featureFlagLogic').FeatureFlagsSet
        ) => boolean
        canAutoPreview: (dashboard: DashboardType<QueryBasedInsightModel> | null) => boolean
        hasIntermittentFilters: (intermittentFilters: DashboardFilter) => boolean
        hasUrlFilters: (urlFilters: DashboardFilter) => boolean
        showEditBarApplyPopover: (canAutoPreview: boolean, hasIntermittentFilters: boolean) => boolean
        urlFilters: (searchParams: Record<string, any>) => DashboardFilter
        filtersOverrideForLoad: (externalFilters: DashboardFilter, urlFilters: DashboardFilter) => DashboardFilter
        effectiveEditBarFilters: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            externalFilters: DashboardFilter,
            urlFilters: DashboardFilter,
            intermittentFilters: DashboardFilter
        ) => DashboardFilter
        effectiveRefreshFilters: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            externalFilters: DashboardFilter,
            urlFilters: DashboardFilter
        ) => DashboardFilter
        effectiveDashboardVariableOverrides: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            urlVariables: Record<string, InsightsQLVariable>
        ) => {
            [x: string]: InsightsQLVariable
        }
        effectiveVariablesAndAssociatedInsights: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            variables: Variable[],
            urlVariables: Record<string, InsightsQLVariable>
        ) => {
            insightNames: string[]
            variable: Variable
        }[]
        urlVariables: (
            searchParams: Record<string, any>,
            variables: Variable[],
            initialVariablesLoaded: boolean
        ) => Record<string, InsightsQLVariable>
        hasVariables: (
            effectiveVariablesAndAssociatedInsights: {
                insightNames: string[]
                variable: Variable
            }[]
        ) => boolean
        asDashboardTemplate: (
            dashboard: DashboardType<QueryBasedInsightModel> | null
        ) => DashboardTemplateEditorType | undefined
        placement: (arg: any) => DashboardPlacement
        apiUrl: (
            id: number
        ) => (
            refresh?: RefreshType | undefined,
            filtersOverride?: DashboardFilter | undefined,
            variablesOverride?: Record<string, InsightsQLVariable> | undefined,
            layoutSize?: 'sm' | 'xs' | undefined
        ) => string
        currentLayoutSize: (containerWidth: number | null) => 'sm' | 'xs'
        tiles: (dashboard: DashboardType<QueryBasedInsightModel> | null) => DashboardTile<QueryBasedInsightModel>[]
        insightTiles: (tiles: DashboardTile<QueryBasedInsightModel>[]) => DashboardTile<QueryBasedInsightModel>[]
        textTiles: (tiles: DashboardTile<QueryBasedInsightModel>[]) => DashboardTile<QueryBasedInsightModel>[]
        itemsLoading: (
            dashboardLoading: boolean,
            dashboardStreaming: boolean,
            refreshStatus: Record<string, RefreshStatus>,
            initialVariablesLoaded: boolean
        ) => boolean
        isRefreshingQueued: (refreshStatus: Record<string, RefreshStatus>) => (id: string) => boolean
        isRefreshing: (refreshStatus: Record<string, RefreshStatus>) => (id: string) => boolean
        highlightedInsightId: (searchParams: Record<string, any>) => any
        sortedDates: (insightTiles: DashboardTile<QueryBasedInsightModel>[]) => Dayjs[]
        oldestRefreshed: (sortedDates: Dayjs[], pageVisibility: boolean) => Dayjs | null
        effectiveLastRefresh: (lastDashboardRefresh: Dayjs | null, oldestRefreshed: Dayjs | null) => Dayjs | null
        nextAllowedDashboardRefresh: (lastDashboardRefresh: Dayjs | null) => Dayjs | null
        blockRefresh: (
            nextAllowedDashboardRefresh: Dayjs | null,
            placement: DashboardPlacement,
            pageVisibility: boolean
        ) => boolean
        canEditDashboard: (dashboard: DashboardType<QueryBasedInsightModel> | null) => boolean
        canRestrictDashboard: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            user: null | import('/home/z/work/hanzo/insights/frontend/src/types').UserType,
            currentTeam:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/types').TeamPublicType
                | import('/home/z/work/hanzo/insights/frontend/src/types').TeamType
        ) => boolean
        sizeKey: (columns: number | null) => DashboardLayoutSize | undefined
        layouts: (tiles: DashboardTile<QueryBasedInsightModel>[]) => Partial<Record<DashboardLayoutSize, Layout[]>>
        layout: (
            layouts: Partial<Record<DashboardLayoutSize, Layout[]>>,
            sizeKey: DashboardLayoutSize | undefined
        ) => Layout[] | undefined
        layoutForItem: (layout: Layout[] | undefined) => Record<string, Layout>
        refreshMetrics: (refreshStatus: Record<string, RefreshStatus>) => {
            completed: number
            total: number
        }
        breadcrumbs: (
            dashboard: DashboardType<QueryBasedInsightModel> | null,
            error404: boolean,
            dashboardFailedToLoad: boolean
        ) => Breadcrumb[]
        projectTreeRef: (arg: number) => ProjectTreeRef
        sidePanelContext: (dashboard: DashboardType<QueryBasedInsightModel> | null) => SidePanelSceneContext | null
        dataColorTheme: (
            dataColorThemeId: number | null,
            getTheme: (themeId: number | string | null | undefined) => DataColorTheme | null
        ) => DataColorTheme | null
        maxContext: (dashboard: DashboardType<QueryBasedInsightModel> | null) => MaxContextInput[]
    }
    __keaTypeGenInternalReducerActions: {
        'tile moved to dashboard (models.dashboardsModel)': (
            tile: DashboardTile<QueryBasedInsightModel>,
            dashboardId: number
        ) => {
            payload: {
                dashboardId: number
                tile: DashboardTile<QueryBasedInsightModel>
            }
            type: 'tile moved to dashboard (models.dashboardsModel)'
        }
        'update dashboard insight (models.dashboardsModel)': (
            insight: QueryBasedInsightModel,
            extraDashboardIds?: number[]
        ) => {
            payload: {
                extraDashboardIds: number[] | undefined
                insight: QueryBasedInsightModel
            }
            type: 'update dashboard insight (models.dashboardsModel)'
        }
        'update dashboard success (models.dashboardsModel)': (
            dashboard: DashboardType<QueryBasedInsightModel> | null | undefined,
            payload?: any
        ) => {
            payload: {
                dashboard: DashboardType<QueryBasedInsightModel> | null | undefined
                payload?: any
            }
            type: 'update dashboard success (models.dashboardsModel)'
        }
        'rename insight success (models.insightsModel)': (item: QueryBasedInsightModel) => {
            payload: {
                item: QueryBasedInsightModel
            }
            type: 'rename insight success (models.insightsModel)'
        }
        'update dashboard failure (models.dashboardsModel)': (
            error: string,
            errorObject?: any
        ) => {
            payload: {
                error: string
                errorObject?: any
            }
            type: 'update dashboard failure (models.dashboardsModel)'
        }
        'duplicate insight success (models.insightsModel)': (item: QueryBasedInsightModel) => {
            payload: {
                item: QueryBasedInsightModel
            }
            type: 'duplicate insight success (models.insightsModel)'
        }
        'tile added to dashboard (models.dashboardsModel)': (dashboardId: number) => {
            payload: {
                dashboardId: number
            }
            type: 'tile added to dashboard (models.dashboardsModel)'
        }
        'get variables success (queries.nodes.DataVisualization.Components.Variables.variableDataLogic)': (
            variables: Variable[],
            payload?: any
        ) => {
            payload: {
                payload?: any
                variables: Variable[]
            }
            type: 'get variables success (queries.nodes.DataVisualization.Components.Variables.variableDataLogic)'
        }
    }
}
