// Generated by kea-typegen on Sun, 02 Aug 2026 21:35:23 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { PromptFormValues, PromptLogicProps, PromptMode } from './llmPromptLogic'
import type { ProductIntentProperties } from '../../../../frontend/src/lib/utils/product-intents'
import type { AnyPropertyFilter, Breadcrumb, LLMPrompt } from '../../../../frontend/src/types'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import type { DataTableNode, InsightVizNode } from '../../../../frontend/src/queries/schema/schema-general'

export interface llmPromptLogicType extends Logic {
    actionCreators: {
        addProductIntent: (properties: ProductIntentProperties) => {
            type: 'add product intent (scenes.llm-analytics.llmPromptLogic)'
            payload: ProductIntentProperties
        }
        setPrompt: (prompt: LLMPrompt | PromptFormValues) => {
            type: 'set prompt (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                prompt: LLMPrompt | PromptFormValues
            }
        }
        deletePrompt: () => {
            type: 'delete prompt (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                value: true
            }
        }
        setMode: (mode: PromptMode) => {
            type: 'set mode (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                mode: PromptMode
            }
        }
        loadPrompt: () => {
            type: 'load prompt (scenes.llm-analytics.llmPromptLogic)'
            payload: any
        }
        loadPromptSuccess: (
            prompt: LLMPrompt,
            payload?: any
        ) => {
            type: 'load prompt success (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                prompt: LLMPrompt
                payload?: any
            }
        }
        loadPromptFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load prompt failure (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        setPromptFormValue: (
            key: FieldName,
            value: any
        ) => {
            type: 'set prompt form value (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                name: FieldName
                value: any
            }
        }
        setPromptFormValues: (values: DeepPartial<PromptFormValues>) => {
            type: 'set prompt form values (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                values: DeepPartial<PromptFormValues>
            }
        }
        setPromptFormManualErrors: (errors: Record<string, any>) => {
            type: 'set prompt form manual errors (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                errors: Record<string, any>
            }
        }
        touchPromptFormField: (key: string) => {
            type: 'touch prompt form field (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                key: string
            }
        }
        resetPromptForm: (values?: PromptFormValues) => {
            type: 'reset prompt form (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                values?: PromptFormValues
            }
        }
        submitPromptForm: () => {
            type: 'submit prompt form (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                value: boolean
            }
        }
        submitPromptFormRequest: (promptForm: PromptFormValues) => {
            type: 'submit prompt form request (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                promptForm: PromptFormValues
            }
        }
        submitPromptFormSuccess: (promptForm: PromptFormValues) => {
            type: 'submit prompt form success (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                promptForm: PromptFormValues
            }
        }
        submitPromptFormFailure: (
            error: Error,
            errors: Record<string, any>
        ) => {
            type: 'submit prompt form failure (scenes.llm-analytics.llmPromptLogic)'
            payload: {
                error: Error
                errors: Record<string, any>
            }
        }
    }
    actionKeys: {
        'add product intent (scenes.llm-analytics.llmPromptLogic)': 'addProductIntent'
        'set prompt (scenes.llm-analytics.llmPromptLogic)': 'setPrompt'
        'delete prompt (scenes.llm-analytics.llmPromptLogic)': 'deletePrompt'
        'set mode (scenes.llm-analytics.llmPromptLogic)': 'setMode'
        'load prompt (scenes.llm-analytics.llmPromptLogic)': 'loadPrompt'
        'load prompt success (scenes.llm-analytics.llmPromptLogic)': 'loadPromptSuccess'
        'load prompt failure (scenes.llm-analytics.llmPromptLogic)': 'loadPromptFailure'
        'set prompt form value (scenes.llm-analytics.llmPromptLogic)': 'setPromptFormValue'
        'set prompt form values (scenes.llm-analytics.llmPromptLogic)': 'setPromptFormValues'
        'set prompt form manual errors (scenes.llm-analytics.llmPromptLogic)': 'setPromptFormManualErrors'
        'touch prompt form field (scenes.llm-analytics.llmPromptLogic)': 'touchPromptFormField'
        'reset prompt form (scenes.llm-analytics.llmPromptLogic)': 'resetPromptForm'
        'submit prompt form (scenes.llm-analytics.llmPromptLogic)': 'submitPromptForm'
        'submit prompt form request (scenes.llm-analytics.llmPromptLogic)': 'submitPromptFormRequest'
        'submit prompt form success (scenes.llm-analytics.llmPromptLogic)': 'submitPromptFormSuccess'
        'submit prompt form failure (scenes.llm-analytics.llmPromptLogic)': 'submitPromptFormFailure'
    }
    actionTypes: {
        addProductIntent: 'add product intent (scenes.llm-analytics.llmPromptLogic)'
        setPrompt: 'set prompt (scenes.llm-analytics.llmPromptLogic)'
        deletePrompt: 'delete prompt (scenes.llm-analytics.llmPromptLogic)'
        setMode: 'set mode (scenes.llm-analytics.llmPromptLogic)'
        loadPrompt: 'load prompt (scenes.llm-analytics.llmPromptLogic)'
        loadPromptSuccess: 'load prompt success (scenes.llm-analytics.llmPromptLogic)'
        loadPromptFailure: 'load prompt failure (scenes.llm-analytics.llmPromptLogic)'
        setPromptFormValue: 'set prompt form value (scenes.llm-analytics.llmPromptLogic)'
        setPromptFormValues: 'set prompt form values (scenes.llm-analytics.llmPromptLogic)'
        setPromptFormManualErrors: 'set prompt form manual errors (scenes.llm-analytics.llmPromptLogic)'
        touchPromptFormField: 'touch prompt form field (scenes.llm-analytics.llmPromptLogic)'
        resetPromptForm: 'reset prompt form (scenes.llm-analytics.llmPromptLogic)'
        submitPromptForm: 'submit prompt form (scenes.llm-analytics.llmPromptLogic)'
        submitPromptFormRequest: 'submit prompt form request (scenes.llm-analytics.llmPromptLogic)'
        submitPromptFormSuccess: 'submit prompt form success (scenes.llm-analytics.llmPromptLogic)'
        submitPromptFormFailure: 'submit prompt form failure (scenes.llm-analytics.llmPromptLogic)'
    }
    actions: {
        addProductIntent: (properties: ProductIntentProperties) => void
        setPrompt: (prompt: LLMPrompt | PromptFormValues) => void
        deletePrompt: () => void
        setMode: (mode: PromptMode) => void
        loadPrompt: () => void
        loadPromptSuccess: (prompt: LLMPrompt, payload?: any) => void
        loadPromptFailure: (error: string, errorObject?: any) => void
        setPromptFormValue: (key: FieldName, value: any) => void
        setPromptFormValues: (values: DeepPartial<PromptFormValues>) => void
        setPromptFormManualErrors: (errors: Record<string, any>) => void
        touchPromptFormField: (key: string) => void
        resetPromptForm: (values?: PromptFormValues) => void
        submitPromptForm: () => void
        submitPromptFormRequest: (promptForm: PromptFormValues) => void
        submitPromptFormSuccess: (promptForm: PromptFormValues) => void
        submitPromptFormFailure: (error: Error, errors: Record<string, any>) => void
    }
    asyncActions: {
        addProductIntent: (properties: ProductIntentProperties) => Promise<any>
        setPrompt: (prompt: LLMPrompt | PromptFormValues) => Promise<any>
        deletePrompt: () => Promise<any>
        setMode: (mode: PromptMode) => Promise<any>
        loadPrompt: () => Promise<any>
        loadPromptSuccess: (prompt: LLMPrompt, payload?: any) => Promise<any>
        loadPromptFailure: (error: string, errorObject?: any) => Promise<any>
        setPromptFormValue: (key: FieldName, value: any) => Promise<any>
        setPromptFormValues: (values: DeepPartial<PromptFormValues>) => Promise<any>
        setPromptFormManualErrors: (errors: Record<string, any>) => Promise<any>
        touchPromptFormField: (key: string) => Promise<any>
        resetPromptForm: (values?: PromptFormValues) => Promise<any>
        submitPromptForm: () => Promise<any>
        submitPromptFormRequest: (promptForm: PromptFormValues) => Promise<any>
        submitPromptFormSuccess: (promptForm: PromptFormValues) => Promise<any>
        submitPromptFormFailure: (error: Error, errors: Record<string, any>) => Promise<any>
    }
    defaults: {
        prompt: LLMPrompt | PromptFormValues | null
        mode: PromptMode
        promptLoading: boolean
        promptForm: PromptFormValues
        isPromptFormSubmitting: boolean
        showPromptFormErrors: boolean
        promptFormChanged: boolean
        promptFormTouches: Record<string, boolean>
        promptFormManualErrors: Record<string, any>
    }
    events: {}
    key: string
    listeners: {
        deletePrompt: ((
            action: {
                type: 'delete prompt (scenes.llm-analytics.llmPromptLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadPromptSuccess: ((
            action: {
                type: 'load prompt success (scenes.llm-analytics.llmPromptLogic)'
                payload: {
                    prompt: LLMPrompt
                    payload?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'llm-analytics', 'llmPromptLogic']
    pathString: 'scenes.llm-analytics.llmPromptLogic'
    props: PromptLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        prompt: LLMPrompt | PromptFormValues | null
        mode: PromptMode
        promptLoading: boolean
        promptForm: PromptFormValues
        isPromptFormSubmitting: boolean
        showPromptFormErrors: boolean
        promptFormChanged: boolean
        promptFormTouches: Record<string, boolean>
        promptFormManualErrors: Record<string, any>
    }
    reducers: {
        prompt: (
            state: LLMPrompt | PromptFormValues | null,
            action: any,
            fullState: any
        ) => LLMPrompt | PromptFormValues | null
        mode: (state: PromptMode, action: any, fullState: any) => PromptMode
        promptLoading: (state: boolean, action: any, fullState: any) => boolean
        promptForm: (state: PromptFormValues, action: any, fullState: any) => PromptFormValues
        isPromptFormSubmitting: (state: boolean, action: any, fullState: any) => boolean
        showPromptFormErrors: (state: boolean, action: any, fullState: any) => boolean
        promptFormChanged: (state: boolean, action: any, fullState: any) => boolean
        promptFormTouches: (state: Record<string, boolean>, action: any, fullState: any) => Record<string, boolean>
        promptFormManualErrors: (state: Record<string, any>, action: any, fullState: any) => Record<string, any>
    }
    selector: (state: any) => {
        prompt: LLMPrompt | PromptFormValues | null
        mode: PromptMode
        promptLoading: boolean
        promptForm: PromptFormValues
        isPromptFormSubmitting: boolean
        showPromptFormErrors: boolean
        promptFormChanged: boolean
        promptFormTouches: Record<string, boolean>
        promptFormManualErrors: Record<string, any>
    }
    selectors: {
        prompt: (state: any, props?: any) => LLMPrompt | PromptFormValues | null
        mode: (state: any, props?: any) => PromptMode
        promptLoading: (state: any, props?: any) => boolean
        promptForm: (state: any, props?: any) => PromptFormValues
        isPromptFormSubmitting: (state: any, props?: any) => boolean
        showPromptFormErrors: (state: any, props?: any) => boolean
        promptFormChanged: (state: any, props?: any) => boolean
        promptFormTouches: (state: any, props?: any) => Record<string, boolean>
        promptFormManualErrors: (state: any, props?: any) => Record<string, any>
        promptFormTouched: (state: any, props?: any) => boolean
        promptFormValidationErrors: (state: any, props?: any) => DeepPartialMap<PromptFormValues, ValidationErrorType>
        promptFormAllErrors: (state: any, props?: any) => Record<string, any>
        promptFormHasErrors: (state: any, props?: any) => boolean
        promptFormErrors: (state: any, props?: any) => DeepPartialMap<PromptFormValues, ValidationErrorType>
        isPromptFormValid: (state: any, props?: any) => boolean
        isNewPrompt: (state: any, props?: any) => boolean
        isPromptMissing: (state: any, props?: any) => boolean
        shouldDisplaySkeleton: (state: any, props?: any) => boolean
        promptVariables: (state: any, props?: any) => string[]
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
        isViewMode: (state: any, props?: any) => boolean
        isEditMode: (state: any, props?: any) => boolean
        relatedTracesQuery: (state: any, props?: any) => DataTableNode | null
        viewAllTracesUrl: (state: any, props?: any) => string
        promptUsagePropertyFilter: (state: any, props?: any) => AnyPropertyFilter[]
        promptUsageTrendQuery: (state: any, props?: any) => InsightVizNode
        promptUsageLogQuery: (state: any, props?: any) => DataTableNode
    }
    sharedListeners: {}
    values: {
        prompt: LLMPrompt | PromptFormValues | null
        mode: PromptMode
        promptLoading: boolean
        promptForm: PromptFormValues
        isPromptFormSubmitting: boolean
        showPromptFormErrors: boolean
        promptFormChanged: boolean
        promptFormTouches: Record<string, boolean>
        promptFormManualErrors: Record<string, any>
        promptFormTouched: boolean
        promptFormValidationErrors: DeepPartialMap<PromptFormValues, ValidationErrorType>
        promptFormAllErrors: Record<string, any>
        promptFormHasErrors: boolean
        promptFormErrors: DeepPartialMap<PromptFormValues, ValidationErrorType>
        isPromptFormValid: boolean
        isNewPrompt: boolean
        isPromptMissing: boolean
        shouldDisplaySkeleton: boolean
        promptVariables: string[]
        breadcrumbs: Breadcrumb[]
        isViewMode: boolean
        isEditMode: boolean
        relatedTracesQuery: DataTableNode | null
        viewAllTracesUrl: string
        promptUsagePropertyFilter: AnyPropertyFilter[]
        promptUsageTrendQuery: InsightVizNode
        promptUsageLogQuery: DataTableNode
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        isNewPrompt: (arg: any) => boolean
        isPromptMissing: (prompt: LLMPrompt | PromptFormValues | null, promptLoading: boolean) => boolean
        shouldDisplaySkeleton: (prompt: LLMPrompt | PromptFormValues | null, promptLoading: boolean) => boolean
        promptVariables: (promptForm: PromptFormValues) => string[]
        breadcrumbs: (prompt: LLMPrompt | PromptFormValues | null, searchParams: Record<string, any>) => Breadcrumb[]
        isViewMode: (mode: PromptMode, arg: any) => boolean
        isEditMode: (mode: PromptMode, arg: any) => boolean
        relatedTracesQuery: (prompt: LLMPrompt | PromptFormValues | null) => DataTableNode | null
        viewAllTracesUrl: (prompt: LLMPrompt | PromptFormValues | null) => string
        promptUsagePropertyFilter: (prompt: LLMPrompt | PromptFormValues | null) => AnyPropertyFilter[]
        promptUsageTrendQuery: (promptUsagePropertyFilter: AnyPropertyFilter[]) => InsightVizNode
        promptUsageLogQuery: (promptUsagePropertyFilter: AnyPropertyFilter[]) => DataTableNode
    }
}
