"""Temporal activities for the Insights Slack App.

Activities living here run on ``settings.TASKS_TASK_QUEUE`` and are imported by
``insights_code_slack_mention.py`` and ``insights_code_slack_mention_command.py``
in this package at module load time.
"""

from insights.temporal.ai.slack_app.activities import (
    CLASSIFIER_THREAD_HISTORY_MESSAGES,
    POSTFN_CODE_SLACK_MENTION_PICKER_GUIDANCE,
    POSTFN_CODE_SLACK_RULES_ADD_PICKER_GUIDANCE,
    block_insights_code_task_if_no_personal_github_activity,
    cascade_insights_code_repository_activity,
    classify_message_is_agent_directed,
    classify_insights_code_task_needs_repo_activity,
    classify_untagged_followup_activity,
    collect_insights_code_thread_messages_activity,
    create_insights_code_routing_rule_activity,
    create_insights_code_task_for_repo_activity,
    derive_mention_workflow_id,
    discover_insights_code_repository_via_agent_activity,
    enforce_insights_code_billing_quota_activity,
    forward_insights_code_followup_activity,
    handle_insights_code_rules_command_activity,
    handle_insights_code_slack_mention_command_activity,
    mark_slack_app_message_processing_activity,
    mark_slack_app_message_queued_activity,
    post_insights_code_authorship_timeout_activity,
    post_insights_code_internal_error_activity,
    post_insights_code_no_repos_activity,
    post_insights_code_picker_timeout_activity,
    post_insights_code_repo_picker_activity,
    resolve_insights_code_authorship_activity,
    resolve_insights_code_slack_command_user_activity,
    resolve_insights_code_slack_user_activity,
    run_insights_slack_inbox_onboarding_activity,
)
from insights.temporal.ai.slack_app.types import (
    SLACK_APP_PROCESSING_REACTION,
    SLACK_APP_QUEUED_REACTION,
    InsightsCodeRepoCascadeOutcome,
    InsightsCodeRulesCommandResult,
    InsightsCodeSlackMentionCommandResult,
    InsightsCodeSlackMentionCommandWorkflowInputs,
    InsightsCodeSlackMentionWorkflowInputs,
    InsightsSlackInboxOnboardingInputs,
    SlackAppMentionWorkflowInputs,
    SlackAppMessageReactionInput,
    SlackRepoSelectionOutcome,
)

SLACK_APP_ACTIVITIES = [
    classify_untagged_followup_activity,
    resolve_insights_code_slack_user_activity,
    resolve_insights_code_slack_command_user_activity,
    collect_insights_code_thread_messages_activity,
    cascade_insights_code_repository_activity,
    discover_insights_code_repository_via_agent_activity,
    classify_insights_code_task_needs_repo_activity,
    enforce_insights_code_billing_quota_activity,
    post_insights_code_no_repos_activity,
    post_insights_code_repo_picker_activity,
    block_insights_code_task_if_no_personal_github_activity,
    resolve_insights_code_authorship_activity,
    post_insights_code_picker_timeout_activity,
    post_insights_code_authorship_timeout_activity,
    post_insights_code_internal_error_activity,
    create_insights_code_task_for_repo_activity,
    forward_insights_code_followup_activity,
    handle_insights_code_rules_command_activity,
    create_insights_code_routing_rule_activity,
    handle_insights_code_slack_mention_command_activity,
    mark_slack_app_message_processing_activity,
    mark_slack_app_message_queued_activity,
    run_insights_slack_inbox_onboarding_activity,
]

__all__ = [
    "CLASSIFIER_THREAD_HISTORY_MESSAGES",
    "SlackAppMessageReactionInput",
    "POSTFN_CODE_SLACK_MENTION_PICKER_GUIDANCE",
    "POSTFN_CODE_SLACK_RULES_ADD_PICKER_GUIDANCE",
    "SLACK_APP_PROCESSING_REACTION",
    "SLACK_APP_QUEUED_REACTION",
    "InsightsCodeRepoCascadeOutcome",
    "InsightsCodeRulesCommandResult",
    "InsightsCodeSlackMentionCommandResult",
    "InsightsCodeSlackMentionCommandWorkflowInputs",
    "InsightsCodeSlackMentionWorkflowInputs",
    "InsightsSlackInboxOnboardingInputs",
    "SLACK_APP_ACTIVITIES",
    "SlackAppMentionWorkflowInputs",
    "SlackRepoSelectionOutcome",
    "block_insights_code_task_if_no_personal_github_activity",
    "cascade_insights_code_repository_activity",
    "classify_message_is_agent_directed",
    "classify_insights_code_task_needs_repo_activity",
    "classify_untagged_followup_activity",
    "collect_insights_code_thread_messages_activity",
    "create_insights_code_routing_rule_activity",
    "create_insights_code_task_for_repo_activity",
    "derive_mention_workflow_id",
    "discover_insights_code_repository_via_agent_activity",
    "enforce_insights_code_billing_quota_activity",
    "forward_insights_code_followup_activity",
    "handle_insights_code_rules_command_activity",
    "handle_insights_code_slack_mention_command_activity",
    "mark_slack_app_message_processing_activity",
    "mark_slack_app_message_queued_activity",
    "post_insights_code_authorship_timeout_activity",
    "post_insights_code_internal_error_activity",
    "post_insights_code_no_repos_activity",
    "post_insights_code_picker_timeout_activity",
    "post_insights_code_repo_picker_activity",
    "resolve_insights_code_authorship_activity",
    "resolve_insights_code_slack_command_user_activity",
    "resolve_insights_code_slack_user_activity",
    "run_insights_slack_inbox_onboarding_activity",
]
