// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:53 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface commandLogicType extends Logic {
    actionCreators: {
        openCommand: () => {
            type: 'open command (lib.components.Command.commandLogic)'
            payload: {
                value: true
            }
        }
        closeCommand: () => {
            type: 'close command (lib.components.Command.commandLogic)'
            payload: {
                value: true
            }
        }
        toggleCommand: () => {
            type: 'toggle command (lib.components.Command.commandLogic)'
            payload: {
                value: true
            }
        }
    }
    actionKeys: {
        'open command (lib.components.Command.commandLogic)': 'openCommand'
        'close command (lib.components.Command.commandLogic)': 'closeCommand'
        'toggle command (lib.components.Command.commandLogic)': 'toggleCommand'
    }
    actionTypes: {
        openCommand: 'open command (lib.components.Command.commandLogic)'
        closeCommand: 'close command (lib.components.Command.commandLogic)'
        toggleCommand: 'toggle command (lib.components.Command.commandLogic)'
    }
    actions: {
        openCommand: () => void
        closeCommand: () => void
        toggleCommand: () => void
    }
    asyncActions: {
        openCommand: () => Promise<any>
        closeCommand: () => Promise<any>
        toggleCommand: () => Promise<any>
    }
    defaults: {
        isCommandOpen: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['lib', 'components', 'Command', 'commandLogic']
    pathString: 'lib.components.Command.commandLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        isCommandOpen: boolean
    }
    reducers: {
        isCommandOpen: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        isCommandOpen: boolean
    }
    selectors: {
        isCommandOpen: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        isCommandOpen: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}
