// Generated by kea-typegen on Sun, 02 Aug 2026 21:36:21 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface tagSelectLogicType extends Logic {
    actionCreators: {
        setSearch: (search: string) => {
            type: 'set search (lib.components.tagSelectLogic)'
            payload: {
                search: string
            }
        }
        setShowPopover: (visible: boolean) => {
            type: 'set show popover (lib.components.tagSelectLogic)'
            payload: {
                visible: boolean
            }
        }
    }
    actionKeys: {
        'set search (lib.components.tagSelectLogic)': 'setSearch'
        'set show popover (lib.components.tagSelectLogic)': 'setShowPopover'
    }
    actionTypes: {
        setSearch: 'set search (lib.components.tagSelectLogic)'
        setShowPopover: 'set show popover (lib.components.tagSelectLogic)'
    }
    actions: {
        setSearch: (search: string) => void
        setShowPopover: (visible: boolean) => void
    }
    asyncActions: {
        setSearch: (search: string) => Promise<any>
        setShowPopover: (visible: boolean) => Promise<any>
    }
    defaults: {
        search: string
        showPopover: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['lib', 'components', 'tagSelectLogic']
    pathString: 'lib.components.tagSelectLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        search: string
        showPopover: boolean
    }
    reducers: {
        search: (state: string, action: any, fullState: any) => string
        showPopover: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        search: string
        showPopover: boolean
    }
    selectors: {
        search: (state: any, props?: any) => string
        showPopover: (state: any, props?: any) => boolean
        tags: (state: any, props?: any) => string[]
        filteredTags: (state: any, props?: any) => string[]
    }
    sharedListeners: {}
    values: {
        search: string
        showPopover: boolean
        tags: string[]
        filteredTags: string[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        filteredTags: (tags: string[], search: string) => string[]
    }
}
