# Generated by Django 5.2.14 on 2026-07-03 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import insights.models.utils
from insights.migration_helpers import AddForeignKeyNotValid


class Migration(migrations.Migration):
    dependencies = [
        ("customer_analytics", "0021_custompropertysource_column_descriptions"),
        ("insights", "1247_oauthaccesstoken_token_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStream",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=insights.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("event_names", models.JSONField(default=list)),
                ("slack_channel_id", models.CharField(blank=True, default="", max_length=200)),
                ("slack_channel_name", models.CharField(blank=True, default="", max_length=200)),
                ("insights_function_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slack_integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="insights.integration",
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_analytics_event_stream",
                        to="insights.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventStreamMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=insights.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_stream_memberships",
                        to="customer_analytics.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="customer_analytics.eventstream",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="insights.team"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("stream", "account"), name="unique_event_stream_member")
                ],
            },
        ),
        AddForeignKeyNotValid(
            model_name="eventstream",
            name="eventstream_team_id_fk",
            column="team_id",
            to_table="insights_team",
            to_column="id",
        ),
        AddForeignKeyNotValid(
            model_name="eventstream",
            name="eventstream_created_by_id_fk",
            column="created_by_id",
            to_table="insights_user",
            to_column="id",
        ),
        AddForeignKeyNotValid(
            model_name="eventstreammember",
            name="eventstreammember_team_id_fk",
            column="team_id",
            to_table="insights_team",
            to_column="id",
        ),
        AddForeignKeyNotValid(
            model_name="eventstreammember",
            name="eventstreammember_created_by_id_fk",
            column="created_by_id",
            to_table="insights_user",
            to_column="id",
        ),
    ]
