# Generated by Django 4.2.29 on 2026-07-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics_platform', '0001_initial'),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaggregationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preaggregationjob',
            name='team',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='insights.team'),
        ),
        migrations.AddIndex(
            model_name='preaggregationjob',
            index=models.Index(fields=['team_id', 'query_hash'], name='analytics_p_team_id_f37a89_idx'),
        ),
        migrations.AddIndex(
            model_name='preaggregationjob',
            index=models.Index(fields=['team_id', 'status'], name='analytics_p_team_id_b17148_idx'),
        ),
        migrations.AddIndex(
            model_name='preaggregationjob',
            index=models.Index(fields=['team_id', 'time_range_start', 'time_range_end'], name='analytics_p_team_id_4e65a5_idx'),
        ),
        migrations.AddIndex(
            model_name='preaggregationjob',
            index=models.Index(fields=['team_id', 'expires_at'], name='analytics_p_team_id_3b8e02_idx'),
        ),
        migrations.AddConstraint(
            model_name='preaggregationjob',
            constraint=models.CheckConstraint(check=models.Q(('time_range_start__lt', models.F('time_range_end'))), name='time_range_start_before_end'),
        ),
    ]
