// Generated by kea-typegen on Sun, 02 Aug 2026 21:35:24 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DefinitionLogicProps, SetDefinitionProps } from './definitionLogic'
import type { Breadcrumb, Definition, EventDefinitionMetrics, ObjectMediaPreview, PropertyDefinitionType, PropertyType, SchemaEnforcementMode, UserBasicType } from '../../../types'

export interface definitionLogicType extends Logic {
    actionCreators: {
        setDefinition: (
            definition: Partial<Definition>,
            options?: SetDefinitionProps
        ) => {
            type: 'set definition (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                definition: Partial<Definition>
                options: SetDefinitionProps
            }
        }
        loadDefinition: (id: Definition['id']) => {
            type: 'load definition (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                id: string
            }
        }
        loadMetrics: (id: Definition['id']) => {
            type: 'load metrics (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                id: string
            }
        }
        setDefinitionMissing: () => {
            type: 'set definition missing (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                value: true
            }
        }
        loadPreviews: () => {
            type: 'load previews (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                value: true
            }
        }
        createMediaPreview: (
            uploadedMediaId: string,
            metadata?: Record<string, any>
        ) => {
            type: 'create media preview (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                metadata: Record<string, any> | undefined
                uploadedMediaId: string
            }
        }
        deleteMediaPreview: (previewId: string) => {
            type: 'delete media preview (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                previewId: string
            }
        }
        setDefinitionSuccess: (
            definition: Definition,
            payload?: {
                definition: Partial<Definition>
                options: SetDefinitionProps
            }
        ) => {
            type: 'set definition success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                definition: Definition
                payload?: {
                    definition: Partial<Definition>
                    options: SetDefinitionProps
                }
            }
        }
        setDefinitionFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'set definition failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadDefinitionSuccess: (
            definition:
                | {
                      created_at?: string | undefined
                      default_columns?: string[] | undefined
                      description?: string | undefined
                      enforcement_mode?: SchemaEnforcementMode | undefined
                      hidden?: boolean | undefined
                      id: string
                      is_action?: boolean | undefined
                      last_seen_at?: string | undefined
                      last_updated_at?: string | undefined
                      media_preview_urls?: string[] | undefined
                      name: string
                      owner?: UserBasicType | null | undefined
                      tags?: string[] | undefined
                      updated_at?: string | undefined
                      updated_by?: UserBasicType | null | undefined
                      verified?: boolean | undefined
                      verified_at?: string | undefined
                      verified_by?: string | undefined
                  }
                | {
                      created_at?: string | undefined
                      description?: string | undefined
                      example?: string | undefined
                      hidden?: boolean | undefined
                      id: string
                      is_action?: boolean | undefined
                      is_numerical?: boolean | undefined
                      is_seen_on_filtered_events?: boolean | undefined
                      last_seen_at?: string | undefined
                      name: string
                      property_type?: PropertyType | undefined
                      tags?: string[] | undefined
                      type?: PropertyDefinitionType | undefined
                      updated_at?: string | undefined
                      updated_by?: UserBasicType | null | undefined
                      verified?: boolean | undefined
                      verified_at?: string | undefined
                      verified_by?: string | undefined
                      virtual?: boolean | undefined
                  },
            payload?: {
                id: string
            }
        ) => {
            type: 'load definition success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                definition:
                    | {
                          created_at?: string | undefined
                          default_columns?: string[] | undefined
                          description?: string | undefined
                          enforcement_mode?: SchemaEnforcementMode | undefined
                          hidden?: boolean | undefined
                          id: string
                          is_action?: boolean | undefined
                          last_seen_at?: string | undefined
                          last_updated_at?: string | undefined
                          media_preview_urls?: string[] | undefined
                          name: string
                          owner?: UserBasicType | null | undefined
                          tags?: string[] | undefined
                          updated_at?: string | undefined
                          updated_by?: UserBasicType | null | undefined
                          verified?: boolean | undefined
                          verified_at?: string | undefined
                          verified_by?: string | undefined
                      }
                    | {
                          created_at?: string | undefined
                          description?: string | undefined
                          example?: string | undefined
                          hidden?: boolean | undefined
                          id: string
                          is_action?: boolean | undefined
                          is_numerical?: boolean | undefined
                          is_seen_on_filtered_events?: boolean | undefined
                          last_seen_at?: string | undefined
                          name: string
                          property_type?: PropertyType | undefined
                          tags?: string[] | undefined
                          type?: PropertyDefinitionType | undefined
                          updated_at?: string | undefined
                          updated_by?: UserBasicType | null | undefined
                          verified?: boolean | undefined
                          verified_at?: string | undefined
                          verified_by?: string | undefined
                          virtual?: boolean | undefined
                      }
                payload?: {
                    id: string
                }
            }
        }
        loadDefinitionFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load definition failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        deleteDefinition: () => {
            type: 'delete definition (scenes.data-management.definition.definitionViewLogic)'
            payload: any
        }
        deleteDefinitionSuccess: (
            definition: Definition,
            payload?: any
        ) => {
            type: 'delete definition success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                definition: Definition
                payload?: any
            }
        }
        deleteDefinitionFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'delete definition failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadMetricsSuccess: (
            metrics: EventDefinitionMetrics | null,
            payload?: {
                id: string
            }
        ) => {
            type: 'load metrics success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                metrics: EventDefinitionMetrics | null
                payload?: {
                    id: string
                }
            }
        }
        loadMetricsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load metrics failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadPreviewsSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                value: true
            }
        ) => {
            type: 'load previews success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                previews: ObjectMediaPreview[]
                payload?: {
                    value: true
                }
            }
        }
        loadPreviewsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load previews failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        createMediaPreviewSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                metadata: Record<string, any> | undefined
                uploadedMediaId: string
            }
        ) => {
            type: 'create media preview success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                previews: ObjectMediaPreview[]
                payload?: {
                    metadata: Record<string, any> | undefined
                    uploadedMediaId: string
                }
            }
        }
        createMediaPreviewFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'create media preview failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        deleteMediaPreviewSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                previewId: string
            }
        ) => {
            type: 'delete media preview success (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                previews: ObjectMediaPreview[]
                payload?: {
                    previewId: string
                }
            }
        }
        deleteMediaPreviewFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'delete media preview failure (scenes.data-management.definition.definitionViewLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'set definition (scenes.data-management.definition.definitionViewLogic)': 'setDefinition'
        'load definition (scenes.data-management.definition.definitionViewLogic)': 'loadDefinition'
        'load metrics (scenes.data-management.definition.definitionViewLogic)': 'loadMetrics'
        'set definition missing (scenes.data-management.definition.definitionViewLogic)': 'setDefinitionMissing'
        'load previews (scenes.data-management.definition.definitionViewLogic)': 'loadPreviews'
        'create media preview (scenes.data-management.definition.definitionViewLogic)': 'createMediaPreview'
        'delete media preview (scenes.data-management.definition.definitionViewLogic)': 'deleteMediaPreview'
        'set definition success (scenes.data-management.definition.definitionViewLogic)': 'setDefinitionSuccess'
        'set definition failure (scenes.data-management.definition.definitionViewLogic)': 'setDefinitionFailure'
        'load definition success (scenes.data-management.definition.definitionViewLogic)': 'loadDefinitionSuccess'
        'load definition failure (scenes.data-management.definition.definitionViewLogic)': 'loadDefinitionFailure'
        'delete definition (scenes.data-management.definition.definitionViewLogic)': 'deleteDefinition'
        'delete definition success (scenes.data-management.definition.definitionViewLogic)': 'deleteDefinitionSuccess'
        'delete definition failure (scenes.data-management.definition.definitionViewLogic)': 'deleteDefinitionFailure'
        'load metrics success (scenes.data-management.definition.definitionViewLogic)': 'loadMetricsSuccess'
        'load metrics failure (scenes.data-management.definition.definitionViewLogic)': 'loadMetricsFailure'
        'load previews success (scenes.data-management.definition.definitionViewLogic)': 'loadPreviewsSuccess'
        'load previews failure (scenes.data-management.definition.definitionViewLogic)': 'loadPreviewsFailure'
        'create media preview success (scenes.data-management.definition.definitionViewLogic)': 'createMediaPreviewSuccess'
        'create media preview failure (scenes.data-management.definition.definitionViewLogic)': 'createMediaPreviewFailure'
        'delete media preview success (scenes.data-management.definition.definitionViewLogic)': 'deleteMediaPreviewSuccess'
        'delete media preview failure (scenes.data-management.definition.definitionViewLogic)': 'deleteMediaPreviewFailure'
    }
    actionTypes: {
        setDefinition: 'set definition (scenes.data-management.definition.definitionViewLogic)'
        loadDefinition: 'load definition (scenes.data-management.definition.definitionViewLogic)'
        loadMetrics: 'load metrics (scenes.data-management.definition.definitionViewLogic)'
        setDefinitionMissing: 'set definition missing (scenes.data-management.definition.definitionViewLogic)'
        loadPreviews: 'load previews (scenes.data-management.definition.definitionViewLogic)'
        createMediaPreview: 'create media preview (scenes.data-management.definition.definitionViewLogic)'
        deleteMediaPreview: 'delete media preview (scenes.data-management.definition.definitionViewLogic)'
        setDefinitionSuccess: 'set definition success (scenes.data-management.definition.definitionViewLogic)'
        setDefinitionFailure: 'set definition failure (scenes.data-management.definition.definitionViewLogic)'
        loadDefinitionSuccess: 'load definition success (scenes.data-management.definition.definitionViewLogic)'
        loadDefinitionFailure: 'load definition failure (scenes.data-management.definition.definitionViewLogic)'
        deleteDefinition: 'delete definition (scenes.data-management.definition.definitionViewLogic)'
        deleteDefinitionSuccess: 'delete definition success (scenes.data-management.definition.definitionViewLogic)'
        deleteDefinitionFailure: 'delete definition failure (scenes.data-management.definition.definitionViewLogic)'
        loadMetricsSuccess: 'load metrics success (scenes.data-management.definition.definitionViewLogic)'
        loadMetricsFailure: 'load metrics failure (scenes.data-management.definition.definitionViewLogic)'
        loadPreviewsSuccess: 'load previews success (scenes.data-management.definition.definitionViewLogic)'
        loadPreviewsFailure: 'load previews failure (scenes.data-management.definition.definitionViewLogic)'
        createMediaPreviewSuccess: 'create media preview success (scenes.data-management.definition.definitionViewLogic)'
        createMediaPreviewFailure: 'create media preview failure (scenes.data-management.definition.definitionViewLogic)'
        deleteMediaPreviewSuccess: 'delete media preview success (scenes.data-management.definition.definitionViewLogic)'
        deleteMediaPreviewFailure: 'delete media preview failure (scenes.data-management.definition.definitionViewLogic)'
    }
    actions: {
        setDefinition: (definition: Partial<Definition>, options?: SetDefinitionProps) => void
        loadDefinition: (id: Definition['id']) => void
        loadMetrics: (id: Definition['id']) => void
        setDefinitionMissing: () => void
        loadPreviews: () => void
        createMediaPreview: (uploadedMediaId: string, metadata?: Record<string, any>) => void
        deleteMediaPreview: (previewId: string) => void
        setDefinitionSuccess: (
            definition: Definition,
            payload?: {
                definition: Partial<Definition>
                options: SetDefinitionProps
            }
        ) => void
        setDefinitionFailure: (error: string, errorObject?: any) => void
        loadDefinitionSuccess: (
            definition:
                | {
                      created_at?: string | undefined
                      default_columns?: string[] | undefined
                      description?: string | undefined
                      enforcement_mode?: SchemaEnforcementMode | undefined
                      hidden?: boolean | undefined
                      id: string
                      is_action?: boolean | undefined
                      last_seen_at?: string | undefined
                      last_updated_at?: string | undefined
                      media_preview_urls?: string[] | undefined
                      name: string
                      owner?: UserBasicType | null | undefined
                      tags?: string[] | undefined
                      updated_at?: string | undefined
                      updated_by?: UserBasicType | null | undefined
                      verified?: boolean | undefined
                      verified_at?: string | undefined
                      verified_by?: string | undefined
                  }
                | {
                      created_at?: string | undefined
                      description?: string | undefined
                      example?: string | undefined
                      hidden?: boolean | undefined
                      id: string
                      is_action?: boolean | undefined
                      is_numerical?: boolean | undefined
                      is_seen_on_filtered_events?: boolean | undefined
                      last_seen_at?: string | undefined
                      name: string
                      property_type?: PropertyType | undefined
                      tags?: string[] | undefined
                      type?: PropertyDefinitionType | undefined
                      updated_at?: string | undefined
                      updated_by?: UserBasicType | null | undefined
                      verified?: boolean | undefined
                      verified_at?: string | undefined
                      verified_by?: string | undefined
                      virtual?: boolean | undefined
                  },
            payload?: {
                id: string
            }
        ) => void
        loadDefinitionFailure: (error: string, errorObject?: any) => void
        deleteDefinition: () => void
        deleteDefinitionSuccess: (definition: Definition, payload?: any) => void
        deleteDefinitionFailure: (error: string, errorObject?: any) => void
        loadMetricsSuccess: (
            metrics: EventDefinitionMetrics | null,
            payload?: {
                id: string
            }
        ) => void
        loadMetricsFailure: (error: string, errorObject?: any) => void
        loadPreviewsSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                value: true
            }
        ) => void
        loadPreviewsFailure: (error: string, errorObject?: any) => void
        createMediaPreviewSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                metadata: Record<string, any> | undefined
                uploadedMediaId: string
            }
        ) => void
        createMediaPreviewFailure: (error: string, errorObject?: any) => void
        deleteMediaPreviewSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                previewId: string
            }
        ) => void
        deleteMediaPreviewFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        setDefinition: (definition: Partial<Definition>, options?: SetDefinitionProps) => Promise<any>
        loadDefinition: (id: Definition['id']) => Promise<any>
        loadMetrics: (id: Definition['id']) => Promise<any>
        setDefinitionMissing: () => Promise<any>
        loadPreviews: () => Promise<any>
        createMediaPreview: (uploadedMediaId: string, metadata?: Record<string, any>) => Promise<any>
        deleteMediaPreview: (previewId: string) => Promise<any>
        setDefinitionSuccess: (
            definition: Definition,
            payload?: {
                definition: Partial<Definition>
                options: SetDefinitionProps
            }
        ) => Promise<any>
        setDefinitionFailure: (error: string, errorObject?: any) => Promise<any>
        loadDefinitionSuccess: (
            definition:
                | {
                      created_at?: string | undefined
                      default_columns?: string[] | undefined
                      description?: string | undefined
                      enforcement_mode?: SchemaEnforcementMode | undefined
                      hidden?: boolean | undefined
                      id: string
                      is_action?: boolean | undefined
                      last_seen_at?: string | undefined
                      last_updated_at?: string | undefined
                      media_preview_urls?: string[] | undefined
                      name: string
                      owner?: UserBasicType | null | undefined
                      tags?: string[] | undefined
                      updated_at?: string | undefined
                      updated_by?: UserBasicType | null | undefined
                      verified?: boolean | undefined
                      verified_at?: string | undefined
                      verified_by?: string | undefined
                  }
                | {
                      created_at?: string | undefined
                      description?: string | undefined
                      example?: string | undefined
                      hidden?: boolean | undefined
                      id: string
                      is_action?: boolean | undefined
                      is_numerical?: boolean | undefined
                      is_seen_on_filtered_events?: boolean | undefined
                      last_seen_at?: string | undefined
                      name: string
                      property_type?: PropertyType | undefined
                      tags?: string[] | undefined
                      type?: PropertyDefinitionType | undefined
                      updated_at?: string | undefined
                      updated_by?: UserBasicType | null | undefined
                      verified?: boolean | undefined
                      verified_at?: string | undefined
                      verified_by?: string | undefined
                      virtual?: boolean | undefined
                  },
            payload?: {
                id: string
            }
        ) => Promise<any>
        loadDefinitionFailure: (error: string, errorObject?: any) => Promise<any>
        deleteDefinition: () => Promise<any>
        deleteDefinitionSuccess: (definition: Definition, payload?: any) => Promise<any>
        deleteDefinitionFailure: (error: string, errorObject?: any) => Promise<any>
        loadMetricsSuccess: (
            metrics: EventDefinitionMetrics | null,
            payload?: {
                id: string
            }
        ) => Promise<any>
        loadMetricsFailure: (error: string, errorObject?: any) => Promise<any>
        loadPreviewsSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                value: true
            }
        ) => Promise<any>
        loadPreviewsFailure: (error: string, errorObject?: any) => Promise<any>
        createMediaPreviewSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                metadata: Record<string, any> | undefined
                uploadedMediaId: string
            }
        ) => Promise<any>
        createMediaPreviewFailure: (error: string, errorObject?: any) => Promise<any>
        deleteMediaPreviewSuccess: (
            previews: ObjectMediaPreview[],
            payload?: {
                previewId: string
            }
        ) => Promise<any>
        deleteMediaPreviewFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        definitionMissing: boolean
        definition: Definition
        definitionLoading: boolean
        metrics: EventDefinitionMetrics | null
        metricsLoading: boolean
        previews: ObjectMediaPreview[]
        previewsLoading: boolean
    }
    events: {}
    key: string
    listeners: {
        loadDefinitionSuccess: ((
            action: {
                type: 'load definition success (scenes.data-management.definition.definitionViewLogic)'
                payload: {
                    definition:
                        | {
                              created_at?: string | undefined
                              default_columns?: string[] | undefined
                              description?: string | undefined
                              enforcement_mode?: SchemaEnforcementMode | undefined
                              hidden?: boolean | undefined
                              id: string
                              is_action?: boolean | undefined
                              last_seen_at?: string | undefined
                              last_updated_at?: string | undefined
                              media_preview_urls?: string[] | undefined
                              name: string
                              owner?: UserBasicType | null | undefined
                              tags?: string[] | undefined
                              updated_at?: string | undefined
                              updated_by?: UserBasicType | null | undefined
                              verified?: boolean | undefined
                              verified_at?: string | undefined
                              verified_by?: string | undefined
                          }
                        | {
                              created_at?: string | undefined
                              description?: string | undefined
                              example?: string | undefined
                              hidden?: boolean | undefined
                              id: string
                              is_action?: boolean | undefined
                              is_numerical?: boolean | undefined
                              is_seen_on_filtered_events?: boolean | undefined
                              last_seen_at?: string | undefined
                              name: string
                              property_type?: PropertyType | undefined
                              tags?: string[] | undefined
                              type?: PropertyDefinitionType | undefined
                              updated_at?: string | undefined
                              updated_by?: UserBasicType | null | undefined
                              verified?: boolean | undefined
                              verified_at?: string | undefined
                              verified_by?: string | undefined
                              virtual?: boolean | undefined
                          }
                    payload?: {
                        id: string
                    }
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        createMediaPreviewSuccess: ((
            action: {
                type: 'create media preview success (scenes.data-management.definition.definitionViewLogic)'
                payload: {
                    previews: ObjectMediaPreview[]
                    payload?: {
                        metadata: Record<string, any> | undefined
                        uploadedMediaId: string
                    }
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        createMediaPreviewFailure: ((
            action: {
                type: 'create media preview failure (scenes.data-management.definition.definitionViewLogic)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        deleteMediaPreviewSuccess: ((
            action: {
                type: 'delete media preview success (scenes.data-management.definition.definitionViewLogic)'
                payload: {
                    previews: ObjectMediaPreview[]
                    payload?: {
                        previewId: string
                    }
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        deleteMediaPreviewFailure: ((
            action: {
                type: 'delete media preview failure (scenes.data-management.definition.definitionViewLogic)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'data-management', 'definition', 'definitionViewLogic']
    pathString: 'scenes.data-management.definition.definitionViewLogic'
    props: DefinitionLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        definitionMissing: boolean
        definition: Definition
        definitionLoading: boolean
        metrics: EventDefinitionMetrics | null
        metricsLoading: boolean
        previews: ObjectMediaPreview[]
        previewsLoading: boolean
    }
    reducers: {
        definitionMissing: (state: boolean, action: any, fullState: any) => boolean
        definition: (state: Definition, action: any, fullState: any) => Definition
        definitionLoading: (state: boolean, action: any, fullState: any) => boolean
        metrics: (state: EventDefinitionMetrics | null, action: any, fullState: any) => EventDefinitionMetrics | null
        metricsLoading: (state: boolean, action: any, fullState: any) => boolean
        previews: (state: ObjectMediaPreview[], action: any, fullState: any) => ObjectMediaPreview[]
        previewsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        definitionMissing: boolean
        definition: Definition
        definitionLoading: boolean
        metrics: EventDefinitionMetrics | null
        metricsLoading: boolean
        previews: ObjectMediaPreview[]
        previewsLoading: boolean
    }
    selectors: {
        definitionMissing: (state: any, props?: any) => boolean
        definition: (state: any, props?: any) => Definition
        definitionLoading: (state: any, props?: any) => boolean
        metrics: (state: any, props?: any) => EventDefinitionMetrics | null
        metricsLoading: (state: any, props?: any) => boolean
        previews: (state: any, props?: any) => ObjectMediaPreview[]
        previewsLoading: (state: any, props?: any) => boolean
        isEvent: (state: any, props?: any) => boolean
        isProperty: (state: any, props?: any) => boolean
        singular: (state: any, props?: any) => string
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
    }
    sharedListeners: {}
    values: {
        definitionMissing: boolean
        definition: Definition
        definitionLoading: boolean
        metrics: EventDefinitionMetrics | null
        metricsLoading: boolean
        previews: ObjectMediaPreview[]
        previewsLoading: boolean
        isEvent: boolean
        isProperty: boolean
        singular: string
        breadcrumbs: Breadcrumb[]
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        isEvent: (location: { hash: string; pathname: string; search: string }) => boolean
        isProperty: (isEvent: boolean) => boolean
        singular: (isEvent: boolean) => string
        breadcrumbs: (definition: Definition, isEvent: boolean) => Breadcrumb[]
    }
}
