// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:38 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { WorkflowLogicProps } from '../../../workflowLogic'
import type { InsightsFlow } from '../../types'
import type { CyclotronJobInvocationGlobals, PersonType } from '../../../../../../../frontend/src/types'
import type { InsightsFlowTestResult } from '../../steps/types'
import type { InsightsFlowTestInvocation } from './insightsFlowEditorTestLogic'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

export interface insightsFlowEditorNotificationTestLogicType extends Logic {
    actionCreators: {
        setSelectedNodeId: (selectedNodeId: string | null) => {
            type: 'set selected node id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                selectedNodeId: string | null
            }
        }
        setPersonSelectorOpen: (open: boolean) => {
            type: 'set person selector open (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                open: boolean
            }
        }
        setPersonSearchTerm: (term: string) => {
            type: 'set person search term (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                term: string
            }
        }
        loadSamplePersons: () => {
            type: 'load sample persons (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                value: true
            }
        }
        searchPersons: (searchTerm: string) => {
            type: 'search persons (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                searchTerm: string
            }
        }
        clearPersonSearch: () => {
            type: 'clear person search (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                value: true
            }
        }
        loadSamplePersonByDistinctId: (payload: { distinctId: string }) => {
            type: 'load sample person by distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                distinctId: string
            }
        }
        loadSamplePersonByDistinctIdSuccess: (sampleGlobals: CyclotronJobInvocationGlobals | null) => {
            type: 'load sample person by distinct id success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                sampleGlobals: CyclotronJobInvocationGlobals | null
            }
        }
        loadSamplePersonByDistinctIdFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load sample person by distinct id failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                error: string
                errorObject: any
            }
        }
        setEmailAddressOverride: (email: string) => {
            type: 'set email address override (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                email: string
            }
        }
        setSampleGlobals: (globals?: string | null) => {
            type: 'set sample globals (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                globals: string | null
            }
        }
        setSampleGlobalsError: (error: string | null) => {
            type: 'set sample globals error (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                error: string | null
            }
        }
        setTestResult: (testResult: InsightsFlowTestResult | null) => {
            type: 'set test result (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                testResult: InsightsFlowTestResult | null
            }
        }
        setNextActionId: (nextActionId: string | null) => {
            type: 'set next action id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                nextActionId: string | null
            }
        }
        setSelectedPersonDistinctId: (distinctId: string | null) => {
            type: 'set selected person distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                distinctId: string | null
            }
        }
        loadSamplePersonsSuccess: (
            samplePersons: PersonType[],
            payload?: {
                value: true
            }
        ) => {
            type: 'load sample persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                samplePersons: PersonType[]
                payload?: {
                    value: true
                }
            }
        }
        loadSamplePersonsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load sample persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        searchPersonsSuccess: (
            personSearchResults: PersonType[],
            payload?: {
                searchTerm: string
            }
        ) => {
            type: 'search persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                personSearchResults: PersonType[]
                payload?: {
                    searchTerm: string
                }
            }
        }
        searchPersonsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'search persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        setTestInvocationValue: (
            key: FieldName,
            value: any
        ) => {
            type: 'set test invocation value (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                name: FieldName
                value: any
            }
        }
        setTestInvocationValues: (values: DeepPartial<InsightsFlowTestInvocation>) => {
            type: 'set test invocation values (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                values: DeepPartial<InsightsFlowTestInvocation>
            }
        }
        setTestInvocationManualErrors: (errors: Record<string, any>) => {
            type: 'set test invocation manual errors (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                errors: Record<string, any>
            }
        }
        touchTestInvocationField: (key: string) => {
            type: 'touch test invocation field (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                key: string
            }
        }
        resetTestInvocation: (values?: InsightsFlowTestInvocation) => {
            type: 'reset test invocation (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                values?: InsightsFlowTestInvocation
            }
        }
        submitTestInvocation: () => {
            type: 'submit test invocation (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                value: boolean
            }
        }
        submitTestInvocationRequest: (testInvocation: InsightsFlowTestInvocation) => {
            type: 'submit test invocation request (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                testInvocation: InsightsFlowTestInvocation
            }
        }
        submitTestInvocationSuccess: (testInvocation: InsightsFlowTestInvocation) => {
            type: 'submit test invocation success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                testInvocation: InsightsFlowTestInvocation
            }
        }
        submitTestInvocationFailure: (
            error: Error,
            errors: Record<string, any>
        ) => {
            type: 'submit test invocation failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
            payload: {
                error: Error
                errors: Record<string, any>
            }
        }
    }
    actionKeys: {
        'set selected node id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setSelectedNodeId'
        'set person selector open (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setPersonSelectorOpen'
        'set person search term (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setPersonSearchTerm'
        'load sample persons (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'loadSamplePersons'
        'search persons (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'searchPersons'
        'clear person search (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'clearPersonSearch'
        'load sample person by distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'loadSamplePersonByDistinctId'
        'load sample person by distinct id success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'loadSamplePersonByDistinctIdSuccess'
        'load sample person by distinct id failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'loadSamplePersonByDistinctIdFailure'
        'set email address override (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setEmailAddressOverride'
        'set sample globals (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setSampleGlobals'
        'set sample globals error (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setSampleGlobalsError'
        'set test result (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setTestResult'
        'set next action id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setNextActionId'
        'set selected person distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setSelectedPersonDistinctId'
        'load sample persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'loadSamplePersonsSuccess'
        'load sample persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'loadSamplePersonsFailure'
        'search persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'searchPersonsSuccess'
        'search persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'searchPersonsFailure'
        'set test invocation value (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setTestInvocationValue'
        'set test invocation values (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setTestInvocationValues'
        'set test invocation manual errors (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'setTestInvocationManualErrors'
        'touch test invocation field (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'touchTestInvocationField'
        'reset test invocation (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'resetTestInvocation'
        'submit test invocation (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'submitTestInvocation'
        'submit test invocation request (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'submitTestInvocationRequest'
        'submit test invocation success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'submitTestInvocationSuccess'
        'submit test invocation failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)': 'submitTestInvocationFailure'
    }
    actionTypes: {
        setSelectedNodeId: 'set selected node id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setPersonSelectorOpen: 'set person selector open (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setPersonSearchTerm: 'set person search term (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        loadSamplePersons: 'load sample persons (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        searchPersons: 'search persons (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        clearPersonSearch: 'clear person search (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        loadSamplePersonByDistinctId: 'load sample person by distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        loadSamplePersonByDistinctIdSuccess: 'load sample person by distinct id success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        loadSamplePersonByDistinctIdFailure: 'load sample person by distinct id failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setEmailAddressOverride: 'set email address override (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setSampleGlobals: 'set sample globals (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setSampleGlobalsError: 'set sample globals error (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setTestResult: 'set test result (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setNextActionId: 'set next action id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setSelectedPersonDistinctId: 'set selected person distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        loadSamplePersonsSuccess: 'load sample persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        loadSamplePersonsFailure: 'load sample persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        searchPersonsSuccess: 'search persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        searchPersonsFailure: 'search persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setTestInvocationValue: 'set test invocation value (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setTestInvocationValues: 'set test invocation values (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        setTestInvocationManualErrors: 'set test invocation manual errors (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        touchTestInvocationField: 'touch test invocation field (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        resetTestInvocation: 'reset test invocation (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        submitTestInvocation: 'submit test invocation (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        submitTestInvocationRequest: 'submit test invocation request (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        submitTestInvocationSuccess: 'submit test invocation success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
        submitTestInvocationFailure: 'submit test invocation failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
    }
    actions: {
        setSelectedNodeId: (selectedNodeId: string | null) => void
        setPersonSelectorOpen: (open: boolean) => void
        setPersonSearchTerm: (term: string) => void
        loadSamplePersons: () => void
        searchPersons: (searchTerm: string) => void
        clearPersonSearch: () => void
        loadSamplePersonByDistinctId: (payload: { distinctId: string }) => void
        loadSamplePersonByDistinctIdSuccess: (sampleGlobals: CyclotronJobInvocationGlobals | null) => void
        loadSamplePersonByDistinctIdFailure: (error: string, errorObject?: any) => void
        setEmailAddressOverride: (email: string) => void
        setSampleGlobals: (globals?: string | null) => void
        setSampleGlobalsError: (error: string | null) => void
        setTestResult: (testResult: InsightsFlowTestResult | null) => void
        setNextActionId: (nextActionId: string | null) => void
        setSelectedPersonDistinctId: (distinctId: string | null) => void
        loadSamplePersonsSuccess: (
            samplePersons: PersonType[],
            payload?: {
                value: true
            }
        ) => void
        loadSamplePersonsFailure: (error: string, errorObject?: any) => void
        searchPersonsSuccess: (
            personSearchResults: PersonType[],
            payload?: {
                searchTerm: string
            }
        ) => void
        searchPersonsFailure: (error: string, errorObject?: any) => void
        setTestInvocationValue: (key: FieldName, value: any) => void
        setTestInvocationValues: (values: DeepPartial<InsightsFlowTestInvocation>) => void
        setTestInvocationManualErrors: (errors: Record<string, any>) => void
        touchTestInvocationField: (key: string) => void
        resetTestInvocation: (values?: InsightsFlowTestInvocation) => void
        submitTestInvocation: () => void
        submitTestInvocationRequest: (testInvocation: InsightsFlowTestInvocation) => void
        submitTestInvocationSuccess: (testInvocation: InsightsFlowTestInvocation) => void
        submitTestInvocationFailure: (error: Error, errors: Record<string, any>) => void
    }
    asyncActions: {
        setSelectedNodeId: (selectedNodeId: string | null) => Promise<any>
        setPersonSelectorOpen: (open: boolean) => Promise<any>
        setPersonSearchTerm: (term: string) => Promise<any>
        loadSamplePersons: () => Promise<any>
        searchPersons: (searchTerm: string) => Promise<any>
        clearPersonSearch: () => Promise<any>
        loadSamplePersonByDistinctId: (payload: { distinctId: string }) => Promise<any>
        loadSamplePersonByDistinctIdSuccess: (sampleGlobals: CyclotronJobInvocationGlobals | null) => Promise<any>
        loadSamplePersonByDistinctIdFailure: (error: string, errorObject?: any) => Promise<any>
        setEmailAddressOverride: (email: string) => Promise<any>
        setSampleGlobals: (globals?: string | null) => Promise<any>
        setSampleGlobalsError: (error: string | null) => Promise<any>
        setTestResult: (testResult: InsightsFlowTestResult | null) => Promise<any>
        setNextActionId: (nextActionId: string | null) => Promise<any>
        setSelectedPersonDistinctId: (distinctId: string | null) => Promise<any>
        loadSamplePersonsSuccess: (
            samplePersons: PersonType[],
            payload?: {
                value: true
            }
        ) => Promise<any>
        loadSamplePersonsFailure: (error: string, errorObject?: any) => Promise<any>
        searchPersonsSuccess: (
            personSearchResults: PersonType[],
            payload?: {
                searchTerm: string
            }
        ) => Promise<any>
        searchPersonsFailure: (error: string, errorObject?: any) => Promise<any>
        setTestInvocationValue: (key: FieldName, value: any) => Promise<any>
        setTestInvocationValues: (values: DeepPartial<InsightsFlowTestInvocation>) => Promise<any>
        setTestInvocationManualErrors: (errors: Record<string, any>) => Promise<any>
        touchTestInvocationField: (key: string) => Promise<any>
        resetTestInvocation: (values?: InsightsFlowTestInvocation) => Promise<any>
        submitTestInvocation: () => Promise<any>
        submitTestInvocationRequest: (testInvocation: InsightsFlowTestInvocation) => Promise<any>
        submitTestInvocationSuccess: (testInvocation: InsightsFlowTestInvocation) => Promise<any>
        submitTestInvocationFailure: (error: Error, errors: Record<string, any>) => Promise<any>
    }
    defaults: {
        personSelectorOpen: boolean
        personSearchTerm: string
        emailAddressOverride: string | null
        testResult: InsightsFlowTestResult | null
        nextActionId: string | null
        selectedPersonDistinctId: string | null
        sampleGlobals: CyclotronJobInvocationGlobals | null
        sampleGlobalsLoading: boolean
        sampleGlobalsError: string | null
        samplePersons: PersonType[]
        samplePersonsLoading: boolean
        personSearchResults: PersonType[]
        personSearchResultsLoading: boolean
        testInvocation: InsightsFlowTestInvocation
        isTestInvocationSubmitting: boolean
        showTestInvocationErrors: boolean
        testInvocationChanged: boolean
        testInvocationTouches: Record<string, boolean>
        testInvocationManualErrors: Record<string, any>
    }
    events: {}
    key: string
    listeners: {
        loadSamplePersonByDistinctId: ((
            action: {
                type: 'load sample person by distinct id (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    distinctId: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setPersonSearchTerm: ((
            action: {
                type: 'set person search term (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    term: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setPersonSelectorOpen: ((
            action: {
                type: 'set person selector open (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    open: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadSamplePersonsSuccess: ((
            action: {
                type: 'load sample persons success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    samplePersons: PersonType[]
                    payload?: {
                        value: true
                    }
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadSamplePersonsFailure: ((
            action: {
                type: 'load sample persons failure (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setSampleGlobals: ((
            action: {
                type: 'set sample globals (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    globals: string | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadSamplePersonByDistinctIdSuccess: ((
            action: {
                type: 'load sample person by distinct id success (products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*)'
                payload: {
                    sampleGlobals: CyclotronJobInvocationGlobals | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: [
        'products',
        'workflows',
        'frontend',
        'Workflows',
        'insightsflows',
        'panel',
        'testing',
        'insightsFlowEditorNotificationTestLogic',
        '*',
    ]
    pathString: 'products.workflows.frontend.Workflows.insightsflows.panel.testing.insightsFlowEditorNotificationTestLogic.*'
    props: WorkflowLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        personSelectorOpen: boolean
        personSearchTerm: string
        emailAddressOverride: string | null
        testResult: InsightsFlowTestResult | null
        nextActionId: string | null
        selectedPersonDistinctId: string | null
        sampleGlobals: CyclotronJobInvocationGlobals | null
        sampleGlobalsLoading: boolean
        sampleGlobalsError: string | null
        samplePersons: PersonType[]
        samplePersonsLoading: boolean
        personSearchResults: PersonType[]
        personSearchResultsLoading: boolean
        testInvocation: InsightsFlowTestInvocation
        isTestInvocationSubmitting: boolean
        showTestInvocationErrors: boolean
        testInvocationChanged: boolean
        testInvocationTouches: Record<string, boolean>
        testInvocationManualErrors: Record<string, any>
    }
    reducers: {
        personSelectorOpen: (state: boolean, action: any, fullState: any) => boolean
        personSearchTerm: (state: string, action: any, fullState: any) => string
        emailAddressOverride: (state: string | null, action: any, fullState: any) => string | null
        testResult: (state: InsightsFlowTestResult | null, action: any, fullState: any) => InsightsFlowTestResult | null
        nextActionId: (state: string | null, action: any, fullState: any) => string | null
        selectedPersonDistinctId: (state: string | null, action: any, fullState: any) => string | null
        sampleGlobals: (
            state: CyclotronJobInvocationGlobals | null,
            action: any,
            fullState: any
        ) => CyclotronJobInvocationGlobals | null
        sampleGlobalsLoading: (state: boolean, action: any, fullState: any) => boolean
        sampleGlobalsError: (state: string | null, action: any, fullState: any) => string | null
        samplePersons: (state: PersonType[], action: any, fullState: any) => PersonType[]
        samplePersonsLoading: (state: boolean, action: any, fullState: any) => boolean
        personSearchResults: (state: PersonType[], action: any, fullState: any) => PersonType[]
        personSearchResultsLoading: (state: boolean, action: any, fullState: any) => boolean
        testInvocation: (state: InsightsFlowTestInvocation, action: any, fullState: any) => InsightsFlowTestInvocation
        isTestInvocationSubmitting: (state: boolean, action: any, fullState: any) => boolean
        showTestInvocationErrors: (state: boolean, action: any, fullState: any) => boolean
        testInvocationChanged: (state: boolean, action: any, fullState: any) => boolean
        testInvocationTouches: (state: Record<string, boolean>, action: any, fullState: any) => Record<string, boolean>
        testInvocationManualErrors: (state: Record<string, any>, action: any, fullState: any) => Record<string, any>
    }
    selector: (state: any) => {
        personSelectorOpen: boolean
        personSearchTerm: string
        emailAddressOverride: string | null
        testResult: InsightsFlowTestResult | null
        nextActionId: string | null
        selectedPersonDistinctId: string | null
        sampleGlobals: CyclotronJobInvocationGlobals | null
        sampleGlobalsLoading: boolean
        sampleGlobalsError: string | null
        samplePersons: PersonType[]
        samplePersonsLoading: boolean
        personSearchResults: PersonType[]
        personSearchResultsLoading: boolean
        testInvocation: InsightsFlowTestInvocation
        isTestInvocationSubmitting: boolean
        showTestInvocationErrors: boolean
        testInvocationChanged: boolean
        testInvocationTouches: Record<string, boolean>
        testInvocationManualErrors: Record<string, any>
    }
    selectors: {
        personSelectorOpen: (state: any, props?: any) => boolean
        personSearchTerm: (state: any, props?: any) => string
        emailAddressOverride: (state: any, props?: any) => string | null
        testResult: (state: any, props?: any) => InsightsFlowTestResult | null
        nextActionId: (state: any, props?: any) => string | null
        selectedPersonDistinctId: (state: any, props?: any) => string | null
        sampleGlobals: (state: any, props?: any) => CyclotronJobInvocationGlobals | null
        sampleGlobalsLoading: (state: any, props?: any) => boolean
        sampleGlobalsError: (state: any, props?: any) => string | null
        samplePersons: (state: any, props?: any) => PersonType[]
        samplePersonsLoading: (state: any, props?: any) => boolean
        personSearchResults: (state: any, props?: any) => PersonType[]
        personSearchResultsLoading: (state: any, props?: any) => boolean
        testInvocation: (state: any, props?: any) => InsightsFlowTestInvocation
        isTestInvocationSubmitting: (state: any, props?: any) => boolean
        showTestInvocationErrors: (state: any, props?: any) => boolean
        testInvocationChanged: (state: any, props?: any) => boolean
        testInvocationTouches: (state: any, props?: any) => Record<string, boolean>
        testInvocationManualErrors: (state: any, props?: any) => Record<string, any>
        workflow: (state: any, props?: any) => InsightsFlow
        workflowSanitized: (state: any, props?: any) => InsightsFlow
        selectedNodeId: (state: any, props?: any) => string | null
        testInvocationTouched: (state: any, props?: any) => boolean
        testInvocationValidationErrors: (
            state: any,
            props?: any
        ) => DeepPartialMap<InsightsFlowTestInvocation, ValidationErrorType>
        testInvocationAllErrors: (state: any, props?: any) => Record<string, any>
        testInvocationHasErrors: (state: any, props?: any) => boolean
        testInvocationErrors: (
            state: any,
            props?: any
        ) => DeepPartialMap<InsightsFlowTestInvocation, ValidationErrorType>
        isTestInvocationValid: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        personSelectorOpen: boolean
        personSearchTerm: string
        emailAddressOverride: string | null
        testResult: InsightsFlowTestResult | null
        nextActionId: string | null
        selectedPersonDistinctId: string | null
        sampleGlobals: CyclotronJobInvocationGlobals | null
        sampleGlobalsLoading: boolean
        sampleGlobalsError: string | null
        samplePersons: PersonType[]
        samplePersonsLoading: boolean
        personSearchResults: PersonType[]
        personSearchResultsLoading: boolean
        testInvocation: InsightsFlowTestInvocation
        isTestInvocationSubmitting: boolean
        showTestInvocationErrors: boolean
        testInvocationChanged: boolean
        testInvocationTouches: Record<string, boolean>
        testInvocationManualErrors: Record<string, any>
        workflow: InsightsFlow
        workflowSanitized: InsightsFlow
        selectedNodeId: string | null
        testInvocationTouched: boolean
        testInvocationValidationErrors: DeepPartialMap<InsightsFlowTestInvocation, ValidationErrorType>
        testInvocationAllErrors: Record<string, any>
        testInvocationHasErrors: boolean
        testInvocationErrors: DeepPartialMap<InsightsFlowTestInvocation, ValidationErrorType>
        isTestInvocationValid: boolean
    }
    _isKea: true
    _isKeaWithKey: true
}
