// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:38 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Task, TaskUpsertProps } from '../types'

export interface tasksLogicType extends Logic {
    actionCreators: {
        openTask: (taskId: Task['id']) => {
            type: 'open task (products.tasks.frontend.tasksLogic)'
            payload: {
                taskId: string
            }
        }
        updateTask: (task: Task) => {
            type: 'update task (products.tasks.frontend.tasksLogic)'
            payload: {
                task: Task
            }
        }
        loadTasks: () => {
            type: 'load tasks (products.tasks.frontend.tasksLogic)'
            payload: any
        }
        loadTasksSuccess: (
            tasks: Task[],
            payload?: any
        ) => {
            type: 'load tasks success (products.tasks.frontend.tasksLogic)'
            payload: {
                tasks: Task[]
                payload?: any
            }
        }
        loadTasksFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load tasks failure (products.tasks.frontend.tasksLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        createTask: ({ data }: { data: TaskUpsertProps }) => {
            type: 'create task (products.tasks.frontend.tasksLogic)'
            payload: {
                data: TaskUpsertProps
            }
        }
        createTaskSuccess: (
            tasks: Task[],
            payload?: {
                data: TaskUpsertProps
            }
        ) => {
            type: 'create task success (products.tasks.frontend.tasksLogic)'
            payload: {
                tasks: Task[]
                payload?: {
                    data: TaskUpsertProps
                }
            }
        }
        createTaskFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'create task failure (products.tasks.frontend.tasksLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        deleteTask: ({ taskId }: { taskId: string }) => {
            type: 'delete task (products.tasks.frontend.tasksLogic)'
            payload: {
                taskId: string
            }
        }
        deleteTaskSuccess: (
            tasks: Task[],
            payload?: {
                taskId: string
            }
        ) => {
            type: 'delete task success (products.tasks.frontend.tasksLogic)'
            payload: {
                tasks: Task[]
                payload?: {
                    taskId: string
                }
            }
        }
        deleteTaskFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'delete task failure (products.tasks.frontend.tasksLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'open task (products.tasks.frontend.tasksLogic)': 'openTask'
        'update task (products.tasks.frontend.tasksLogic)': 'updateTask'
        'load tasks (products.tasks.frontend.tasksLogic)': 'loadTasks'
        'load tasks success (products.tasks.frontend.tasksLogic)': 'loadTasksSuccess'
        'load tasks failure (products.tasks.frontend.tasksLogic)': 'loadTasksFailure'
        'create task (products.tasks.frontend.tasksLogic)': 'createTask'
        'create task success (products.tasks.frontend.tasksLogic)': 'createTaskSuccess'
        'create task failure (products.tasks.frontend.tasksLogic)': 'createTaskFailure'
        'delete task (products.tasks.frontend.tasksLogic)': 'deleteTask'
        'delete task success (products.tasks.frontend.tasksLogic)': 'deleteTaskSuccess'
        'delete task failure (products.tasks.frontend.tasksLogic)': 'deleteTaskFailure'
    }
    actionTypes: {
        openTask: 'open task (products.tasks.frontend.tasksLogic)'
        updateTask: 'update task (products.tasks.frontend.tasksLogic)'
        loadTasks: 'load tasks (products.tasks.frontend.tasksLogic)'
        loadTasksSuccess: 'load tasks success (products.tasks.frontend.tasksLogic)'
        loadTasksFailure: 'load tasks failure (products.tasks.frontend.tasksLogic)'
        createTask: 'create task (products.tasks.frontend.tasksLogic)'
        createTaskSuccess: 'create task success (products.tasks.frontend.tasksLogic)'
        createTaskFailure: 'create task failure (products.tasks.frontend.tasksLogic)'
        deleteTask: 'delete task (products.tasks.frontend.tasksLogic)'
        deleteTaskSuccess: 'delete task success (products.tasks.frontend.tasksLogic)'
        deleteTaskFailure: 'delete task failure (products.tasks.frontend.tasksLogic)'
    }
    actions: {
        openTask: (taskId: Task['id']) => void
        updateTask: (task: Task) => void
        loadTasks: () => void
        loadTasksSuccess: (tasks: Task[], payload?: any) => void
        loadTasksFailure: (error: string, errorObject?: any) => void
        createTask: ({ data }: { data: TaskUpsertProps }) => void
        createTaskSuccess: (
            tasks: Task[],
            payload?: {
                data: TaskUpsertProps
            }
        ) => void
        createTaskFailure: (error: string, errorObject?: any) => void
        deleteTask: ({ taskId }: { taskId: string }) => void
        deleteTaskSuccess: (
            tasks: Task[],
            payload?: {
                taskId: string
            }
        ) => void
        deleteTaskFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        openTask: (taskId: Task['id']) => Promise<any>
        updateTask: (task: Task) => Promise<any>
        loadTasks: () => Promise<any>
        loadTasksSuccess: (tasks: Task[], payload?: any) => Promise<any>
        loadTasksFailure: (error: string, errorObject?: any) => Promise<any>
        createTask: ({ data }: { data: TaskUpsertProps }) => Promise<any>
        createTaskSuccess: (
            tasks: Task[],
            payload?: {
                data: TaskUpsertProps
            }
        ) => Promise<any>
        createTaskFailure: (error: string, errorObject?: any) => Promise<any>
        deleteTask: ({ taskId }: { taskId: string }) => Promise<any>
        deleteTaskSuccess: (
            tasks: Task[],
            payload?: {
                taskId: string
            }
        ) => Promise<any>
        deleteTaskFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        tasks: Task[]
        tasksLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {
        openTask: ((
            action: {
                type: 'open task (products.tasks.frontend.tasksLogic)'
                payload: {
                    taskId: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['products', 'tasks', 'frontend', 'tasksLogic']
    pathString: 'products.tasks.frontend.tasksLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        tasks: Task[]
        tasksLoading: boolean
    }
    reducers: {
        tasks: (state: Task[], action: any, fullState: any) => Task[]
        tasksLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        tasks: Task[]
        tasksLoading: boolean
    }
    selectors: {
        tasks: (state: any, props?: any) => Task[]
        tasksLoading: (state: any, props?: any) => boolean
        repositories: (state: any, props?: any) => string[]
    }
    sharedListeners: {}
    values: {
        tasks: Task[]
        tasksLoading: boolean
        repositories: string[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        repositories: (tasks: Task[]) => string[]
    }
}
