# Generated by Django 4.2.29 on 2026-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_warehouse", "0031_migrate_5min_to_15min"),
    ]

    operations = [
        migrations.AddField(
            model_name="datamodelingjob",
            name="engine",
            field=models.CharField(
                choices=[("datastore", "Datastore"), ("duckgres", "Duckgres")],
                default="datastore",
                max_length=20,
            ),
        ),
    ]
