// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:31 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { CyclotronJobTemplateOption, CyclotronJobTemplateSuggestionsLogicProps, Fuse } from './cyclotronJobTemplateSuggestionsLogic'

export interface cyclotronJobTemplateSuggestionsLogicType extends Logic {
    actionCreators: {
        setSearch: (search: string) => {
            type: 'set search (components.cyclotron-jobs.cyclotronJobTemplateSuggestionsLogic.*)'
            payload: {
                search: string
            }
        }
    }
    actionKeys: {
        'set search (components.cyclotron-jobs.cyclotronJobTemplateSuggestionsLogic.*)': 'setSearch'
    }
    actionTypes: {
        setSearch: 'set search (components.cyclotron-jobs.cyclotronJobTemplateSuggestionsLogic.*)'
    }
    actions: {
        setSearch: (search: string) => void
    }
    asyncActions: {
        setSearch: (search: string) => Promise<any>
    }
    defaults: {
        search: string
    }
    events: {}
    key: 'fn' | 'liquid'
    listeners: {}
    path: ['components', 'cyclotron-jobs', 'cyclotronJobTemplateSuggestionsLogic', '*']
    pathString: 'components.cyclotron-jobs.cyclotronJobTemplateSuggestionsLogic.*'
    props: CyclotronJobTemplateSuggestionsLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        search: string
    }
    reducers: {
        search: (state: string, action: any, fullState: any) => string
    }
    selector: (state: any) => {
        search: string
    }
    selectors: {
        search: (state: any, props?: any) => string
        allOptions: (state: any, props?: any) => CyclotronJobTemplateOption[]
        optionsFuse: (state: any, props?: any) => Fuse
        optionsFiltered: (state: any, props?: any) => CyclotronJobTemplateOption[]
    }
    sharedListeners: {}
    values: {
        search: string
        allOptions: CyclotronJobTemplateOption[]
        optionsFuse: Fuse
        optionsFiltered: CyclotronJobTemplateOption[]
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        allOptions: (templating: 'fn' | 'liquid') => CyclotronJobTemplateOption[]
        optionsFuse: (allOptions: CyclotronJobTemplateOption[]) => Fuse
        optionsFiltered: (
            allOptions: CyclotronJobTemplateOption[],
            optionsFuse: Fuse,
            search: string
        ) => CyclotronJobTemplateOption[]
    }
}
