// Generated by kea-typegen on Sun, 02 Aug 2026 21:37:18 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DataThemeLogicProps } from './dataThemeLogic'
import type { DataColorThemeModel, TeamPublicType, TeamType } from '../types'
import type { DataColorTheme, DataColorToken } from '../lib/colors'

export interface dataThemeLogicType extends Logic {
    actionCreators: {
        setThemes: (themes: any) => {
            type: 'set themes (scenes.dataThemeLogic)'
            payload: {
                themes: any
            }
        }
        loadThemes: () => {
            type: 'load themes (scenes.dataThemeLogic)'
            payload: any
        }
        loadThemesSuccess: (
            themes: DataColorThemeModel[],
            payload?: any
        ) => {
            type: 'load themes success (scenes.dataThemeLogic)'
            payload: {
                themes: DataColorThemeModel[]
                payload?: any
            }
        }
        loadThemesFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load themes failure (scenes.dataThemeLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'set themes (scenes.dataThemeLogic)': 'setThemes'
        'load themes (scenes.dataThemeLogic)': 'loadThemes'
        'load themes success (scenes.dataThemeLogic)': 'loadThemesSuccess'
        'load themes failure (scenes.dataThemeLogic)': 'loadThemesFailure'
    }
    actionTypes: {
        setThemes: 'set themes (scenes.dataThemeLogic)'
        loadThemes: 'load themes (scenes.dataThemeLogic)'
        loadThemesSuccess: 'load themes success (scenes.dataThemeLogic)'
        loadThemesFailure: 'load themes failure (scenes.dataThemeLogic)'
    }
    actions: {
        setThemes: (themes: any) => void
        loadThemes: () => void
        loadThemesSuccess: (themes: DataColorThemeModel[], payload?: any) => void
        loadThemesFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        setThemes: (themes: any) => Promise<any>
        loadThemes: () => Promise<any>
        loadThemesSuccess: (themes: DataColorThemeModel[], payload?: any) => Promise<any>
        loadThemesFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        themes: DataColorThemeModel[] | null
        themesLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'dataThemeLogic']
    pathString: 'scenes.dataThemeLogic'
    props: DataThemeLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        themes: DataColorThemeModel[] | null
        themesLoading: boolean
    }
    reducers: {
        themes: (state: DataColorThemeModel[] | null, action: any, fullState: any) => DataColorThemeModel[] | null
        themesLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        themes: DataColorThemeModel[] | null
        themesLoading: boolean
    }
    selectors: {
        themes: (state: any, props?: any) => DataColorThemeModel[] | null
        themesLoading: (state: any, props?: any) => boolean
        currentTeam: (state: any, props?: any) => TeamPublicType | TeamType | null
        insightsTheme: (state: any, props?: any) => DataColorThemeModel | null | undefined
        defaultTheme: (state: any, props?: any) => DataColorThemeModel | null
        getTheme: (state: any, props?: any) => (themeId: number | string | null | undefined) => DataColorTheme | null
        getColorFromToken: (
            state: any,
            props?: any
        ) => (themeId: number | string | null | undefined, colorToken: string) => string | null
        getAvailableColorTokens: (
            state: any,
            props?: any
        ) => (themeId: number | string | null | undefined) => DataColorToken[] | null
    }
    sharedListeners: {}
    values: {
        themes: DataColorThemeModel[] | null
        themesLoading: boolean
        currentTeam: TeamPublicType | TeamType | null
        insightsTheme: DataColorThemeModel | null | undefined
        defaultTheme: DataColorThemeModel | null
        getTheme: (themeId: number | string | null | undefined) => DataColorTheme | null
        getColorFromToken: (themeId: number | string | null | undefined, colorToken: string) => string | null
        getAvailableColorTokens: (themeId: number | string | null | undefined) => DataColorToken[] | null
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        insightsTheme: (themes: DataColorThemeModel[] | null) => DataColorThemeModel | null | undefined
        defaultTheme: (
            currentTeam:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/types').TeamPublicType
                | import('/home/z/work/hanzo/insights/frontend/src/types').TeamType,
            themes: DataColorThemeModel[] | null,
            insightsTheme: DataColorThemeModel | null | undefined
        ) => DataColorThemeModel | null
        getTheme: (
            themes: DataColorThemeModel[] | null,
            defaultTheme: DataColorThemeModel | null
        ) => (themeId: number | string | null | undefined) => DataColorTheme | null
        getColorFromToken: (
            getTheme: (themeId: number | string | null | undefined) => DataColorTheme | null
        ) => (themeId: number | string | null | undefined, colorToken: string) => string | null
        getAvailableColorTokens: (
            getTheme: (themeId: number | string | null | undefined) => DataColorTheme | null
        ) => (themeId: number | string | null | undefined) => DataColorToken[] | null
    }
}
