// Generated by kea-typegen on Sun, 02 Aug 2026 21:39:11 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { EditorSizingLogicProps } from './editorSizingLogic'
import type { ResizerLogicProps } from '../../../lib/components/Resizer/resizerLogic'

export interface editorSizingLogicType extends Logic {
    actionCreators: {
        sidebarSetDesiredSize: (size: number | null) => {
            type: 'sidebar set desired size (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                size: number | null
            }
        }
        databaseTreeEndResize: () => {
            type: 'database tree end resize (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                value: true
            }
        }
        databaseTreeSetDesiredSize: (size: number | null) => {
            type: 'database tree set desired size (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                size: number | null
            }
        }
        resetDefaultSidebarWidth: () => {
            type: 'reset default sidebar width (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                value: true
            }
        }
        toggleDatabaseTreeCollapsed: () => {
            type: 'toggle database tree collapsed (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                value: true
            }
        }
        setDatabaseTreeCollapsed: (collapsed: boolean) => {
            type: 'set database tree collapsed (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                collapsed: boolean
            }
        }
        setDatabaseTreeWillCollapse: (willCollapse: boolean) => {
            type: 'set database tree will collapse (scenes.data-warehouse.editor.editorSizingLogic)'
            payload: {
                willCollapse: boolean
            }
        }
    }
    actionKeys: {
        'sidebar set desired size (scenes.data-warehouse.editor.editorSizingLogic)': 'sidebarSetDesiredSize'
        'database tree end resize (scenes.data-warehouse.editor.editorSizingLogic)': 'databaseTreeEndResize'
        'database tree set desired size (scenes.data-warehouse.editor.editorSizingLogic)': 'databaseTreeSetDesiredSize'
        'reset default sidebar width (scenes.data-warehouse.editor.editorSizingLogic)': 'resetDefaultSidebarWidth'
        'toggle database tree collapsed (scenes.data-warehouse.editor.editorSizingLogic)': 'toggleDatabaseTreeCollapsed'
        'set database tree collapsed (scenes.data-warehouse.editor.editorSizingLogic)': 'setDatabaseTreeCollapsed'
        'set database tree will collapse (scenes.data-warehouse.editor.editorSizingLogic)': 'setDatabaseTreeWillCollapse'
    }
    actionTypes: {
        sidebarSetDesiredSize: 'sidebar set desired size (scenes.data-warehouse.editor.editorSizingLogic)'
        databaseTreeEndResize: 'database tree end resize (scenes.data-warehouse.editor.editorSizingLogic)'
        databaseTreeSetDesiredSize: 'database tree set desired size (scenes.data-warehouse.editor.editorSizingLogic)'
        resetDefaultSidebarWidth: 'reset default sidebar width (scenes.data-warehouse.editor.editorSizingLogic)'
        toggleDatabaseTreeCollapsed: 'toggle database tree collapsed (scenes.data-warehouse.editor.editorSizingLogic)'
        setDatabaseTreeCollapsed: 'set database tree collapsed (scenes.data-warehouse.editor.editorSizingLogic)'
        setDatabaseTreeWillCollapse: 'set database tree will collapse (scenes.data-warehouse.editor.editorSizingLogic)'
    }
    actions: {
        sidebarSetDesiredSize: (size: number | null) => void
        databaseTreeEndResize: () => void
        databaseTreeSetDesiredSize: (size: number | null) => void
        resetDefaultSidebarWidth: () => void
        toggleDatabaseTreeCollapsed: () => void
        setDatabaseTreeCollapsed: (collapsed: boolean) => void
        setDatabaseTreeWillCollapse: (willCollapse: boolean) => void
    }
    asyncActions: {
        sidebarSetDesiredSize: (size: number | null) => Promise<any>
        databaseTreeEndResize: () => Promise<any>
        databaseTreeSetDesiredSize: (size: number | null) => Promise<any>
        resetDefaultSidebarWidth: () => Promise<any>
        toggleDatabaseTreeCollapsed: () => Promise<any>
        setDatabaseTreeCollapsed: (collapsed: boolean) => Promise<any>
        setDatabaseTreeWillCollapse: (willCollapse: boolean) => Promise<any>
    }
    defaults: {
        isDatabaseTreeCollapsed: boolean
        databaseTreeWillCollapse: boolean
    }
    events: {}
    key: undefined
    listeners: {
        resetDefaultSidebarWidth: ((
            action: {
                type: 'reset default sidebar width (scenes.data-warehouse.editor.editorSizingLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'data-warehouse', 'editor', 'editorSizingLogic']
    pathString: 'scenes.data-warehouse.editor.editorSizingLogic'
    props: EditorSizingLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        isDatabaseTreeCollapsed: boolean
        databaseTreeWillCollapse: boolean
    }
    reducers: {
        isDatabaseTreeCollapsed: (state: boolean, action: any, fullState: any) => boolean
        databaseTreeWillCollapse: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        isDatabaseTreeCollapsed: boolean
        databaseTreeWillCollapse: boolean
    }
    selectors: {
        isDatabaseTreeCollapsed: (state: any, props?: any) => boolean
        databaseTreeWillCollapse: (state: any, props?: any) => boolean
        sourceNavigatorDesiredSize: (state: any, props?: any) => number | null
        sidebarDesiredSize: (state: any, props?: any) => number | null
        queryPaneDesiredSize: (state: any, props?: any) => number | null
        databaseTreeIsResizing: (state: any, props?: any) => boolean
        databaseTreeDesiredSize: (state: any, props?: any) => number | null
        editorSceneRef: (state: any, props?: any) => any
        sourceNavigatorWidth: (state: any, props?: any) => number
        queryPaneHeight: (state: any, props?: any) => number
        queryTabsWidth: (state: any, props?: any) => number
        sourceNavigatorResizerProps: (state: any, props?: any) => ResizerLogicProps
        queryPaneResizerProps: (state: any, props?: any) => ResizerLogicProps
        sidebarWidth: (state: any, props?: any) => number
        sidebarResizerProps: (state: any, props?: any) => ResizerLogicProps
        databaseTreeWidth: (state: any, props?: any) => number
        databaseTreeResizerProps: (state: any, props?: any) => ResizerLogicProps
    }
    sharedListeners: {}
    values: {
        isDatabaseTreeCollapsed: boolean
        databaseTreeWillCollapse: boolean
        sourceNavigatorDesiredSize: number | null
        sidebarDesiredSize: number | null
        queryPaneDesiredSize: number | null
        databaseTreeIsResizing: boolean
        databaseTreeDesiredSize: number | null
        editorSceneRef: any
        sourceNavigatorWidth: number
        queryPaneHeight: number
        queryTabsWidth: number
        sourceNavigatorResizerProps: ResizerLogicProps
        queryPaneResizerProps: ResizerLogicProps
        sidebarWidth: number
        sidebarResizerProps: ResizerLogicProps
        databaseTreeWidth: number
        databaseTreeResizerProps: ResizerLogicProps
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        editorSceneRef: (editorSceneRef: any) => any
        sourceNavigatorWidth: (sourceNavigatorDesiredSize: number | null) => number
        queryPaneHeight: (queryPaneDesiredSize: number | null) => number
        queryTabsWidth: (queryPaneDesiredSize: number | null) => number
        sourceNavigatorResizerProps: (sourceNavigatorResizerProps: ResizerLogicProps) => ResizerLogicProps
        queryPaneResizerProps: (queryPaneResizerProps: ResizerLogicProps) => ResizerLogicProps
        sidebarWidth: (sidebarDesiredSize: number | null) => number
        sidebarResizerProps: (sidebarResizerProps: ResizerLogicProps) => ResizerLogicProps
        databaseTreeWidth: (databaseTreeDesiredSize: number | null, isDatabaseTreeCollapsed: boolean) => number
        databaseTreeResizerProps: (databaseTreeResizerProps: ResizerLogicProps) => ResizerLogicProps
    }
}
