// Generated by kea-typegen on Sun, 02 Aug 2026 21:38:48 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DateFilterState } from './webAnalyticsLogic'
import type { CompareFilter, InsightVizNode, NodeKind, PageURL, QueryLogTags, QuerySchema, TrendsQuery, WebAnalyticsPropertyFilters, WebStatsBreakdown } from '../../queries/schema/schema-general'
import type { SectionTile, TileId, TileVisualizationOption, WebAnalyticsTile } from './common'
import type { FeatureFlagsSet } from '../../lib/logic/featureFlagLogic'
import type { PageURLSearchResult } from './pageReportsLogic'
import type { InsightLogicProps } from '../../types'

export interface pageReportsLogicType extends Logic {
    actionCreators: {
        setDates: (
            dateFrom: string | null,
            dateTo: string | null
        ) => {
            type: 'set dates (scenes.web-analytics.pageReportsLogic)'
            payload: {
                dateFrom: string | null
                dateTo: string | null
            }
        }
        setPageUrl: (url: string | string[] | null) => {
            type: 'set page url (scenes.web-analytics.pageReportsLogic)'
            payload: {
                url: string | string[] | null
            }
        }
        setPageUrlSearchTerm: (searchTerm: string) => {
            type: 'set page url search term (scenes.web-analytics.pageReportsLogic)'
            payload: {
                searchTerm: string
            }
        }
        loadPages: (searchTerm?: string) => {
            type: 'load pages (scenes.web-analytics.pageReportsLogic)'
            payload: {
                searchTerm: string
            }
        }
        setTileVisualization: (
            tileId: TileId,
            visualization: TileVisualizationOption
        ) => {
            type: 'set tile visualization (scenes.web-analytics.pageReportsLogic)'
            payload: {
                tileId: TileId
                visualization: TileVisualizationOption
            }
        }
        loadPagesUrls: ({ searchTerm }: { searchTerm: string }) => {
            type: 'load pages urls (scenes.web-analytics.pageReportsLogic)'
            payload: {
                searchTerm: string
            }
        }
        loadPagesUrlsSuccess: (
            pagesUrls: PageURL[],
            payload?: {
                searchTerm: string
            }
        ) => {
            type: 'load pages urls success (scenes.web-analytics.pageReportsLogic)'
            payload: {
                pagesUrls: PageURL[]
                payload?: {
                    searchTerm: string
                }
            }
        }
        loadPagesUrlsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load pages urls failure (scenes.web-analytics.pageReportsLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'set dates (scenes.web-analytics.pageReportsLogic)': 'setDates'
        'set page url (scenes.web-analytics.pageReportsLogic)': 'setPageUrl'
        'set page url search term (scenes.web-analytics.pageReportsLogic)': 'setPageUrlSearchTerm'
        'load pages (scenes.web-analytics.pageReportsLogic)': 'loadPages'
        'set tile visualization (scenes.web-analytics.pageReportsLogic)': 'setTileVisualization'
        'load pages urls (scenes.web-analytics.pageReportsLogic)': 'loadPagesUrls'
        'load pages urls success (scenes.web-analytics.pageReportsLogic)': 'loadPagesUrlsSuccess'
        'load pages urls failure (scenes.web-analytics.pageReportsLogic)': 'loadPagesUrlsFailure'
    }
    actionTypes: {
        setDates: 'set dates (scenes.web-analytics.pageReportsLogic)'
        setPageUrl: 'set page url (scenes.web-analytics.pageReportsLogic)'
        setPageUrlSearchTerm: 'set page url search term (scenes.web-analytics.pageReportsLogic)'
        loadPages: 'load pages (scenes.web-analytics.pageReportsLogic)'
        setTileVisualization: 'set tile visualization (scenes.web-analytics.pageReportsLogic)'
        loadPagesUrls: 'load pages urls (scenes.web-analytics.pageReportsLogic)'
        loadPagesUrlsSuccess: 'load pages urls success (scenes.web-analytics.pageReportsLogic)'
        loadPagesUrlsFailure: 'load pages urls failure (scenes.web-analytics.pageReportsLogic)'
    }
    actions: {
        setDates: (dateFrom: string | null, dateTo: string | null) => void
        setPageUrl: (url: string | string[] | null) => void
        setPageUrlSearchTerm: (searchTerm: string) => void
        loadPages: (searchTerm?: string) => void
        setTileVisualization: (tileId: TileId, visualization: TileVisualizationOption) => void
        loadPagesUrls: ({ searchTerm }: { searchTerm: string }) => void
        loadPagesUrlsSuccess: (
            pagesUrls: PageURL[],
            payload?: {
                searchTerm: string
            }
        ) => void
        loadPagesUrlsFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        setDates: (dateFrom: string | null, dateTo: string | null) => Promise<any>
        setPageUrl: (url: string | string[] | null) => Promise<any>
        setPageUrlSearchTerm: (searchTerm: string) => Promise<any>
        loadPages: (searchTerm?: string) => Promise<any>
        setTileVisualization: (tileId: TileId, visualization: TileVisualizationOption) => Promise<any>
        loadPagesUrls: ({ searchTerm }: { searchTerm: string }) => Promise<any>
        loadPagesUrlsSuccess: (
            pagesUrls: PageURL[],
            payload?: {
                searchTerm: string
            }
        ) => Promise<any>
        loadPagesUrlsFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        pageUrl: string | null
        pageUrlSearchTerm: string
        isInitialLoad: boolean
        tileVisualizations: Record<TileId, TileVisualizationOption>
        pagesUrls: PageURLSearchResult[]
        pagesUrlsLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {
        setPageUrlSearchTerm: ((
            action: {
                type: 'set page url search term (scenes.web-analytics.pageReportsLogic)'
                payload: {
                    searchTerm: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setPageUrl: ((
            action: {
                type: 'set page url (scenes.web-analytics.pageReportsLogic)'
                payload: {
                    url: string | string[] | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadPages: ((
            action: {
                type: 'load pages (scenes.web-analytics.pageReportsLogic)'
                payload: {
                    searchTerm: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'web-analytics', 'pageReportsLogic']
    pathString: 'scenes.web-analytics.pageReportsLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        pageUrl: string | null
        pageUrlSearchTerm: string
        isInitialLoad: boolean
        tileVisualizations: Record<TileId, TileVisualizationOption>
        pagesUrls: PageURLSearchResult[]
        pagesUrlsLoading: boolean
    }
    reducers: {
        pageUrl: (state: string | null, action: any, fullState: any) => string | null
        pageUrlSearchTerm: (state: string, action: any, fullState: any) => string
        isInitialLoad: (state: boolean, action: any, fullState: any) => boolean
        tileVisualizations: (
            state: Record<TileId, TileVisualizationOption>,
            action: any,
            fullState: any
        ) => Record<TileId, TileVisualizationOption>
        pagesUrls: (state: PageURLSearchResult[], action: any, fullState: any) => PageURLSearchResult[]
        pagesUrlsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        pageUrl: string | null
        pageUrlSearchTerm: string
        isInitialLoad: boolean
        tileVisualizations: Record<TileId, TileVisualizationOption>
        pagesUrls: PageURLSearchResult[]
        pagesUrlsLoading: boolean
    }
    selectors: {
        pageUrl: (state: any, props?: any) => string | null
        pageUrlSearchTerm: (state: any, props?: any) => string
        isInitialLoad: (state: any, props?: any) => boolean
        tileVisualizations: (state: any, props?: any) => Record<TileId, TileVisualizationOption>
        pagesUrls: (state: any, props?: any) => PageURLSearchResult[]
        pagesUrlsLoading: (state: any, props?: any) => boolean
        dateFilter: (state: any, props?: any) => DateFilterState
        shouldFilterTestAccounts: (state: any, props?: any) => boolean
        compareFilter: (state: any, props?: any) => CompareFilter
        isPathCleaningEnabled: (state: any, props?: any) => boolean
        webAnalyticsFilters: (state: any, props?: any) => WebAnalyticsPropertyFilters
        webAnalyticsTiles: (state: any, props?: any) => WebAnalyticsTile[]
        featureFlags: (state: any, props?: any) => FeatureFlagsSet
        hasPageUrl: (state: any, props?: any) => boolean
        isLoading: (state: any, props?: any) => boolean
        stripQueryParams: (state: any, props?: any) => boolean
        queries: (
            state: any,
            props?: any
        ) =>
            | {
                  avgTimeOnPageTrendQuery: InsightVizNode<TrendsQuery> | undefined
                  browserQuery: QuerySchema | undefined
                  channelsQuery: QuerySchema | undefined
                  citiesQuery: QuerySchema | undefined
                  countriesQuery: QuerySchema | undefined
                  deviceTypeQuery: QuerySchema | undefined
                  entryPathsQuery: QuerySchema | undefined
                  exitPathsQuery: QuerySchema | undefined
                  languagesQuery: QuerySchema | undefined
                  osQuery: QuerySchema | undefined
                  outboundClicksQuery: QuerySchema | undefined
                  prevPathsQuery: {
                      embedded: boolean
                      full: boolean
                      kind: NodeKind
                      showActions: boolean
                      source: {
                          breakdownBy: WebStatsBreakdown
                          compareFilter: CompareFilter
                          dateRange: {
                              date_from: string | null
                              date_to: string | null
                          }
                          doPathCleaning: boolean
                          filterTestAccounts: boolean
                          kind: NodeKind
                          limit: number
                          properties: WebAnalyticsPropertyFilters
                          tags: QueryLogTags
                      }
                  }
                  referrersQuery: QuerySchema | undefined
                  regionsQuery: QuerySchema | undefined
                  timezonesQuery: QuerySchema | undefined
                  topEventsQuery: QuerySchema | undefined
                  utmCampaignQuery: QuerySchema | undefined
                  utmContentQuery: QuerySchema | undefined
                  utmMediumQuery: QuerySchema | undefined
                  utmSourceQuery: QuerySchema | undefined
                  utmTermQuery: QuerySchema | undefined
              }
            | {
                  avgTimeOnPageTrendQuery: undefined
                  browserQuery: undefined
                  channelsQuery: undefined
                  citiesQuery: undefined
                  countriesQuery: undefined
                  deviceTypeQuery: undefined
                  entryPathsQuery: undefined
                  exitPathsQuery: undefined
                  languagesQuery: undefined
                  osQuery: undefined
                  outboundClicksQuery: undefined
                  prevPathsQuery?: undefined
                  referrersQuery: undefined
                  regionsQuery: undefined
                  timezonesQuery: undefined
                  topEventsQuery: undefined
                  utmCampaignQuery: undefined
                  utmContentQuery: undefined
                  utmMediumQuery: undefined
                  utmSourceQuery: undefined
                  utmTermQuery: undefined
              }
        createInsightProps: (
            state: any,
            props?: any
        ) => (tileId: TileId, tabId?: string | undefined) => InsightLogicProps<QuerySchema>
        combinedMetricsQuery: (state: any, props?: any) => (dateFilter: DateFilterState) => InsightVizNode<TrendsQuery>
        tiles: (state: any, props?: any) => SectionTile[]
    }
    sharedListeners: {}
    values: {
        pageUrl: string | null
        pageUrlSearchTerm: string
        isInitialLoad: boolean
        tileVisualizations: Record<TileId, TileVisualizationOption>
        pagesUrls: PageURLSearchResult[]
        pagesUrlsLoading: boolean
        dateFilter: DateFilterState
        shouldFilterTestAccounts: boolean
        compareFilter: CompareFilter
        isPathCleaningEnabled: boolean
        webAnalyticsFilters: WebAnalyticsPropertyFilters
        webAnalyticsTiles: WebAnalyticsTile[]
        featureFlags: FeatureFlagsSet
        hasPageUrl: boolean
        isLoading: boolean
        stripQueryParams: boolean
        queries:
            | {
                  avgTimeOnPageTrendQuery: InsightVizNode<TrendsQuery> | undefined
                  browserQuery: QuerySchema | undefined
                  channelsQuery: QuerySchema | undefined
                  citiesQuery: QuerySchema | undefined
                  countriesQuery: QuerySchema | undefined
                  deviceTypeQuery: QuerySchema | undefined
                  entryPathsQuery: QuerySchema | undefined
                  exitPathsQuery: QuerySchema | undefined
                  languagesQuery: QuerySchema | undefined
                  osQuery: QuerySchema | undefined
                  outboundClicksQuery: QuerySchema | undefined
                  prevPathsQuery: {
                      embedded: boolean
                      full: boolean
                      kind: NodeKind
                      showActions: boolean
                      source: {
                          breakdownBy: WebStatsBreakdown
                          compareFilter: CompareFilter
                          dateRange: {
                              date_from: string | null
                              date_to: string | null
                          }
                          doPathCleaning: boolean
                          filterTestAccounts: boolean
                          kind: NodeKind
                          limit: number
                          properties: WebAnalyticsPropertyFilters
                          tags: QueryLogTags
                      }
                  }
                  referrersQuery: QuerySchema | undefined
                  regionsQuery: QuerySchema | undefined
                  timezonesQuery: QuerySchema | undefined
                  topEventsQuery: QuerySchema | undefined
                  utmCampaignQuery: QuerySchema | undefined
                  utmContentQuery: QuerySchema | undefined
                  utmMediumQuery: QuerySchema | undefined
                  utmSourceQuery: QuerySchema | undefined
                  utmTermQuery: QuerySchema | undefined
              }
            | {
                  avgTimeOnPageTrendQuery: undefined
                  browserQuery: undefined
                  channelsQuery: undefined
                  citiesQuery: undefined
                  countriesQuery: undefined
                  deviceTypeQuery: undefined
                  entryPathsQuery: undefined
                  exitPathsQuery: undefined
                  languagesQuery: undefined
                  osQuery: undefined
                  outboundClicksQuery: undefined
                  prevPathsQuery?: undefined
                  referrersQuery: undefined
                  regionsQuery: undefined
                  timezonesQuery: undefined
                  topEventsQuery: undefined
                  utmCampaignQuery: undefined
                  utmContentQuery: undefined
                  utmMediumQuery: undefined
                  utmSourceQuery: undefined
                  utmTermQuery: undefined
              }
        createInsightProps: (tileId: TileId, tabId?: string | undefined) => InsightLogicProps<QuerySchema>
        combinedMetricsQuery: (dateFilter: DateFilterState) => InsightVizNode<TrendsQuery>
        tiles: SectionTile[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        hasPageUrl: (pageUrl: string | null) => boolean
        isLoading: (pagesUrlsLoading: boolean, isInitialLoad: boolean) => boolean
        queries: (
            webAnalyticsTiles: WebAnalyticsTile[],
            pageUrl: string | null,
            stripQueryParams: boolean,
            dateFilter: import('/home/z/work/hanzo/insights/frontend/src/scenes/web-analytics/webAnalyticsLogic').DateFilterState,
            shouldFilterTestAccounts: boolean,
            compareFilter: CompareFilter,
            isPathCleaningEnabled: boolean
        ) =>
            | {
                  avgTimeOnPageTrendQuery: InsightVizNode<TrendsQuery> | undefined
                  browserQuery: QuerySchema | undefined
                  channelsQuery: QuerySchema | undefined
                  citiesQuery: QuerySchema | undefined
                  countriesQuery: QuerySchema | undefined
                  deviceTypeQuery: QuerySchema | undefined
                  entryPathsQuery: QuerySchema | undefined
                  exitPathsQuery: QuerySchema | undefined
                  languagesQuery: QuerySchema | undefined
                  osQuery: QuerySchema | undefined
                  outboundClicksQuery: QuerySchema | undefined
                  prevPathsQuery: {
                      embedded: boolean
                      full: boolean
                      kind: NodeKind
                      showActions: boolean
                      source: {
                          breakdownBy: WebStatsBreakdown
                          compareFilter: CompareFilter
                          dateRange: {
                              date_from: string | null
                              date_to: string | null
                          }
                          doPathCleaning: boolean
                          filterTestAccounts: boolean
                          kind: NodeKind
                          limit: number
                          properties: WebAnalyticsPropertyFilters
                          tags: QueryLogTags
                      }
                  }
                  referrersQuery: QuerySchema | undefined
                  regionsQuery: QuerySchema | undefined
                  timezonesQuery: QuerySchema | undefined
                  topEventsQuery: QuerySchema | undefined
                  utmCampaignQuery: QuerySchema | undefined
                  utmContentQuery: QuerySchema | undefined
                  utmMediumQuery: QuerySchema | undefined
                  utmSourceQuery: QuerySchema | undefined
                  utmTermQuery: QuerySchema | undefined
              }
            | {
                  avgTimeOnPageTrendQuery: undefined
                  browserQuery: undefined
                  channelsQuery: undefined
                  citiesQuery: undefined
                  countriesQuery: undefined
                  deviceTypeQuery: undefined
                  entryPathsQuery: undefined
                  exitPathsQuery: undefined
                  languagesQuery: undefined
                  osQuery: undefined
                  outboundClicksQuery: undefined
                  prevPathsQuery?: undefined
                  referrersQuery: undefined
                  regionsQuery: undefined
                  timezonesQuery: undefined
                  topEventsQuery: undefined
                  utmCampaignQuery: undefined
                  utmContentQuery: undefined
                  utmMediumQuery: undefined
                  utmSourceQuery: undefined
                  utmTermQuery: undefined
              }
        combinedMetricsQuery: (
            pageUrl: string | null,
            stripQueryParams: boolean,
            shouldFilterTestAccounts: boolean
        ) => (dateFilter: DateFilterState) => InsightVizNode<TrendsQuery>
        tiles: (
            queries:
                | {
                      avgTimeOnPageTrendQuery: InsightVizNode<TrendsQuery> | undefined
                      browserQuery: QuerySchema | undefined
                      channelsQuery: QuerySchema | undefined
                      citiesQuery: QuerySchema | undefined
                      countriesQuery: QuerySchema | undefined
                      deviceTypeQuery: QuerySchema | undefined
                      entryPathsQuery: QuerySchema | undefined
                      exitPathsQuery: QuerySchema | undefined
                      languagesQuery: QuerySchema | undefined
                      osQuery: QuerySchema | undefined
                      outboundClicksQuery: QuerySchema | undefined
                      prevPathsQuery: {
                          embedded: boolean
                          full: boolean
                          kind: NodeKind
                          showActions: boolean
                          source: {
                              breakdownBy: WebStatsBreakdown
                              compareFilter: CompareFilter
                              dateRange: {
                                  date_from: string | null
                                  date_to: string | null
                              }
                              doPathCleaning: boolean
                              filterTestAccounts: boolean
                              kind: NodeKind
                              limit: number
                              properties: WebAnalyticsPropertyFilters
                              tags: import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').QueryLogTags
                          }
                      }
                      referrersQuery: QuerySchema | undefined
                      regionsQuery: QuerySchema | undefined
                      timezonesQuery: QuerySchema | undefined
                      topEventsQuery: QuerySchema | undefined
                      utmCampaignQuery: QuerySchema | undefined
                      utmContentQuery: QuerySchema | undefined
                      utmMediumQuery: QuerySchema | undefined
                      utmSourceQuery: QuerySchema | undefined
                      utmTermQuery: QuerySchema | undefined
                  }
                | {
                      avgTimeOnPageTrendQuery: undefined
                      browserQuery: undefined
                      channelsQuery: undefined
                      citiesQuery: undefined
                      countriesQuery: undefined
                      deviceTypeQuery: undefined
                      entryPathsQuery: undefined
                      exitPathsQuery: undefined
                      languagesQuery: undefined
                      osQuery: undefined
                      outboundClicksQuery: undefined
                      prevPathsQuery?: undefined
                      referrersQuery: undefined
                      regionsQuery: undefined
                      timezonesQuery: undefined
                      topEventsQuery: undefined
                      utmCampaignQuery: undefined
                      utmContentQuery: undefined
                      utmMediumQuery: undefined
                      utmSourceQuery: undefined
                      utmTermQuery: undefined
                  },
            pageUrl: string | null,
            createInsightProps: (tileId: TileId, tabId?: string | undefined) => InsightLogicProps<QuerySchema>,
            combinedMetricsQuery: (
                dateFilter: import('/home/z/work/hanzo/insights/frontend/src/scenes/web-analytics/webAnalyticsLogic').DateFilterState
            ) => InsightVizNode<TrendsQuery>,
            dateFilter: import('/home/z/work/hanzo/insights/frontend/src/scenes/web-analytics/webAnalyticsLogic').DateFilterState,
            featureFlags: import('/home/z/work/hanzo/insights/frontend/src/lib/logic/featureFlagLogic').FeatureFlagsSet
        ) => SectionTile[]
    }
}
