// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:40 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { FeatureFlagsSet } from '../../../lib/logic/featureFlagLogic'
import type { Breadcrumb, SessionPropertyFilter } from '../../../types'
import type { DataTableNode, DateRange, SessionAttributionGroupBy } from '../../../queries/schema/schema-general'

export interface sessionAttributionExplorerLogicType extends Logic {
    actionCreators: {
        setProperties: (properties: SessionPropertyFilter[]) => {
            type: 'set properties (scenes.webAnalytics.sessionDebuggerLogic)'
            payload: {
                properties: SessionPropertyFilter[]
            }
        }
        setDateRange: (dateRange: DateRange | null) => {
            type: 'set date range (scenes.webAnalytics.sessionDebuggerLogic)'
            payload: {
                dateRange: DateRange | null
            }
        }
        setStateFromUrl: (state: { dateRange: DateRange | null; properties: SessionPropertyFilter[] }) => {
            type: 'set state from url (scenes.webAnalytics.sessionDebuggerLogic)'
            payload: {
                state: {
                    dateRange: DateRange | null
                    properties: SessionPropertyFilter[]
                }
            }
        }
        enableGroupBy: (groupBy: SessionAttributionGroupBy) => {
            type: 'enable group by (scenes.webAnalytics.sessionDebuggerLogic)'
            payload: {
                groupBy: SessionAttributionGroupBy
            }
        }
        disableGroupBy: (groupBy: SessionAttributionGroupBy) => {
            type: 'disable group by (scenes.webAnalytics.sessionDebuggerLogic)'
            payload: {
                groupBy: SessionAttributionGroupBy
            }
        }
    }
    actionKeys: {
        'set properties (scenes.webAnalytics.sessionDebuggerLogic)': 'setProperties'
        'set date range (scenes.webAnalytics.sessionDebuggerLogic)': 'setDateRange'
        'set state from url (scenes.webAnalytics.sessionDebuggerLogic)': 'setStateFromUrl'
        'enable group by (scenes.webAnalytics.sessionDebuggerLogic)': 'enableGroupBy'
        'disable group by (scenes.webAnalytics.sessionDebuggerLogic)': 'disableGroupBy'
    }
    actionTypes: {
        setProperties: 'set properties (scenes.webAnalytics.sessionDebuggerLogic)'
        setDateRange: 'set date range (scenes.webAnalytics.sessionDebuggerLogic)'
        setStateFromUrl: 'set state from url (scenes.webAnalytics.sessionDebuggerLogic)'
        enableGroupBy: 'enable group by (scenes.webAnalytics.sessionDebuggerLogic)'
        disableGroupBy: 'disable group by (scenes.webAnalytics.sessionDebuggerLogic)'
    }
    actions: {
        setProperties: (properties: SessionPropertyFilter[]) => void
        setDateRange: (dateRange: DateRange | null) => void
        setStateFromUrl: (state: { dateRange: DateRange | null; properties: SessionPropertyFilter[] }) => void
        enableGroupBy: (groupBy: SessionAttributionGroupBy) => void
        disableGroupBy: (groupBy: SessionAttributionGroupBy) => void
    }
    asyncActions: {
        setProperties: (properties: SessionPropertyFilter[]) => Promise<any>
        setDateRange: (dateRange: DateRange | null) => Promise<any>
        setStateFromUrl: (state: { dateRange: DateRange | null; properties: SessionPropertyFilter[] }) => Promise<any>
        enableGroupBy: (groupBy: SessionAttributionGroupBy) => Promise<any>
        disableGroupBy: (groupBy: SessionAttributionGroupBy) => Promise<any>
    }
    defaults: {
        properties: SessionPropertyFilter[]
        dateRange: DateRange | null
        groupBy: SessionAttributionGroupBy[]
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'webAnalytics', 'sessionDebuggerLogic']
    pathString: 'scenes.webAnalytics.sessionDebuggerLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        properties: SessionPropertyFilter[]
        dateRange: DateRange | null
        groupBy: SessionAttributionGroupBy[]
    }
    reducers: {
        properties: (state: SessionPropertyFilter[], action: any, fullState: any) => SessionPropertyFilter[]
        dateRange: (state: DateRange | null, action: any, fullState: any) => DateRange | null
        groupBy: (state: SessionAttributionGroupBy[], action: any, fullState: any) => SessionAttributionGroupBy[]
    }
    selector: (state: any) => {
        properties: SessionPropertyFilter[]
        dateRange: DateRange | null
        groupBy: SessionAttributionGroupBy[]
    }
    selectors: {
        properties: (state: any, props?: any) => SessionPropertyFilter[]
        dateRange: (state: any, props?: any) => DateRange | null
        groupBy: (state: any, props?: any) => SessionAttributionGroupBy[]
        featureFlags: (state: any, props?: any) => FeatureFlagsSet
        query: (state: any, props?: any) => DataTableNode
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
    }
    sharedListeners: {}
    values: {
        properties: SessionPropertyFilter[]
        dateRange: DateRange | null
        groupBy: SessionAttributionGroupBy[]
        featureFlags: FeatureFlagsSet
        query: DataTableNode
        breadcrumbs: Breadcrumb[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        query: (
            properties: SessionPropertyFilter[],
            dateRange: DateRange | null,
            groupBy: SessionAttributionGroupBy[]
        ) => DataTableNode
    }
}
