# Generated by Django 4.2.29 on 2026-07-16 07:36

from django.db import migrations, models
import django.utils.timezone
import insights.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopRecording',
            fields=[
                ('id', models.UUIDField(default=insights.models.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sdk_upload_id', models.UUIDField(db_index=True, unique=True)),
                ('recall_recording_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('desktop_audio', 'Desktop audio'), ('slack', 'Slack huddle')], max_length=20)),
                ('meeting_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('participants', models.JSONField(default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='recording', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_segments', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('extracted_tasks', models.JSONField(default=list)),
                ('tasks_generated_at', models.DateTimeField(blank=True, null=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insights_desktop_recording',
                'ordering': ['-started_at'],
            },
        ),
    ]
