# Generated by Django 4.2.29 on 2026-07-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desktop_recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoprecording',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desktoprecording',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_recordings', to='insights.team'),
        ),
        migrations.AddIndex(
            model_name='desktoprecording',
            index=models.Index(fields=['team', '-started_at'], name='insights_de_team_id_c178d9_idx'),
        ),
        migrations.AddIndex(
            model_name='desktoprecording',
            index=models.Index(fields=['created_by', '-started_at'], name='insights_de_created_ecf55d_idx'),
        ),
        migrations.AddIndex(
            model_name='desktoprecording',
            index=models.Index(fields=['status'], name='insights_de_status_0d28b0_idx'),
        ),
    ]
