import { MakeLogicType, connect, kea, path, selectors } from 'kea'

import { preflightLogic } from 'lib/logic/preflightLogic'
import { userPreferencesLogic } from 'lib/logic/userPreferencesLogic'

import { CLOUD_INTERNAL_POSTFN_PROPERTY_KEYS, PROPERTY_KEYS } from '~/taxonomy/taxonomy'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface eventPropertyFilteringLogicValues {
    isCloudOrDev: boolean | undefined // preflightLogic
    hideInsightsPropertiesInTable: boolean // userPreferencesLogic
    filterProperties: (props: Record<string, any>) => Record<string, any>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface eventPropertyFilteringLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        filterProperties: (
            hideInsightsPropertiesInTable: boolean,
            isCloudOrDev: boolean | undefined
        ) => (props: Record<string, any>) => Record<string, any>
    }
}

export type eventPropertyFilteringLogicType = MakeLogicType<
    eventPropertyFilteringLogicValues,
    {},
    Record<string, any>,
    eventPropertyFilteringLogicMeta
>

export const eventPropertyFilteringLogic = kea<eventPropertyFilteringLogicType>([
    path(['lib', 'components', 'EventPropertyTabs', 'eventPropertyFilteringLogic']),
    connect(() => ({
        values: [userPreferencesLogic, ['hideInsightsPropertiesInTable'], preflightLogic, ['isCloudOrDev']],
    })),
    selectors({
        filterProperties: [
            (s) => [s.hideInsightsPropertiesInTable, s.isCloudOrDev],
            (hideInsightsPropertiesInTable: boolean, isCloudOrDev: boolean | undefined) => {
                return (props: Record<string, any>) => {
                    if (!hideInsightsPropertiesInTable) {
                        return props
                    }

                    return Object.fromEntries(
                        Object.entries(props).filter(([key]) => {
                            const isInsightsProperty = key.startsWith('$') && PROPERTY_KEYS.includes(key)
                            const isNonDollarInsightsProperty =
                                isCloudOrDev && CLOUD_INTERNAL_POSTFN_PROPERTY_KEYS.includes(key)
                            const isSystemProperty = props[key]?.system
                            return !isInsightsProperty && !isNonDollarInsightsProperty && !isSystemProperty
                        })
                    )
                }
            },
        ],
    }),
])
