// Generated by kea-typegen on Sun, 02 Aug 2026 21:37:51 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DuckSqlRunMode, InsightsqlSqlRunMode, NotebookNodeLogicProps, PythonRunMode } from './notebookNodeLogic'
import type { NotebookEditor, NotebookNodeAction, NotebookNodeAttributes, NotebookNodeResource, NotebookNodeSettings, NotebookNodeSettingsPlacement, NotebookNodeType, NotebookType } from '../types'
import type { MenuItems } from '../../../../@hanzo/elements/src/index'
import type { EditorRange, JSONContent, RichContentNode } from '../../../lib/components/RichContentEditor/types'
import type { NotebookNodeMessages, NotebookNodeMessagesListeners } from './messaging/notebook-node-messages'
import type { NotebookDataframeResult, PythonExecutionResult } from './pythonExecution'
import type { Range } from '../../../../../node_modules/.pnpm/@tiptap+core@3.19.0_@tiptap+pm@3.19.0/node_modules/@tiptap/core/dist/index'
import type { CommentType } from '../../../types'
import type { NotebookKernelInfo } from '../Notebook/notebookKernelInfoLogic'
import type { DuckSqlNodeSummary, InsightsqlSqlNodeSummary, NotebookDependencyGraph, NotebookDependencyUsage, PythonNodeSummary } from './notebookNodeContent'
import type { BuiltLogic } from '../../../../../node_modules/.pnpm/kea@4.0.0-pre.3_react@18.3.1/node_modules/kea/lib/index'
import type { notebookLogicType } from '../Notebook/notebookLogicType'

export interface notebookNodeLogicType extends Logic {
    actionCreators: {
        setExpanded: (expanded: boolean) => {
            type: 'set expanded (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                expanded: boolean
            }
        }
        setResizeable: (resizeable: boolean) => {
            type: 'set resizeable (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                resizeable: boolean
            }
        }
        setActions: (actions: (NotebookNodeAction | undefined)[]) => {
            type: 'set actions (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                actions: (NotebookNodeAction | undefined)[]
            }
        }
        setMenuItems: (menuItems: MenuItems | null) => {
            type: 'set menu items (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                menuItems: MenuItems | null
            }
        }
        insertAfter: (content: JSONContent) => {
            type: 'insert after (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                content: JSONContent
            }
        }
        insertAfterLastNodeOfType: (
            nodeType: string,
            content: JSONContent
        ) => {
            type: 'insert after last node of type (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                content: JSONContent
                nodeType: string
            }
        }
        updateAttributes: (attributes: Partial<NotebookNodeAttributes<any>>) => {
            type: 'update attributes (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                attributes: Partial<any>
            }
        }
        insertOrSelectNextLine: () => {
            type: 'insert or select next line (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        setPreviousNode: (node: RichContentNode | null) => {
            type: 'set previous node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                node: RichContentNode | null
            }
        }
        setNextNode: (node: RichContentNode | null) => {
            type: 'set next node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                node: RichContentNode | null
            }
        }
        deleteNode: () => {
            type: 'delete node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        selectNode: (scroll?: boolean) => {
            type: 'select node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                scroll: boolean | undefined
            }
        }
        toggleEditing: (visible?: boolean) => {
            type: 'toggle editing (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                visible: boolean | undefined
            }
        }
        scrollIntoView: () => {
            type: 'scroll into view (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        initializeNode: () => {
            type: 'initialize node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        setMessageListeners: (listeners: NotebookNodeMessagesListeners) => {
            type: 'set message listeners (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                listeners: NotebookNodeMessagesListeners
            }
        }
        setTitlePlaceholder: (titlePlaceholder: string) => {
            type: 'set title placeholder (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                titlePlaceholder: string
            }
        }
        setRef: (ref: HTMLElement | null) => {
            type: 'set ref (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                ref: HTMLElement | null
            }
        }
        toggleEditingTitle: (editing?: boolean) => {
            type: 'toggle editing title (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                editing: boolean | undefined
            }
        }
        copyToClipboard: () => {
            type: 'copy to clipboard (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        convertToBacklink: (href: string) => {
            type: 'convert to backlink (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                href: string
            }
        }
        navigateToNode: (nodeId: string) => {
            type: 'navigate to node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                nodeId: string
            }
        }
        runPythonNode: (payload: { code: string }) => {
            type: 'run python node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                code: string
            }
        }
        runPythonNodeWithMode: (payload: { mode: PythonRunMode }) => {
            type: 'run python node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                mode: PythonRunMode
            }
        }
        setPythonRunLoading: (loading: boolean) => {
            type: 'set python run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                loading: boolean
            }
        }
        setPythonRunQueued: (queued: boolean) => {
            type: 'set python run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                queued: boolean
            }
        }
        runDuckSqlNode: () => {
            type: 'run duck sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        runDuckSqlNodeWithMode: (payload: { mode: DuckSqlRunMode }) => {
            type: 'run duck sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                mode: DuckSqlRunMode
            }
        }
        setDuckSqlRunLoading: (loading: boolean) => {
            type: 'set duck sql run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                loading: boolean
            }
        }
        setDuckSqlRunQueued: (queued: boolean) => {
            type: 'set duck sql run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                queued: boolean
            }
        }
        runInsightsqlSqlNode: () => {
            type: 'run insightsql sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        runInsightsqlSqlNodeWithMode: (payload: { mode: InsightsqlSqlRunMode }) => {
            type: 'run insightsql sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                mode: InsightsqlSqlRunMode
            }
        }
        setInsightsqlSqlRunLoading: (loading: boolean) => {
            type: 'set insightsql sql run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                loading: boolean
            }
        }
        setInsightsqlSqlRunQueued: (queued: boolean) => {
            type: 'set insightsql sql run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                queued: boolean
            }
        }
        setDataframeVariableName: (
            variableName: string | null,
            initialResult?: NotebookDataframeResult | null
        ) => {
            type: 'set dataframe variable name (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                initialResult: NotebookDataframeResult | null | undefined
                variableName: string | null
            }
        }
        setDataframePage: (page: number) => {
            type: 'set dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                page: number
            }
        }
        setDataframePageSize: (pageSize: number) => {
            type: 'set dataframe page size (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                pageSize: number
            }
        }
        loadDataframePage: (payload: { pageSize?: number; variableName: string }) => {
            type: 'load dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                pageSize?: number | undefined
                variableName: string
            }
        }
        setDataframeResult: (result: NotebookDataframeResult | null) => {
            type: 'set dataframe result (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                result: NotebookDataframeResult | null
            }
        }
        setDataframeLoading: (loading: boolean) => {
            type: 'set dataframe loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                loading: boolean
            }
        }
        setDataframeError: (error: string | null) => {
            type: 'set dataframe error (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                error: string | null
            }
        }
        resetDataframeResults: () => {
            type: 'reset dataframe results (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        onUpdateEditor: () => {
            type: 'on update editor (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                value: true
            }
        }
        setTextSelection: (selection: number | EditorRange) => {
            type: 'set text selection (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
            payload: {
                selection: number | Range
            }
        }
    }
    actionKeys: {
        'set expanded (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setExpanded'
        'set resizeable (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setResizeable'
        'set actions (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setActions'
        'set menu items (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setMenuItems'
        'insert after (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'insertAfter'
        'insert after last node of type (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'insertAfterLastNodeOfType'
        'update attributes (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'updateAttributes'
        'insert or select next line (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'insertOrSelectNextLine'
        'set previous node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setPreviousNode'
        'set next node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setNextNode'
        'delete node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'deleteNode'
        'select node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'selectNode'
        'toggle editing (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'toggleEditing'
        'scroll into view (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'scrollIntoView'
        'initialize node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'initializeNode'
        'set message listeners (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setMessageListeners'
        'set title placeholder (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setTitlePlaceholder'
        'set ref (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setRef'
        'toggle editing title (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'toggleEditingTitle'
        'copy to clipboard (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'copyToClipboard'
        'convert to backlink (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'convertToBacklink'
        'navigate to node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'navigateToNode'
        'run python node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'runPythonNode'
        'run python node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'runPythonNodeWithMode'
        'set python run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setPythonRunLoading'
        'set python run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setPythonRunQueued'
        'run duck sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'runDuckSqlNode'
        'run duck sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'runDuckSqlNodeWithMode'
        'set duck sql run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDuckSqlRunLoading'
        'set duck sql run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDuckSqlRunQueued'
        'run insightsql sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'runInsightsqlSqlNode'
        'run insightsql sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'runInsightsqlSqlNodeWithMode'
        'set insightsql sql run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setInsightsqlSqlRunLoading'
        'set insightsql sql run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setInsightsqlSqlRunQueued'
        'set dataframe variable name (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDataframeVariableName'
        'set dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDataframePage'
        'set dataframe page size (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDataframePageSize'
        'load dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'loadDataframePage'
        'set dataframe result (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDataframeResult'
        'set dataframe loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDataframeLoading'
        'set dataframe error (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setDataframeError'
        'reset dataframe results (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'resetDataframeResults'
        'on update editor (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'onUpdateEditor'
        'set text selection (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)': 'setTextSelection'
    }
    actionTypes: {
        setExpanded: 'set expanded (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setResizeable: 'set resizeable (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setActions: 'set actions (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setMenuItems: 'set menu items (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        insertAfter: 'insert after (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        insertAfterLastNodeOfType: 'insert after last node of type (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        updateAttributes: 'update attributes (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        insertOrSelectNextLine: 'insert or select next line (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setPreviousNode: 'set previous node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setNextNode: 'set next node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        deleteNode: 'delete node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        selectNode: 'select node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        toggleEditing: 'toggle editing (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        scrollIntoView: 'scroll into view (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        initializeNode: 'initialize node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setMessageListeners: 'set message listeners (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setTitlePlaceholder: 'set title placeholder (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setRef: 'set ref (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        toggleEditingTitle: 'toggle editing title (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        copyToClipboard: 'copy to clipboard (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        convertToBacklink: 'convert to backlink (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        navigateToNode: 'navigate to node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        runPythonNode: 'run python node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        runPythonNodeWithMode: 'run python node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setPythonRunLoading: 'set python run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setPythonRunQueued: 'set python run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        runDuckSqlNode: 'run duck sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        runDuckSqlNodeWithMode: 'run duck sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDuckSqlRunLoading: 'set duck sql run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDuckSqlRunQueued: 'set duck sql run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        runInsightsqlSqlNode: 'run insightsql sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        runInsightsqlSqlNodeWithMode: 'run insightsql sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setInsightsqlSqlRunLoading: 'set insightsql sql run loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setInsightsqlSqlRunQueued: 'set insightsql sql run queued (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDataframeVariableName: 'set dataframe variable name (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDataframePage: 'set dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDataframePageSize: 'set dataframe page size (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        loadDataframePage: 'load dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDataframeResult: 'set dataframe result (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDataframeLoading: 'set dataframe loading (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setDataframeError: 'set dataframe error (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        resetDataframeResults: 'reset dataframe results (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        onUpdateEditor: 'on update editor (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
        setTextSelection: 'set text selection (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
    }
    actions: {
        setExpanded: (expanded: boolean) => void
        setResizeable: (resizeable: boolean) => void
        setActions: (actions: (NotebookNodeAction | undefined)[]) => void
        setMenuItems: (menuItems: MenuItems | null) => void
        insertAfter: (content: JSONContent) => void
        insertAfterLastNodeOfType: (nodeType: string, content: JSONContent) => void
        updateAttributes: (attributes: Partial<NotebookNodeAttributes<any>>) => void
        insertOrSelectNextLine: () => void
        setPreviousNode: (node: RichContentNode | null) => void
        setNextNode: (node: RichContentNode | null) => void
        deleteNode: () => void
        selectNode: (scroll?: boolean) => void
        toggleEditing: (visible?: boolean) => void
        scrollIntoView: () => void
        initializeNode: () => void
        setMessageListeners: (listeners: NotebookNodeMessagesListeners) => void
        setTitlePlaceholder: (titlePlaceholder: string) => void
        setRef: (ref: HTMLElement | null) => void
        toggleEditingTitle: (editing?: boolean) => void
        copyToClipboard: () => void
        convertToBacklink: (href: string) => void
        navigateToNode: (nodeId: string) => void
        runPythonNode: (payload: { code: string }) => void
        runPythonNodeWithMode: (payload: { mode: PythonRunMode }) => void
        setPythonRunLoading: (loading: boolean) => void
        setPythonRunQueued: (queued: boolean) => void
        runDuckSqlNode: () => void
        runDuckSqlNodeWithMode: (payload: { mode: DuckSqlRunMode }) => void
        setDuckSqlRunLoading: (loading: boolean) => void
        setDuckSqlRunQueued: (queued: boolean) => void
        runInsightsqlSqlNode: () => void
        runInsightsqlSqlNodeWithMode: (payload: { mode: InsightsqlSqlRunMode }) => void
        setInsightsqlSqlRunLoading: (loading: boolean) => void
        setInsightsqlSqlRunQueued: (queued: boolean) => void
        setDataframeVariableName: (variableName: string | null, initialResult?: NotebookDataframeResult | null) => void
        setDataframePage: (page: number) => void
        setDataframePageSize: (pageSize: number) => void
        loadDataframePage: (payload: { pageSize?: number; variableName: string }) => void
        setDataframeResult: (result: NotebookDataframeResult | null) => void
        setDataframeLoading: (loading: boolean) => void
        setDataframeError: (error: string | null) => void
        resetDataframeResults: () => void
        onUpdateEditor: () => void
        setTextSelection: (selection: number | EditorRange) => void
    }
    asyncActions: {
        setExpanded: (expanded: boolean) => Promise<any>
        setResizeable: (resizeable: boolean) => Promise<any>
        setActions: (actions: (NotebookNodeAction | undefined)[]) => Promise<any>
        setMenuItems: (menuItems: MenuItems | null) => Promise<any>
        insertAfter: (content: JSONContent) => Promise<any>
        insertAfterLastNodeOfType: (nodeType: string, content: JSONContent) => Promise<any>
        updateAttributes: (attributes: Partial<NotebookNodeAttributes<any>>) => Promise<any>
        insertOrSelectNextLine: () => Promise<any>
        setPreviousNode: (node: RichContentNode | null) => Promise<any>
        setNextNode: (node: RichContentNode | null) => Promise<any>
        deleteNode: () => Promise<any>
        selectNode: (scroll?: boolean) => Promise<any>
        toggleEditing: (visible?: boolean) => Promise<any>
        scrollIntoView: () => Promise<any>
        initializeNode: () => Promise<any>
        setMessageListeners: (listeners: NotebookNodeMessagesListeners) => Promise<any>
        setTitlePlaceholder: (titlePlaceholder: string) => Promise<any>
        setRef: (ref: HTMLElement | null) => Promise<any>
        toggleEditingTitle: (editing?: boolean) => Promise<any>
        copyToClipboard: () => Promise<any>
        convertToBacklink: (href: string) => Promise<any>
        navigateToNode: (nodeId: string) => Promise<any>
        runPythonNode: (payload: { code: string }) => Promise<any>
        runPythonNodeWithMode: (payload: { mode: PythonRunMode }) => Promise<any>
        setPythonRunLoading: (loading: boolean) => Promise<any>
        setPythonRunQueued: (queued: boolean) => Promise<any>
        runDuckSqlNode: () => Promise<any>
        runDuckSqlNodeWithMode: (payload: { mode: DuckSqlRunMode }) => Promise<any>
        setDuckSqlRunLoading: (loading: boolean) => Promise<any>
        setDuckSqlRunQueued: (queued: boolean) => Promise<any>
        runInsightsqlSqlNode: () => Promise<any>
        runInsightsqlSqlNodeWithMode: (payload: { mode: InsightsqlSqlRunMode }) => Promise<any>
        setInsightsqlSqlRunLoading: (loading: boolean) => Promise<any>
        setInsightsqlSqlRunQueued: (queued: boolean) => Promise<any>
        setDataframeVariableName: (
            variableName: string | null,
            initialResult?: NotebookDataframeResult | null
        ) => Promise<any>
        setDataframePage: (page: number) => Promise<any>
        setDataframePageSize: (pageSize: number) => Promise<any>
        loadDataframePage: (payload: { pageSize?: number; variableName: string }) => Promise<any>
        setDataframeResult: (result: NotebookDataframeResult | null) => Promise<any>
        setDataframeLoading: (loading: boolean) => Promise<any>
        setDataframeError: (error: string | null) => Promise<any>
        resetDataframeResults: () => Promise<any>
        onUpdateEditor: () => Promise<any>
        setTextSelection: (selection: number | EditorRange) => Promise<any>
    }
    defaults: {
        ref: HTMLElement | null
        expanded: boolean
        resizeable: boolean
        previousNode: RichContentNode | null
        nextNode: RichContentNode | null
        actions: NotebookNodeAction[]
        customMenuItems: MenuItems | null
        messageListeners: NotebookNodeMessagesListeners
        titlePlaceholder: string
        isEditingTitle: boolean
        pythonRunLoading: boolean
        pythonRunQueued: boolean
        duckSqlRunLoading: boolean
        duckSqlRunQueued: boolean
        insightsqlSqlRunLoading: boolean
        insightsqlSqlRunQueued: boolean
        dataframeVariableName: string | null
        dataframePage: number
        dataframePageSize: number
        dataframeResult: NotebookDataframeResult | null
        dataframeLoading: boolean
        dataframeError: string | null
    }
    events: {}
    key: any
    listeners: {
        onUpdateEditor: ((
            action: {
                type: 'on update editor (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        insertAfter: ((
            action: {
                type: 'insert after (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    content: JSONContent
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        deleteNode: ((
            action: {
                type: 'delete node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        selectNode: ((
            action: {
                type: 'select node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    scroll: boolean | undefined
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        navigateToNode: ((
            action: {
                type: 'navigate to node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    nodeId: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        scrollIntoView: ((
            action: {
                type: 'scroll into view (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        insertAfterLastNodeOfType: ((
            action: {
                type: 'insert after last node of type (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    content: JSONContent
                    nodeType: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        insertOrSelectNextLine: ((
            action: {
                type: 'insert or select next line (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setExpanded: ((
            action: {
                type: 'set expanded (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    expanded: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        updateAttributes: ((
            action: {
                type: 'update attributes (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    attributes: Partial<any>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        toggleEditing: ((
            action: {
                type: 'toggle editing (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    visible: boolean | undefined
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        initializeNode: ((
            action: {
                type: 'initialize node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        copyToClipboard: ((
            action: {
                type: 'copy to clipboard (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        convertToBacklink: ((
            action: {
                type: 'convert to backlink (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    href: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        runPythonNode: ((
            action: {
                type: 'run python node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    code: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        runDuckSqlNode: ((
            action: {
                type: 'run duck sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        runDuckSqlNodeWithMode: ((
            action: {
                type: 'run duck sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    mode: DuckSqlRunMode
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        runInsightsqlSqlNode: ((
            action: {
                type: 'run insightsql sql node (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        runInsightsqlSqlNodeWithMode: ((
            action: {
                type: 'run insightsql sql node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    mode: InsightsqlSqlRunMode
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        runPythonNodeWithMode: ((
            action: {
                type: 'run python node with mode (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    mode: PythonRunMode
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setDataframeVariableName: ((
            action: {
                type: 'set dataframe variable name (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    initialResult: NotebookDataframeResult | null | undefined
                    variableName: string | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setDataframePage: ((
            action: {
                type: 'set dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    page: number
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setDataframePageSize: ((
            action: {
                type: 'set dataframe page size (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    pageSize: number
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadDataframePage: ((
            action: {
                type: 'load dataframe page (scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*)'
                payload: {
                    pageSize?: number | undefined
                    variableName: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'notebooks', 'Notebook', 'Nodes', 'notebookNodeLogic', '*']
    pathString: 'scenes.notebooks.Notebook.Nodes.notebookNodeLogic.*'
    props: NotebookNodeLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        ref: HTMLElement | null
        expanded: boolean
        resizeable: boolean
        previousNode: RichContentNode | null
        nextNode: RichContentNode | null
        actions: NotebookNodeAction[]
        customMenuItems: MenuItems | null
        messageListeners: NotebookNodeMessagesListeners
        titlePlaceholder: string
        isEditingTitle: boolean
        pythonRunLoading: boolean
        pythonRunQueued: boolean
        duckSqlRunLoading: boolean
        duckSqlRunQueued: boolean
        insightsqlSqlRunLoading: boolean
        insightsqlSqlRunQueued: boolean
        dataframeVariableName: string | null
        dataframePage: number
        dataframePageSize: number
        dataframeResult: NotebookDataframeResult | null
        dataframeLoading: boolean
        dataframeError: string | null
    }
    reducers: {
        ref: (state: HTMLElement | null, action: any, fullState: any) => HTMLElement | null
        expanded: (state: boolean, action: any, fullState: any) => boolean
        resizeable: (state: boolean, action: any, fullState: any) => boolean
        previousNode: (state: RichContentNode | null, action: any, fullState: any) => RichContentNode | null
        nextNode: (state: RichContentNode | null, action: any, fullState: any) => RichContentNode | null
        actions: (state: NotebookNodeAction[], action: any, fullState: any) => NotebookNodeAction[]
        customMenuItems: (state: MenuItems | null, action: any, fullState: any) => MenuItems | null
        messageListeners: (
            state: NotebookNodeMessagesListeners,
            action: any,
            fullState: any
        ) => NotebookNodeMessagesListeners
        titlePlaceholder: (state: string, action: any, fullState: any) => string
        isEditingTitle: (state: boolean, action: any, fullState: any) => boolean
        pythonRunLoading: (state: boolean, action: any, fullState: any) => boolean
        pythonRunQueued: (state: boolean, action: any, fullState: any) => boolean
        duckSqlRunLoading: (state: boolean, action: any, fullState: any) => boolean
        duckSqlRunQueued: (state: boolean, action: any, fullState: any) => boolean
        insightsqlSqlRunLoading: (state: boolean, action: any, fullState: any) => boolean
        insightsqlSqlRunQueued: (state: boolean, action: any, fullState: any) => boolean
        dataframeVariableName: (state: string | null, action: any, fullState: any) => string | null
        dataframePage: (state: number, action: any, fullState: any) => number
        dataframePageSize: (state: number, action: any, fullState: any) => number
        dataframeResult: (
            state: NotebookDataframeResult | null,
            action: any,
            fullState: any
        ) => NotebookDataframeResult | null
        dataframeLoading: (state: boolean, action: any, fullState: any) => boolean
        dataframeError: (state: string | null, action: any, fullState: any) => string | null
    }
    selector: (state: any) => {
        ref: HTMLElement | null
        expanded: boolean
        resizeable: boolean
        previousNode: RichContentNode | null
        nextNode: RichContentNode | null
        actions: NotebookNodeAction[]
        customMenuItems: MenuItems | null
        messageListeners: NotebookNodeMessagesListeners
        titlePlaceholder: string
        isEditingTitle: boolean
        pythonRunLoading: boolean
        pythonRunQueued: boolean
        duckSqlRunLoading: boolean
        duckSqlRunQueued: boolean
        insightsqlSqlRunLoading: boolean
        insightsqlSqlRunQueued: boolean
        dataframeVariableName: string | null
        dataframePage: number
        dataframePageSize: number
        dataframeResult: NotebookDataframeResult | null
        dataframeLoading: boolean
        dataframeError: string | null
    }
    selectors: {
        ref: (state: any, props?: any) => HTMLElement | null
        expanded: (state: any, props?: any) => boolean
        resizeable: (state: any, props?: any) => boolean
        previousNode: (state: any, props?: any) => RichContentNode | null
        nextNode: (state: any, props?: any) => RichContentNode | null
        actions: (state: any, props?: any) => NotebookNodeAction[]
        customMenuItems: (state: any, props?: any) => MenuItems | null
        messageListeners: (state: any, props?: any) => NotebookNodeMessagesListeners
        titlePlaceholder: (state: any, props?: any) => string
        isEditingTitle: (state: any, props?: any) => boolean
        pythonRunLoading: (state: any, props?: any) => boolean
        pythonRunQueued: (state: any, props?: any) => boolean
        duckSqlRunLoading: (state: any, props?: any) => boolean
        duckSqlRunQueued: (state: any, props?: any) => boolean
        insightsqlSqlRunLoading: (state: any, props?: any) => boolean
        insightsqlSqlRunQueued: (state: any, props?: any) => boolean
        dataframeVariableName: (state: any, props?: any) => string | null
        dataframePage: (state: any, props?: any) => number
        dataframePageSize: (state: any, props?: any) => number
        dataframeResult: (state: any, props?: any) => NotebookDataframeResult | null
        dataframeLoading: (state: any, props?: any) => boolean
        dataframeError: (state: any, props?: any) => string | null
        editor: (state: any, props?: any) => NotebookEditor | null
        notebook: (state: any, props?: any) => NotebookType | null
        comments: (state: any, props?: any) => CommentType[] | null
        kernelInfo: (state: any, props?: any) => NotebookKernelInfo | null
        pythonNodeSummaries: (state: any, props?: any) => PythonNodeSummary[]
        duckSqlNodeSummaries: (state: any, props?: any) => DuckSqlNodeSummary[]
        insightsqlSqlNodeSummaries: (state: any, props?: any) => InsightsqlSqlNodeSummary[]
        dependencyGraph: (state: any, props?: any) => NotebookDependencyGraph
        isEditable: (state: any, props?: any) => boolean
        notebookLogic: (state: any, props?: any) => BuiltLogic<notebookLogicType>
        nodeAttributes: (state: any, props?: any) => NotebookNodeAttributes<any>
        nodeId: (state: any, props?: any) => string
        nodeType: (state: any, props?: any) => NotebookNodeType
        Settings: (state: any, props?: any) => NotebookNodeSettings | null
        settingsPlacement: (state: any, props?: any) => NotebookNodeSettingsPlacement
        title: (state: any, props?: any) => any
        children: (state: any, props?: any) => NotebookNodeResource[]
        exportedGlobals: (
            state: any,
            props?: any
        ) => {
            name: string
            type: string
        }[]
        pythonExecution: (state: any, props?: any) => PythonExecutionResult | null
        displayedGlobals: (
            state: any,
            props?: any
        ) => {
            insightsqlQuery?: string
            name: string
            type: string
        }[]
        pythonNodeIndex: (state: any, props?: any) => number
        duckSqlNodeIndex: (state: any, props?: any) => number
        duckSqlReturnVariable: (state: any, props?: any) => string
        insightsqlSqlNodeIndex: (state: any, props?: any) => number
        insightsqlSqlReturnVariable: (state: any, props?: any) => string
        dataframeRowCount: (state: any, props?: any) => number
        duckSqlTablesUsed: (state: any, props?: any) => string[]
        duckSqlUpstreamTableSources: (state: any, props?: any) => Record<string, NotebookDependencyUsage>
        duckSqlReturnVariableUsage: (state: any, props?: any) => NotebookDependencyUsage[]
        insightsqlReturnVariableUsage: (state: any, props?: any) => NotebookDependencyUsage[]
        usageByVariable: (state: any, props?: any) => Record<string, NotebookDependencyUsage[]>
        sendMessage: (
            state: any,
            props?: any
        ) => <T extends keyof NotebookNodeMessages>(message: T, payload: NotebookNodeMessages[T]) => boolean
        sourceComment: (state: any, props?: any) => CommentType | null | undefined
    }
    sharedListeners: {}
    values: {
        ref: HTMLElement | null
        expanded: boolean
        resizeable: boolean
        previousNode: RichContentNode | null
        nextNode: RichContentNode | null
        actions: NotebookNodeAction[]
        customMenuItems: MenuItems | null
        messageListeners: NotebookNodeMessagesListeners
        titlePlaceholder: string
        isEditingTitle: boolean
        pythonRunLoading: boolean
        pythonRunQueued: boolean
        duckSqlRunLoading: boolean
        duckSqlRunQueued: boolean
        insightsqlSqlRunLoading: boolean
        insightsqlSqlRunQueued: boolean
        dataframeVariableName: string | null
        dataframePage: number
        dataframePageSize: number
        dataframeResult: NotebookDataframeResult | null
        dataframeLoading: boolean
        dataframeError: string | null
        editor: NotebookEditor | null
        notebook: NotebookType | null
        comments: CommentType[] | null
        kernelInfo: NotebookKernelInfo | null
        pythonNodeSummaries: PythonNodeSummary[]
        duckSqlNodeSummaries: DuckSqlNodeSummary[]
        insightsqlSqlNodeSummaries: InsightsqlSqlNodeSummary[]
        dependencyGraph: NotebookDependencyGraph
        isEditable: boolean
        notebookLogic: BuiltLogic<notebookLogicType>
        nodeAttributes: NotebookNodeAttributes<any>
        nodeId: string
        nodeType: NotebookNodeType
        Settings: NotebookNodeSettings | null
        settingsPlacement: NotebookNodeSettingsPlacement
        title: any
        children: NotebookNodeResource[]
        exportedGlobals: {
            name: string
            type: string
        }[]
        pythonExecution: PythonExecutionResult | null
        displayedGlobals: {
            insightsqlQuery?: string
            name: string
            type: string
        }[]
        pythonNodeIndex: number
        duckSqlNodeIndex: number
        duckSqlReturnVariable: string
        insightsqlSqlNodeIndex: number
        insightsqlSqlReturnVariable: string
        dataframeRowCount: number
        duckSqlTablesUsed: string[]
        duckSqlUpstreamTableSources: Record<string, NotebookDependencyUsage>
        duckSqlReturnVariableUsage: NotebookDependencyUsage[]
        insightsqlReturnVariableUsage: NotebookDependencyUsage[]
        usageByVariable: Record<string, NotebookDependencyUsage[]>
        sendMessage: <T extends keyof NotebookNodeMessages>(message: T, payload: NotebookNodeMessages[T]) => boolean
        sourceComment: CommentType | null | undefined
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        notebookLogic: (notebookLogic: BuiltLogic<notebookLogicType>) => BuiltLogic<notebookLogicType>
        nodeAttributes: (attributes: any) => NotebookNodeAttributes<any>
        nodeId: (attributes: any) => string
        nodeType: (nodeType: NotebookNodeType) => NotebookNodeType
        Settings: (arg: any) => NotebookNodeSettings | null
        settingsPlacement: (arg: any) => NotebookNodeSettingsPlacement
        title: (titlePlaceholder: string, nodeAttributes: any) => any
        children: (nodeAttributes: any) => NotebookNodeResource[]
        exportedGlobals: (nodeAttributes: any) => {
            name: string
            type: string
        }[]
        pythonExecution: (nodeAttributes: any) => PythonExecutionResult | null
        displayedGlobals: (
            exportedGlobals: {
                name: string
                type: string
            }[],
            pythonExecution: PythonExecutionResult | null
        ) => {
            insightsqlQuery?: string
            name: string
            type: string
        }[]
        pythonNodeIndex: (
            pythonNodeSummaries: import('/home/z/work/hanzo/insights/frontend/src/scenes/notebooks/Nodes/notebookNodeContent').PythonNodeSummary[],
            nodeId: string
        ) => number
        duckSqlNodeIndex: (duckSqlNodeSummaries: DuckSqlNodeSummary[], nodeId: string) => number
        duckSqlReturnVariable: (
            duckSqlNodeSummaries: DuckSqlNodeSummary[],
            nodeId: string,
            nodeAttributes: any
        ) => string
        insightsqlSqlNodeIndex: (insightsqlSqlNodeSummaries: InsightsqlSqlNodeSummary[], nodeId: string) => number
        insightsqlSqlReturnVariable: (
            insightsqlSqlNodeSummaries: InsightsqlSqlNodeSummary[],
            nodeId: string,
            nodeAttributes: any
        ) => string
        dataframeRowCount: (dataframeResult: NotebookDataframeResult | null) => number
        duckSqlTablesUsed: (dependencyGraph: NotebookDependencyGraph, nodeId: string) => string[]
        duckSqlUpstreamTableSources: (
            dependencyGraph: NotebookDependencyGraph,
            nodeId: string
        ) => Record<string, NotebookDependencyUsage>
        duckSqlReturnVariableUsage: (
            dependencyGraph: NotebookDependencyGraph,
            nodeId: string,
            duckSqlReturnVariable: string
        ) => NotebookDependencyUsage[]
        insightsqlReturnVariableUsage: (
            dependencyGraph: NotebookDependencyGraph,
            nodeId: string,
            insightsqlSqlReturnVariable: string
        ) => NotebookDependencyUsage[]
        usageByVariable: (
            dependencyGraph: NotebookDependencyGraph,
            exportedGlobals: {
                name: string
                type: string
            }[],
            nodeId: string
        ) => Record<string, NotebookDependencyUsage[]>
        sendMessage: (
            messageListeners: NotebookNodeMessagesListeners
        ) => <T extends keyof NotebookNodeMessages>(message: T, payload: NotebookNodeMessages[T]) => boolean
        sourceComment: (
            comments: import('/home/z/work/hanzo/insights/frontend/src/types').CommentType[] | null,
            nodeId: string
        ) => CommentType | null | undefined
    }
}
