# Generated by Django 3.2.19 on 2023-11-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0364_team_external_data_workspace_rows"),
    ]

    # :TRICKY:
    # We are replacing the original generated migration:
    # migrations.AlterField(
    #     model_name='experiment',
    #     name='created_by',
    #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
    # ),
    # migrations.AlterField(
    #     model_name='featureflag',
    #     name='created_by',
    #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
    # ),
    # with one that adds the 'NOT VALID' directive, which applies the constraint only for inserts/updates.
    # This ensures the table is not locked when creating the new constraint.
    # A follow up migration will validate the constraint.
    # The code here is exactly the same as the one generated by the default migration, except for the 'NOT VALID' directive.

    operations = [
        # make the created_by column nullable in experiments & flags
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="experiment",
                    name="created_by",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="insights.user",
                    ),
                ),
                migrations.AlterField(
                    model_name="featureflag",
                    name="created_by",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="insights.user",
                    ),
                ),
            ],
            database_operations=[
                # We add -- existing-table-constraint-ignore to ignore the constraint validation in CI.
                # This should be safe, because we are making the constraint NOT VALID, so doesn't lock things up for long.
                migrations.RunSQL(
                    """
                    SET CONSTRAINTS "insights_experiment_created_by_id_b40aea95_fk_insights_user_id" IMMEDIATE; -- existing-table-constraint-ignore
                    ALTER TABLE "insights_experiment" DROP CONSTRAINT "insights_experiment_created_by_id_b40aea95_fk_insights_user_id"; -- existing-table-constraint-ignore
                    ALTER TABLE "insights_experiment" ALTER COLUMN "created_by_id" DROP NOT NULL;
                    ALTER TABLE "insights_experiment" ADD CONSTRAINT "insights_experiment_created_by_id_b40aea95_fk_insights_user_id" FOREIGN KEY ("created_by_id") REFERENCES "insights_user" ("id") DEFERRABLE INITIALLY DEFERRED NOT VALID; -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                        SET CONSTRAINTS "insights_experiment_created_by_id_b40aea95_fk_insights_user_id" IMMEDIATE;
                        ALTER TABLE "insights_experiment" DROP CONSTRAINT "insights_experiment_created_by_id_b40aea95_fk_insights_user_id";
                        ALTER TABLE "insights_experiment" ALTER COLUMN "created_by_id" SET NOT NULL;
                        ALTER TABLE "insights_experiment" ADD CONSTRAINT "insights_experiment_created_by_id_b40aea95_fk_insights_user_id" FOREIGN KEY ("created_by_id") REFERENCES "insights_user" ("id") DEFERRABLE INITIALLY DEFERRED NOT VALID;
                    """,
                ),
                migrations.RunSQL(
                    """SET CONSTRAINTS "insights_featureflag_created_by_id_4571fe1a_fk_insights_user_id" IMMEDIATE; -- existing-table-constraint-ignore
                    ALTER TABLE "insights_featureflag" DROP CONSTRAINT "insights_featureflag_created_by_id_4571fe1a_fk_insights_user_id"; -- existing-table-constraint-ignore
                    ALTER TABLE "insights_featureflag" ALTER COLUMN "created_by_id" DROP NOT NULL;
                    ALTER TABLE "insights_featureflag" ADD CONSTRAINT "insights_featureflag_created_by_id_4571fe1a_fk_insights_user_id" FOREIGN KEY ("created_by_id") REFERENCES "insights_user" ("id") DEFERRABLE INITIALLY DEFERRED NOT VALID; -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                        SET CONSTRAINTS "insights_featureflag_created_by_id_4571fe1a_fk_insights_user_id" IMMEDIATE;
                        ALTER TABLE "insights_featureflag" DROP CONSTRAINT "insights_featureflag_created_by_id_4571fe1a_fk_insights_user_id";
                        ALTER TABLE "insights_featureflag" ALTER COLUMN "created_by_id" SET NOT NULL;
                        ALTER TABLE "insights_featureflag" ADD CONSTRAINT "insights_featureflag_created_by_id_4571fe1a_fk_insights_user_id" FOREIGN KEY ("created_by_id") REFERENCES "insights_user" ("id") DEFERRABLE INITIALLY DEFERRED NOT VALID;
                        -- existing-table-constraint-ignore
                    """,
                ),
            ],
        ),
    ]
