# Generated by Django 4.2.11 on 2024-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0426_externaldatasource_sync_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="insightsfunction",
            name="icon_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insightsfunction",
            name="template_id",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
