# Generated by Django 4.2.14 on 2024-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0443_externaldatajob_workflow_run_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="integration",
                    name="integration_id",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name="integration",
                    name="kind",
                    field=models.CharField(choices=[("slack", "Slack"), ("salesforce", "Salesforce")], max_length=10),
                ),
                migrations.AddConstraint(
                    model_name="integration",
                    constraint=models.UniqueConstraint(
                        fields=("team", "kind", "integration_id"), name="insights_integration_kind_id_unique"
                    ),
                ),
            ],
            database_operations=[
                # We add -- existing-table-constraint-ignore to ignore the constraint validation in CI.
                migrations.RunSQL(
                    """
                    ALTER TABLE "insights_integration" ADD COLUMN "integration_id" text NULL;
                    ALTER TABLE "insights_integration" ADD CONSTRAINT "insights_integration_kind_id_unique" UNIQUE ("team_id", "kind", "integration_id"); -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                        ALTER TABLE "insights_integration" DROP COLUMN IF EXISTS "integration_id";
                        ALTER TABLE "insights_integration" DROP CONSTRAINT IF EXISTS "insights_integration_kind_id_unique"; -- existing-table-constraint-ignore
                    """,
                ),
            ],
        )
    ]
