# Generated by Django 4.2.15 on 2024-10-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("insights", "0482_alertconfiguration_calculation_interval_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="datawarehousesavedquery",
                    name="table",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="insights.datawarehousetable",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE "insights_datawarehousesavedquery" ADD COLUMN "table_id" uuid NULL CONSTRAINT "insights_datawarehous_table_id_96fdb4f5_fk_insights_d" REFERENCES "insights_datawarehousetable"("id") DEFERRABLE INITIALLY DEFERRED; -- existing-table-constraint-ignore
                    SET CONSTRAINTS ALL IMMEDIATE; -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                    ALTER TABLE "insights_datawarehousesavedquery" DROP COLUMN IF EXISTS "table_id";
                    """,
                ),
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "insights_datawarehousesavedquery_table_id_96fdb4f5" ON "insights_datawarehousesavedquery" ("table_id");
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS "insights_datawarehousesavedquery_table_id_96fdb4f5";
                    """,
                ),
            ],
        ),
    ]
