# Generated by Django 4.2.15 on 2024-10-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [
        ("insights", "0504_add_dead_clicks_setting"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="grouptypemapping",
                    name="project",
                    field=models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="insights.project"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE "insights_grouptypemapping" ADD COLUMN "project_id" bigint NULL CONSTRAINT "insights_grouptypemap_project_id_239c0515_fk_insights_p" REFERENCES "insights_project"("id") DEFERRABLE INITIALLY DEFERRED;
                    SET CONSTRAINTS ALL IMMEDIATE;""",
                    reverse_sql="""
                    ALTER TABLE "insights_grouptypemapping" DROP COLUMN IF EXISTS "project_id";""",
                ),
                # We add CONCURRENTLY to the create command
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "insights_grouptypemapping_project_id_239c0515" ON "insights_grouptypemapping" ("project_id");""",
                    reverse_sql="""
                    DROP INDEX IF EXISTS "insights_grouptypemapping_project_id_239c0515";""",
                ),
            ],
        ),
    ]
