# Generated by Django 4.2.15 on 2024-11-19 12:03

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [("insights", "0524_datawarehousejoin_configuration")]

    operations = [
        migrations.AddField(
            model_name="insightsfunction",
            name="transpiled",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insightsfunction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("destination", "Destination"),
                    ("site_destination", "Site Destination"),
                    ("site_app", "Site App"),
                    ("email", "Email"),
                    ("sms", "Sms"),
                    ("push", "Push"),
                    ("activity", "Activity"),
                    ("alert", "Alert"),
                    ("broadcast", "Broadcast"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        AddIndexConcurrently(
            model_name="insightsfunction",
            index=models.Index(fields=["type", "enabled", "team"], name="insights_iql_type_6f8967_idx"),
        ),
    ]
