# Generated by Django 4.2.15 on 2024-12-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0534_team_cookieless_server_hash_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insightsfunction",
            name="type",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
