# Generated by Django 4.2.18 on 2025-02-12 11:48

import django.db.models.deletion
from django.db import migrations, models

# NOTE: Modified to ensure constraint is added in a non-blocking way


class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [("insights", "0663_alter_insightvariable_type")]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="batchexportrun",
                    name="backfill",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="The backfill this run belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        related_query_name="run",
                        to="insights.batchexportbackfill",
                    ),
                ),
            ],
            database_operations=[
                # We add -- existing-table-constraint-ignore to ignore the constraint validation in CI.
                migrations.RunSQL(
                    """
                    ALTER TABLE "insights_batchexportrun" ADD COLUMN "backfill_id" uuid NULL CONSTRAINT "insights_batchexportr_backfill_id_9243c0f7_fk_insights_b" REFERENCES "insights_batchexportbackfill"("id") DEFERRABLE INITIALLY DEFERRED; -- existing-table-constraint-ignore
                    SET CONSTRAINTS "insights_batchexportr_backfill_id_9243c0f7_fk_insights_b" IMMEDIATE; -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                        ALTER TABLE "insights_batchexportrun" DROP COLUMN IF EXISTS "backfill_id";
                    """,
                ),
                # We add CONCURRENTLY to the create command
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "insights_batchexportrun_backfill_id_9243c0f7" ON "insights_batchexportrun" ("backfill_id");
                    """,
                    reverse_sql="""
                        DROP INDEX IF EXISTS "insights_batchexportrun_backfill_id_9243c0f7";
                    """,
                ),
            ],
        ),
    ]
