# Generated by Django 4.2.18 on 2025-03-17 22:25
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Allows these schema changes (DDL) without holding a transaction the whole time

    dependencies = [
        ("insights", "0689_survey_enable_partial_responses"),
    ]

    operations = [
        #
        # STEP 1: Drop any existing constraints and alter columns to BigInt.
        #         *No* ADD CONSTRAINT lines here, so no linter complaints.
        #
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update Django's idea of the field definitions:
                migrations.AlterField(
                    model_name="person",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="persondistinctid",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="cohortpeople",
                    name="person",
                    field=models.ForeignKey(
                        to="insights.person",
                        on_delete=models.CASCADE,
                    ),
                ),
                migrations.AlterField(
                    model_name="featureflaghashkeyoverride",
                    name="person",
                    field=models.ForeignKey(
                        to="insights.person",
                        on_delete=models.CASCADE,
                    ),
                ),
                migrations.AlterField(
                    model_name="persondistinctid",
                    name="person",
                    field=models.ForeignKey(
                        to="insights.person",
                        on_delete=models.CASCADE,
                    ),
                ),
                migrations.AlterField(
                    model_name="eventproperty",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        -- Drop old FK constraints if they exist
                        ALTER TABLE "insights_cohortpeople"
                            DROP CONSTRAINT IF EXISTS "insights_cohortpeople_person_id_33da7d3f_fk";
                        ALTER TABLE "insights_featureflaghashkeyoverride"
                            DROP CONSTRAINT IF EXISTS "insights_featureflaghashkeyoverride_person_id_7e517f7c_fk";
                        ALTER TABLE "insights_persondistinctid"
                            DROP CONSTRAINT IF EXISTS "insights_persondistinctid_person_id_5d655bba_fk";

                        -- Convert columns to bigint
                        ALTER TABLE "insights_person"
                            ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
                        ALTER SEQUENCE IF EXISTS "insights_person_id_seq" AS bigint;

                        ALTER TABLE "insights_cohortpeople"
                            ALTER COLUMN "person_id" TYPE bigint USING "person_id"::bigint;
                        ALTER TABLE "insights_featureflaghashkeyoverride"
                            ALTER COLUMN "person_id" TYPE bigint USING "person_id"::bigint;
                        ALTER TABLE "insights_persondistinctid"
                            ALTER COLUMN "person_id" TYPE bigint USING "person_id"::bigint;

                        ALTER TABLE "insights_persondistinctid"
                            ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
                        ALTER SEQUENCE IF EXISTS "insights_persondistinctid_id_seq" AS bigint;

                        ALTER TABLE "insights_eventproperty"
                            ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
                        ALTER SEQUENCE IF EXISTS "insights_eventproperty_id_seq" AS bigint;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        #
        # STEP 2: Add each foreign key constraint with NOT VALID (non-blocking),
        #         and the Insights-linter-ignore comment on the exact same line.
        #
        migrations.RunSQL(
            sql="""
                ALTER TABLE "insights_cohortpeople" ADD CONSTRAINT "insights_cohortpeople_person_id_33da7d3f_fk" FOREIGN KEY ("person_id") REFERENCES "insights_person" ("id") NOT VALID; -- existing-table-constraint-ignore
                ALTER TABLE "insights_featureflaghashkeyoverride" ADD CONSTRAINT "insights_featureflaghashkeyoverride_person_id_7e517f7c_fk" FOREIGN KEY ("person_id") REFERENCES "insights_person" ("id") NOT VALID; -- existing-table-constraint-ignore
                ALTER TABLE "insights_persondistinctid" ADD CONSTRAINT "insights_persondistinctid_person_id_5d655bba_fk" FOREIGN KEY ("person_id") REFERENCES "insights_person" ("id") NOT VALID; -- existing-table-constraint-ignore
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        #
        # STEP 3: Validate each constraint in a separate operation.
        #
        migrations.RunSQL(
            sql="""
                ALTER TABLE "insights_cohortpeople" VALIDATE CONSTRAINT "insights_cohortpeople_person_id_33da7d3f_fk";
                ALTER TABLE "insights_featureflaghashkeyoverride" VALIDATE CONSTRAINT "insights_featureflaghashkeyoverride_person_id_7e517f7c_fk";
                ALTER TABLE "insights_persondistinctid" VALIDATE CONSTRAINT "insights_persondistinctid_person_id_5d655bba_fk";
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
