# Generated by Django 4.2.18 on 2025-04-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [
        ("insights", "0701_uploadedmedia_project"),
    ]

    operations = [
        # Add "project_id" to the datacolortheme. Splitting state and database operations to add the index concurrently
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="datacolortheme",
                    name="project",
                    field=models.ForeignKey(
                        null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to="insights.project"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE "insights_datacolortheme" ADD COLUMN "project_id" bigint NULL CONSTRAINT "insights_datacolortheme_project_id_CZYFwmeeLU_fk_insights_p" REFERENCES "insights_project"("id") DEFERRABLE INITIALLY DEFERRED;
                    SET CONSTRAINTS ALL IMMEDIATE;""",
                    reverse_sql="""
                        ALTER TABLE "insights_datacolortheme" DROP COLUMN IF EXISTS "project_id";""",
                ),
                # We add CONCURRENTLY to the create command
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "insights_datacolortheme_project_id_CZYFwmeeLU_Rvzb4NfvcS" ON "insights_datacolortheme" ("project_id");""",
                    reverse_sql="""
                        DROP INDEX IF EXISTS "insights_datacolortheme_project_id_CZYFwmeeLU_Rvzb4NfvcS";""",
                ),
            ],
        ),
    ]
