# Generated by Django 4.2.15 on 2024-11-27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0921_teammarketinganalyticsconfig__campaign_field_preferences_and_more"),
    ]

    operations = [
        # Drop foreign key constraints for all tables that are now in the persons database
        # These tables are managed separately and don't need FK constraints to insights_team
        # insights_persondistinctid
        migrations.RunSQL(
            sql="""
                ALTER TABLE insights_persondistinctid
                DROP CONSTRAINT IF EXISTS "insights_persondistinctid_team_id_8f5c9804_fk_insights_team_id";
            """,
            reverse_sql="""
                ALTER TABLE insights_persondistinctid
                ADD CONSTRAINT "insights_persondistinctid_team_id_8f5c9804_fk_insights_team_id"
                FOREIGN KEY (team_id)
                REFERENCES insights_team(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
        # insights_personlessdistinctid
        migrations.RunSQL(
            sql="""
                ALTER TABLE insights_personlessdistinctid
                DROP CONSTRAINT IF EXISTS "insights_personlessdi_team_id_99211fb1_fk_insights_t";
            """,
            reverse_sql="""
                ALTER TABLE insights_personlessdistinctid
                ADD CONSTRAINT "insights_personlessdi_team_id_99211fb1_fk_insights_t"
                FOREIGN KEY (team_id)
                REFERENCES insights_team(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
        # insights_personoverride
        migrations.RunSQL(
            sql="""
                ALTER TABLE insights_personoverride
                DROP CONSTRAINT IF EXISTS "insights_personoverride_team_id_cf1a22c0_fk_insights_team_id";
            """,
            reverse_sql="""
                ALTER TABLE insights_personoverride
                ADD CONSTRAINT "insights_personoverride_team_id_cf1a22c0_fk_insights_team_id"
                FOREIGN KEY (team_id)
                REFERENCES insights_team(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
        # insights_featureflaghashkeyoverride
        migrations.RunSQL(
            sql="""
                ALTER TABLE insights_featureflaghashkeyoverride
                DROP CONSTRAINT IF EXISTS "insights_featureflagh_team_id_b626eed2_fk_insights_t";
            """,
            reverse_sql="""
                ALTER TABLE insights_featureflaghashkeyoverride
                ADD CONSTRAINT "insights_featureflagh_team_id_b626eed2_fk_insights_t"
                FOREIGN KEY (team_id)
                REFERENCES insights_team(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
        # insights_grouptypemapping
        migrations.RunSQL(
            sql="""
                ALTER TABLE insights_grouptypemapping
                DROP CONSTRAINT IF EXISTS "insights_grouptypemapping_team_id_d66aad62_fk_insights_team_id";
            """,
            reverse_sql="""
                ALTER TABLE insights_grouptypemapping
                ADD CONSTRAINT "insights_grouptypemapping_team_id_d66aad62_fk_insights_team_id"
                FOREIGN KEY (team_id)
                REFERENCES insights_team(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
