# Generated by Django 5.2.14 on 2026-06-30 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import insights.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "1245_duckgres_sink_schema_state"),
        ("web_analytics", "0005_savedheatmap_block_consent_modals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAnalyticsUserConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=insights.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("achievements_opt_out", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insights.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "insights_webanalyticsuserconfig",
                "constraints": [
                    models.UniqueConstraint(fields=("team", "user"), name="unique_web_analytics_user_config")
                ],
            },
        ),
    ]
