// Generated by kea-typegen on Sun, 02 Aug 2026 21:38:48 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { InsightLogicProps } from '../../types'
import type { DateRange, FunnelsQuery, LifecycleQuery, PathsQuery, RetentionFilter, RetentionQuery, StickinessQuery, TrendsQuery, WebOverviewQuery, WebStatsTableQuery } from '../../queries/schema/schema-general'
import type { ProcessedRetentionPayload, RetentionTrendPayload } from './types'
import type { MeanRetentionValue } from './retentionLogic'

export interface retentionGraphLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: string
    listeners: {}
    path: ['scenes', 'retention', 'retentionGraphLogic', '*']
    pathString: 'scenes.retention.retentionGraphLogic.*'
    props: InsightLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        querySource: (
            state: any,
            props?: any
        ) =>
            | FunnelsQuery
            | LifecycleQuery
            | PathsQuery
            | RetentionQuery
            | StickinessQuery
            | TrendsQuery
            | WebOverviewQuery
            | WebStatsTableQuery
            | null
        dateRange: (state: any, props?: any) => DateRange | null | undefined
        retentionFilter: (state: any, props?: any) => RetentionFilter | null
        selectedBreakdownValue: (state: any, props?: any) => boolean | number | string | null
        hasValidBreakdown: (state: any, props?: any) => boolean
        results: (state: any, props?: any) => ProcessedRetentionPayload[]
        filteredResults: (state: any, props?: any) => ProcessedRetentionPayload[]
        retentionMeans: (state: any, props?: any) => Record<string, MeanRetentionValue>
        breakdownDisplayNames: (state: any, props?: any) => Record<string, string>
        timezone: (state: any, props?: any) => string
        trendSeries: (state: any, props?: any) => RetentionTrendPayload[]
        intervalViewSeries: (state: any, props?: any) => RetentionTrendPayload[]
        showTrendLines: (state: any, props?: any) => boolean
        incompletenessOffsetFromEnd: (state: any, props?: any) => number
        aggregationGroupTypeIndex: (state: any, props?: any) => number | 'people'
        shouldShowMeanPerBreakdown: (state: any, props?: any) => boolean
        filteredTrendSeries: (state: any, props?: any) => RetentionTrendPayload[]
        xAxisLabels: (state: any, props?: any) => string[]
    }
    sharedListeners: {}
    values: {
        querySource:
            | FunnelsQuery
            | LifecycleQuery
            | PathsQuery
            | RetentionQuery
            | StickinessQuery
            | TrendsQuery
            | WebOverviewQuery
            | WebStatsTableQuery
            | null
        dateRange: DateRange | null | undefined
        retentionFilter: RetentionFilter | null
        selectedBreakdownValue: boolean | number | string | null
        hasValidBreakdown: boolean
        results: ProcessedRetentionPayload[]
        filteredResults: ProcessedRetentionPayload[]
        retentionMeans: Record<string, MeanRetentionValue>
        breakdownDisplayNames: Record<string, string>
        timezone: string
        trendSeries: RetentionTrendPayload[]
        intervalViewSeries: RetentionTrendPayload[]
        showTrendLines: boolean
        incompletenessOffsetFromEnd: number
        aggregationGroupTypeIndex: number | 'people'
        shouldShowMeanPerBreakdown: boolean
        filteredTrendSeries: RetentionTrendPayload[]
        xAxisLabels: string[]
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        trendSeries: (
            results: ProcessedRetentionPayload[],
            retentionFilter:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').RetentionFilter
        ) => RetentionTrendPayload[]
        intervalViewSeries: (
            filteredResults: ProcessedRetentionPayload[],
            retentionFilter:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').RetentionFilter,
            hasValidBreakdown: boolean,
            breakdownDisplayNames: Record<string, string>
        ) => RetentionTrendPayload[]
        showTrendLines: (
            querySource:
                | RetentionQuery
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').FunnelsQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').LifecycleQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').PathsQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').StickinessQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').TrendsQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').WebOverviewQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').WebStatsTableQuery
        ) => boolean
        incompletenessOffsetFromEnd: (
            dateRange: DateRange | null | undefined,
            retentionFilter:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').RetentionFilter,
            trendSeries: RetentionTrendPayload[],
            timezone: string
        ) => number
        aggregationGroupTypeIndex: (
            querySource:
                | RetentionQuery
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').FunnelsQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').LifecycleQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').PathsQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').StickinessQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').TrendsQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').WebOverviewQuery
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').WebStatsTableQuery
        ) => number | 'people'
        shouldShowMeanPerBreakdown: (
            hasValidBreakdown: boolean,
            selectedBreakdownValue: boolean | number | string | null
        ) => boolean
        filteredTrendSeries: (
            hasValidBreakdown: boolean,
            trendSeries: RetentionTrendPayload[],
            selectedBreakdownValue: boolean | number | string | null,
            retentionMeans: Record<string, MeanRetentionValue>,
            retentionFilter:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').RetentionFilter,
            shouldShowMeanPerBreakdown: boolean,
            breakdownDisplayNames: Record<string, string>,
            intervalViewSeries: RetentionTrendPayload[]
        ) => RetentionTrendPayload[]
        xAxisLabels: (
            retentionFilter:
                | null
                | import('/home/z/work/hanzo/insights/frontend/src/queries/schema/schema-general').RetentionFilter,
            results: ProcessedRetentionPayload[],
            filteredResults: ProcessedRetentionPayload[]
        ) => string[]
    }
}
