// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:33 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { SessionRecordingMetaLogicProps } from './sessionRecordingMetaLogic'
import type { RecordingEventType, SessionRecordingType } from '../../../types'
import type { TimeTree } from '../../../lib/utils/time-tree'
import type { Dayjs } from '../../../lib/dayjs'
import type { ViewportResolution } from './snapshot-processing/patch-meta-event'

export interface sessionEventsDataLogicType extends Logic {
    actionCreators: {
        loadRecordingMetaSuccess: (
            sessionPlayerMetaData: SessionRecordingType | null,
            payload?: {
                value: true
            }
        ) => {
            type: 'load recording meta success (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                payload?: {
                    value: true
                }
                sessionPlayerMetaData: SessionRecordingType | null
            }
        }
        loadEvents: () => {
            type: 'load events (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                value: true
            }
        }
        loadFullEventData: (event: RecordingEventType | RecordingEventType[]) => {
            type: 'load full event data (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                event: RecordingEventType | RecordingEventType[]
            }
        }
        loadEventsSuccess: (
            sessionEventsData: RecordingEventType[] | null,
            payload?: {
                value: true
            }
        ) => {
            type: 'load events success (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                sessionEventsData: RecordingEventType[] | null
                payload?: {
                    value: true
                }
            }
        }
        loadEventsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load events failure (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadFullEventDataSuccess: (
            sessionEventsData: RecordingEventType[] | null,
            payload?: {
                event: RecordingEventType | RecordingEventType[]
            }
        ) => {
            type: 'load full event data success (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                sessionEventsData: RecordingEventType[] | null
                payload?: {
                    event: RecordingEventType | RecordingEventType[]
                }
            }
        }
        loadFullEventDataFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load full event data failure (scenes.session-recordings.sessionEventsDataLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'load recording meta success (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadRecordingMetaSuccess'
        'load events (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadEvents'
        'load full event data (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadFullEventData'
        'load events success (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadEventsSuccess'
        'load events failure (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadEventsFailure'
        'load full event data success (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadFullEventDataSuccess'
        'load full event data failure (scenes.session-recordings.sessionEventsDataLogic.*)': 'loadFullEventDataFailure'
    }
    actionTypes: {
        loadRecordingMetaSuccess: 'load recording meta success (scenes.session-recordings.sessionEventsDataLogic.*)'
        loadEvents: 'load events (scenes.session-recordings.sessionEventsDataLogic.*)'
        loadFullEventData: 'load full event data (scenes.session-recordings.sessionEventsDataLogic.*)'
        loadEventsSuccess: 'load events success (scenes.session-recordings.sessionEventsDataLogic.*)'
        loadEventsFailure: 'load events failure (scenes.session-recordings.sessionEventsDataLogic.*)'
        loadFullEventDataSuccess: 'load full event data success (scenes.session-recordings.sessionEventsDataLogic.*)'
        loadFullEventDataFailure: 'load full event data failure (scenes.session-recordings.sessionEventsDataLogic.*)'
    }
    actions: {
        loadRecordingMetaSuccess: (
            sessionPlayerMetaData: SessionRecordingType | null,
            payload?: {
                value: true
            }
        ) => void
        loadEvents: () => void
        loadFullEventData: (event: RecordingEventType | RecordingEventType[]) => void
        loadEventsSuccess: (
            sessionEventsData: RecordingEventType[] | null,
            payload?: {
                value: true
            }
        ) => void
        loadEventsFailure: (error: string, errorObject?: any) => void
        loadFullEventDataSuccess: (
            sessionEventsData: RecordingEventType[] | null,
            payload?: {
                event: RecordingEventType | RecordingEventType[]
            }
        ) => void
        loadFullEventDataFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadRecordingMetaSuccess: (
            sessionPlayerMetaData: SessionRecordingType | null,
            payload?: {
                value: true
            }
        ) => Promise<any>
        loadEvents: () => Promise<any>
        loadFullEventData: (event: RecordingEventType | RecordingEventType[]) => Promise<any>
        loadEventsSuccess: (
            sessionEventsData: RecordingEventType[] | null,
            payload?: {
                value: true
            }
        ) => Promise<any>
        loadEventsFailure: (error: string, errorObject?: any) => Promise<any>
        loadFullEventDataSuccess: (
            sessionEventsData: RecordingEventType[] | null,
            payload?: {
                event: RecordingEventType | RecordingEventType[]
            }
        ) => Promise<any>
        loadFullEventDataFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        sessionEventsData: RecordingEventType[] | null
        sessionEventsDataLoading: boolean
    }
    events: {}
    key: string
    listeners: {
        loadRecordingMetaSuccess: ((
            action: {
                type: 'load recording meta success (scenes.session-recordings.sessionEventsDataLogic.*)'
                payload: {
                    payload?: {
                        value: true
                    }
                    sessionPlayerMetaData: SessionRecordingType | null
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'session-recordings', 'sessionEventsDataLogic', '*']
    pathString: 'scenes.session-recordings.sessionEventsDataLogic.*'
    props: SessionRecordingMetaLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        sessionEventsData: RecordingEventType[] | null
        sessionEventsDataLoading: boolean
    }
    reducers: {
        sessionEventsData: (
            state: RecordingEventType[] | null,
            action: any,
            fullState: any
        ) => RecordingEventType[] | null
        sessionEventsDataLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        sessionEventsData: RecordingEventType[] | null
        sessionEventsDataLoading: boolean
    }
    selectors: {
        sessionEventsData: (state: any, props?: any) => RecordingEventType[] | null
        sessionEventsDataLoading: (state: any, props?: any) => boolean
        sessionPlayerMetaData: (state: any, props?: any) => SessionRecordingType | null
        webVitalsEvents: (state: any, props?: any) => RecordingEventType[]
        AIEvents: (state: any, props?: any) => RecordingEventType[]
        exceptionEvents: (state: any, props?: any) => RecordingEventType[]
        preloadableEvents: (state: any, props?: any) => RecordingEventType[]
        eventViewportsItems: (
            state: any,
            props?: any
        ) => TimeTree<{
            payload: ViewportResolution
            timestamp: Dayjs
        }>
        viewportForTimestamp: (state: any, props?: any) => (timestamp: number) => ViewportResolution | undefined
    }
    sharedListeners: {}
    values: {
        sessionEventsData: RecordingEventType[] | null
        sessionEventsDataLoading: boolean
        sessionPlayerMetaData: SessionRecordingType | null
        webVitalsEvents: RecordingEventType[]
        AIEvents: RecordingEventType[]
        exceptionEvents: RecordingEventType[]
        preloadableEvents: RecordingEventType[]
        eventViewportsItems: TimeTree<{
            payload: ViewportResolution
            timestamp: Dayjs
        }>
        viewportForTimestamp: (timestamp: number) => ViewportResolution | undefined
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        webVitalsEvents: (sessionEventsData: RecordingEventType[] | null) => RecordingEventType[]
        AIEvents: (sessionEventsData: RecordingEventType[] | null) => RecordingEventType[]
        exceptionEvents: (sessionEventsData: RecordingEventType[] | null) => RecordingEventType[]
        preloadableEvents: (
            webVitalsEvents: RecordingEventType[],
            AIEvents: RecordingEventType[],
            exceptionEvents: RecordingEventType[]
        ) => RecordingEventType[]
        eventViewportsItems: (sessionEventsData: RecordingEventType[] | null) => TimeTree<{
            payload: ViewportResolution
            timestamp: Dayjs
        }>
        viewportForTimestamp: (
            eventViewportsItems: TimeTree<{
                payload: ViewportResolution
                timestamp: Dayjs
            }>
        ) => (timestamp: number) => ViewportResolution | undefined
    }
}
