// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:58 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface newAccountMenuLogicType extends Logic {
    actionCreators: {
        setAccountMenuOpen: (isOpen: boolean) => {
            type: 'set account menu open (lib.components.Account.accountMenuLogic)'
            payload: {
                isOpen: boolean
            }
        }
        toggleAccountMenu: () => {
            type: 'toggle account menu (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
        openProjectSwitcher: () => {
            type: 'open project switcher (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
        closeProjectSwitcher: () => {
            type: 'close project switcher (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
        toggleProjectSwitcher: () => {
            type: 'toggle project switcher (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
        openOrgSwitcher: () => {
            type: 'open org switcher (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
        closeOrgSwitcher: () => {
            type: 'close org switcher (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
        toggleOrgSwitcher: () => {
            type: 'toggle org switcher (lib.components.Account.accountMenuLogic)'
            payload: {
                value: true
            }
        }
    }
    actionKeys: {
        'set account menu open (lib.components.Account.accountMenuLogic)': 'setAccountMenuOpen'
        'toggle account menu (lib.components.Account.accountMenuLogic)': 'toggleAccountMenu'
        'open project switcher (lib.components.Account.accountMenuLogic)': 'openProjectSwitcher'
        'close project switcher (lib.components.Account.accountMenuLogic)': 'closeProjectSwitcher'
        'toggle project switcher (lib.components.Account.accountMenuLogic)': 'toggleProjectSwitcher'
        'open org switcher (lib.components.Account.accountMenuLogic)': 'openOrgSwitcher'
        'close org switcher (lib.components.Account.accountMenuLogic)': 'closeOrgSwitcher'
        'toggle org switcher (lib.components.Account.accountMenuLogic)': 'toggleOrgSwitcher'
    }
    actionTypes: {
        setAccountMenuOpen: 'set account menu open (lib.components.Account.accountMenuLogic)'
        toggleAccountMenu: 'toggle account menu (lib.components.Account.accountMenuLogic)'
        openProjectSwitcher: 'open project switcher (lib.components.Account.accountMenuLogic)'
        closeProjectSwitcher: 'close project switcher (lib.components.Account.accountMenuLogic)'
        toggleProjectSwitcher: 'toggle project switcher (lib.components.Account.accountMenuLogic)'
        openOrgSwitcher: 'open org switcher (lib.components.Account.accountMenuLogic)'
        closeOrgSwitcher: 'close org switcher (lib.components.Account.accountMenuLogic)'
        toggleOrgSwitcher: 'toggle org switcher (lib.components.Account.accountMenuLogic)'
    }
    actions: {
        setAccountMenuOpen: (isOpen: boolean) => void
        toggleAccountMenu: () => void
        openProjectSwitcher: () => void
        closeProjectSwitcher: () => void
        toggleProjectSwitcher: () => void
        openOrgSwitcher: () => void
        closeOrgSwitcher: () => void
        toggleOrgSwitcher: () => void
    }
    asyncActions: {
        setAccountMenuOpen: (isOpen: boolean) => Promise<any>
        toggleAccountMenu: () => Promise<any>
        openProjectSwitcher: () => Promise<any>
        closeProjectSwitcher: () => Promise<any>
        toggleProjectSwitcher: () => Promise<any>
        openOrgSwitcher: () => Promise<any>
        closeOrgSwitcher: () => Promise<any>
        toggleOrgSwitcher: () => Promise<any>
    }
    defaults: {
        isAccountMenuOpen: boolean
        isProjectSwitcherOpen: boolean
        isOrgSwitcherOpen: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['lib', 'components', 'Account', 'accountMenuLogic']
    pathString: 'lib.components.Account.accountMenuLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        isAccountMenuOpen: boolean
        isProjectSwitcherOpen: boolean
        isOrgSwitcherOpen: boolean
    }
    reducers: {
        isAccountMenuOpen: (state: boolean, action: any, fullState: any) => boolean
        isProjectSwitcherOpen: (state: boolean, action: any, fullState: any) => boolean
        isOrgSwitcherOpen: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        isAccountMenuOpen: boolean
        isProjectSwitcherOpen: boolean
        isOrgSwitcherOpen: boolean
    }
    selectors: {
        isAccountMenuOpen: (state: any, props?: any) => boolean
        isProjectSwitcherOpen: (state: any, props?: any) => boolean
        isOrgSwitcherOpen: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        isAccountMenuOpen: boolean
        isProjectSwitcherOpen: boolean
        isOrgSwitcherOpen: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}
