// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:07 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface reverseProxyCheckerLogicType extends Logic {
    actionCreators: {
        loadHasReverseProxy: () => {
            type: 'load has reverse proxy (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
            payload: any
        }
        loadHasReverseProxySuccess: (
            hasReverseProxy: boolean | null,
            payload?: any
        ) => {
            type: 'load has reverse proxy success (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
            payload: {
                hasReverseProxy: boolean | null
                payload?: any
            }
        }
        loadHasReverseProxyFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load has reverse proxy failure (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'load has reverse proxy (components.ReverseProxyChecker.reverseProxyCheckerLogic)': 'loadHasReverseProxy'
        'load has reverse proxy success (components.ReverseProxyChecker.reverseProxyCheckerLogic)': 'loadHasReverseProxySuccess'
        'load has reverse proxy failure (components.ReverseProxyChecker.reverseProxyCheckerLogic)': 'loadHasReverseProxyFailure'
    }
    actionTypes: {
        loadHasReverseProxy: 'load has reverse proxy (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
        loadHasReverseProxySuccess: 'load has reverse proxy success (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
        loadHasReverseProxyFailure: 'load has reverse proxy failure (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
    }
    actions: {
        loadHasReverseProxy: () => void
        loadHasReverseProxySuccess: (hasReverseProxy: boolean | null, payload?: any) => void
        loadHasReverseProxyFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadHasReverseProxy: () => Promise<any>
        loadHasReverseProxySuccess: (hasReverseProxy: boolean | null, payload?: any) => Promise<any>
        loadHasReverseProxyFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        hasReverseProxy: boolean | null
        hasReverseProxyLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {
        loadHasReverseProxySuccess: ((
            action: {
                type: 'load has reverse proxy success (components.ReverseProxyChecker.reverseProxyCheckerLogic)'
                payload: {
                    hasReverseProxy: boolean | null
                    payload?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['components', 'ReverseProxyChecker', 'reverseProxyCheckerLogic']
    pathString: 'components.ReverseProxyChecker.reverseProxyCheckerLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        hasReverseProxy: boolean | null
        hasReverseProxyLoading: boolean
    }
    reducers: {
        hasReverseProxy: (state: boolean | null, action: any, fullState: any) => boolean | null
        hasReverseProxyLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        hasReverseProxy: boolean | null
        hasReverseProxyLoading: boolean
    }
    selectors: {
        hasReverseProxy: (state: any, props?: any) => boolean | null
        hasReverseProxyLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        hasReverseProxy: boolean | null
        hasReverseProxyLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}
