# Generated by Django 4.2.29 on 2026-04-14 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import insights.models.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insights", "1095_create_group_datastore_team"),
        ("event_definitions", "0002_schemapropertygroupproperty_is_optional_in_types"),
        ("ee", "0041_migrate_dashboards_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyAccessControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=insights.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_level", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_access_controls",
                        related_query_name="property_access_controls",
                        to="insights.organizationmembership",
                    ),
                ),
                (
                    "property_definition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_access_controls",
                        related_query_name="property_access_controls",
                        to="event_definitions.propertydefinition",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_access_controls",
                        related_query_name="property_access_controls",
                        to="ee.role",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_access_controls",
                        related_query_name="property_access_controls",
                        to="insights.team",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="propertyaccesscontrol",
            constraint=models.UniqueConstraint(
                fields=("property_definition", "team", "organization_member", "role"),
                name="unique property per target",
            ),
        ),
    ]
