// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:33 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Realm, RecordingDurationFilter, RecordingUniversalFilters, SessionPlayerData, SessionRecordingType, UserType } from '../../types'
import type { SessionRecordingFilterType } from './sessionRecordingEventUsageLogic'
import type { InspectorListItemType } from './player/inspector/playerInspectorLogic'
import type { MiniFilterKey } from './player/inspector/miniFiltersLogic'

export interface sessionRecordingEventUsageLogicType extends Logic {
    actionCreators: {
        reportRecordingLoaded: (
            playerData: SessionPlayerData,
            metadata: SessionRecordingType | null
        ) => {
            type: 'report recording loaded (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                metadata: SessionRecordingType | null
                playerData: SessionPlayerData
            }
        }
        reportRecordingsListFetched: (
            loadTime: number,
            filters: RecordingUniversalFilters,
            defaultDurationFilter: RecordingDurationFilter
        ) => {
            type: 'report recordings list fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                defaultDurationFilter: RecordingDurationFilter
                filters: RecordingUniversalFilters
                loadTime: number
            }
        }
        reportRecordingsListPropertiesFetched: (loadTime: number) => {
            type: 'report recordings list properties fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                loadTime: number
            }
        }
        reportRecordingsListFilterAdded: (filterType: SessionRecordingFilterType) => {
            type: 'report recordings list filter added (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                filterType: SessionRecordingFilterType
            }
        }
        reportRecordingPlayerSeekbarEventHovered: () => {
            type: 'report recording player seekbar event hovered (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                value: true
            }
        }
        reportRecordingInspectorItemExpanded: (
            tab: InspectorListItemType,
            index: number
        ) => {
            type: 'report recording inspector item expanded (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                index: number
                tab:
                    | 'app-state'
                    | 'browser-visibility'
                    | 'comment'
                    | 'console'
                    | 'doctor'
                    | 'events'
                    | 'inactivity'
                    | 'inspector-summary'
                    | 'network'
                    | 'offline-status'
                    | 'performance'
                    | 'session-change'
            }
        }
        reportRecordingInspectorMiniFilterViewed: (
            minifilterKey: MiniFilterKey,
            enabled: boolean
        ) => {
            type: 'report recording inspector mini filter viewed (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                enabled: boolean
                minifilterKey: string
            }
        }
        reportNextRecordingTriggered: (automatic: boolean) => {
            type: 'report next recording triggered (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                automatic: boolean
            }
        }
        reportRecordingExportedToFile: () => {
            type: 'report recording exported to file (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                value: true
            }
        }
        reportRecordingLoadedFromFile: (data: { error?: string; success: boolean }) => {
            type: 'report recording loaded from file (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                error?: string | undefined
                success: boolean
            }
        }
        reportRecordingListVisibilityToggled: (
            type: string,
            visible: boolean
        ) => {
            type: 'report recording list visibility toggled (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                type: string
                visible: boolean
            }
        }
        reportRecordingPinnedToList: (pinned: boolean) => {
            type: 'report recording pinned to list (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                pinned: boolean
            }
        }
        reportRecordingPlaylistCreated: (source: 'duplicate' | 'filters' | 'new' | 'pin') => {
            type: 'report recording playlist created (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                source: 'duplicate' | 'filters' | 'new' | 'pin'
            }
        }
        reportRecordingOpenedFromRecentRecordingList: () => {
            type: 'report recording opened from recent recording list (scenes.session-recordings.sessionRecordingEventUsageLogic)'
            payload: {
                value: true
            }
        }
    }
    actionKeys: {
        'report recording loaded (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingLoaded'
        'report recordings list fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingsListFetched'
        'report recordings list properties fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingsListPropertiesFetched'
        'report recordings list filter added (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingsListFilterAdded'
        'report recording player seekbar event hovered (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingPlayerSeekbarEventHovered'
        'report recording inspector item expanded (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingInspectorItemExpanded'
        'report recording inspector mini filter viewed (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingInspectorMiniFilterViewed'
        'report next recording triggered (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportNextRecordingTriggered'
        'report recording exported to file (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingExportedToFile'
        'report recording loaded from file (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingLoadedFromFile'
        'report recording list visibility toggled (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingListVisibilityToggled'
        'report recording pinned to list (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingPinnedToList'
        'report recording playlist created (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingPlaylistCreated'
        'report recording opened from recent recording list (scenes.session-recordings.sessionRecordingEventUsageLogic)': 'reportRecordingOpenedFromRecentRecordingList'
    }
    actionTypes: {
        reportRecordingLoaded: 'report recording loaded (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingsListFetched: 'report recordings list fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingsListPropertiesFetched: 'report recordings list properties fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingsListFilterAdded: 'report recordings list filter added (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingPlayerSeekbarEventHovered: 'report recording player seekbar event hovered (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingInspectorItemExpanded: 'report recording inspector item expanded (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingInspectorMiniFilterViewed: 'report recording inspector mini filter viewed (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportNextRecordingTriggered: 'report next recording triggered (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingExportedToFile: 'report recording exported to file (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingLoadedFromFile: 'report recording loaded from file (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingListVisibilityToggled: 'report recording list visibility toggled (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingPinnedToList: 'report recording pinned to list (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingPlaylistCreated: 'report recording playlist created (scenes.session-recordings.sessionRecordingEventUsageLogic)'
        reportRecordingOpenedFromRecentRecordingList: 'report recording opened from recent recording list (scenes.session-recordings.sessionRecordingEventUsageLogic)'
    }
    actions: {
        reportRecordingLoaded: (playerData: SessionPlayerData, metadata: SessionRecordingType | null) => void
        reportRecordingsListFetched: (
            loadTime: number,
            filters: RecordingUniversalFilters,
            defaultDurationFilter: RecordingDurationFilter
        ) => void
        reportRecordingsListPropertiesFetched: (loadTime: number) => void
        reportRecordingsListFilterAdded: (filterType: SessionRecordingFilterType) => void
        reportRecordingPlayerSeekbarEventHovered: () => void
        reportRecordingInspectorItemExpanded: (tab: InspectorListItemType, index: number) => void
        reportRecordingInspectorMiniFilterViewed: (minifilterKey: MiniFilterKey, enabled: boolean) => void
        reportNextRecordingTriggered: (automatic: boolean) => void
        reportRecordingExportedToFile: () => void
        reportRecordingLoadedFromFile: (data: { error?: string; success: boolean }) => void
        reportRecordingListVisibilityToggled: (type: string, visible: boolean) => void
        reportRecordingPinnedToList: (pinned: boolean) => void
        reportRecordingPlaylistCreated: (source: 'duplicate' | 'filters' | 'new' | 'pin') => void
        reportRecordingOpenedFromRecentRecordingList: () => void
    }
    asyncActions: {
        reportRecordingLoaded: (playerData: SessionPlayerData, metadata: SessionRecordingType | null) => Promise<any>
        reportRecordingsListFetched: (
            loadTime: number,
            filters: RecordingUniversalFilters,
            defaultDurationFilter: RecordingDurationFilter
        ) => Promise<any>
        reportRecordingsListPropertiesFetched: (loadTime: number) => Promise<any>
        reportRecordingsListFilterAdded: (filterType: SessionRecordingFilterType) => Promise<any>
        reportRecordingPlayerSeekbarEventHovered: () => Promise<any>
        reportRecordingInspectorItemExpanded: (tab: InspectorListItemType, index: number) => Promise<any>
        reportRecordingInspectorMiniFilterViewed: (minifilterKey: MiniFilterKey, enabled: boolean) => Promise<any>
        reportNextRecordingTriggered: (automatic: boolean) => Promise<any>
        reportRecordingExportedToFile: () => Promise<any>
        reportRecordingLoadedFromFile: (data: { error?: string; success: boolean }) => Promise<any>
        reportRecordingListVisibilityToggled: (type: string, visible: boolean) => Promise<any>
        reportRecordingPinnedToList: (pinned: boolean) => Promise<any>
        reportRecordingPlaylistCreated: (source: 'duplicate' | 'filters' | 'new' | 'pin') => Promise<any>
        reportRecordingOpenedFromRecentRecordingList: () => Promise<any>
    }
    defaults: {}
    events: {}
    key: undefined
    listeners: {
        reportRecordingLoaded: ((
            action: {
                type: 'report recording loaded (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    metadata: SessionRecordingType | null
                    playerData: SessionPlayerData
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingsListFilterAdded: ((
            action: {
                type: 'report recordings list filter added (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    filterType: SessionRecordingFilterType
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingsListFetched: ((
            action: {
                type: 'report recordings list fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    defaultDurationFilter: RecordingDurationFilter
                    filters: RecordingUniversalFilters
                    loadTime: number
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingsListPropertiesFetched: ((
            action: {
                type: 'report recordings list properties fetched (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    loadTime: number
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingOpenedFromRecentRecordingList: ((
            action: {
                type: 'report recording opened from recent recording list (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingPlayerSeekbarEventHovered: ((
            action: {
                type: 'report recording player seekbar event hovered (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingInspectorItemExpanded: ((
            action: {
                type: 'report recording inspector item expanded (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    index: number
                    tab:
                        | 'app-state'
                        | 'browser-visibility'
                        | 'comment'
                        | 'console'
                        | 'doctor'
                        | 'events'
                        | 'inactivity'
                        | 'inspector-summary'
                        | 'network'
                        | 'offline-status'
                        | 'performance'
                        | 'session-change'
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingInspectorMiniFilterViewed: ((
            action: {
                type: 'report recording inspector mini filter viewed (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    enabled: boolean
                    minifilterKey: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportNextRecordingTriggered: ((
            action: {
                type: 'report next recording triggered (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    automatic: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingExportedToFile: ((
            action: {
                type: 'report recording exported to file (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingLoadedFromFile: ((
            action: {
                type: 'report recording loaded from file (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    error?: string | undefined
                    success: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingListVisibilityToggled: ((
            action: {
                type: 'report recording list visibility toggled (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    type: string
                    visible: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingPinnedToList: ((
            action: {
                type: 'report recording pinned to list (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    pinned: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        reportRecordingPlaylistCreated: ((
            action: {
                type: 'report recording playlist created (scenes.session-recordings.sessionRecordingEventUsageLogic)'
                payload: {
                    source: 'duplicate' | 'filters' | 'new' | 'pin'
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'session-recordings', 'sessionRecordingEventUsageLogic']
    pathString: 'scenes.session-recordings.sessionRecordingEventUsageLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        realm: (state: any, props?: any) => Realm | null
        user: (state: any, props?: any) => UserType | null
    }
    sharedListeners: {}
    values: {
        realm: Realm | null
        user: UserType | null
    }
    _isKea: true
    _isKeaWithKey: false
}
