// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:44 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { QueryBasedInsightModel } from '../../../frontend/src/types'

export interface insightPickerEndpointModalLogicType extends Logic {
    actionCreators: {
        openModal: () => {
            type: 'open modal (products.endpoints.frontend.insightPickerEndpointModalLogic)'
            payload: {
                value: true
            }
        }
        closeModal: () => {
            type: 'close modal (products.endpoints.frontend.insightPickerEndpointModalLogic)'
            payload: {
                value: true
            }
        }
        selectInsight: (insight: QueryBasedInsightModel) => {
            type: 'select insight (products.endpoints.frontend.insightPickerEndpointModalLogic)'
            payload: {
                insight: QueryBasedInsightModel
            }
        }
        clearSelectedInsight: () => {
            type: 'clear selected insight (products.endpoints.frontend.insightPickerEndpointModalLogic)'
            payload: {
                value: true
            }
        }
        toggleShowMoreInsightTypes: () => {
            type: 'toggle show more insight types (products.endpoints.frontend.insightPickerEndpointModalLogic)'
            payload: {
                value: true
            }
        }
    }
    actionKeys: {
        'open modal (products.endpoints.frontend.insightPickerEndpointModalLogic)': 'openModal'
        'close modal (products.endpoints.frontend.insightPickerEndpointModalLogic)': 'closeModal'
        'select insight (products.endpoints.frontend.insightPickerEndpointModalLogic)': 'selectInsight'
        'clear selected insight (products.endpoints.frontend.insightPickerEndpointModalLogic)': 'clearSelectedInsight'
        'toggle show more insight types (products.endpoints.frontend.insightPickerEndpointModalLogic)': 'toggleShowMoreInsightTypes'
    }
    actionTypes: {
        openModal: 'open modal (products.endpoints.frontend.insightPickerEndpointModalLogic)'
        closeModal: 'close modal (products.endpoints.frontend.insightPickerEndpointModalLogic)'
        selectInsight: 'select insight (products.endpoints.frontend.insightPickerEndpointModalLogic)'
        clearSelectedInsight: 'clear selected insight (products.endpoints.frontend.insightPickerEndpointModalLogic)'
        toggleShowMoreInsightTypes: 'toggle show more insight types (products.endpoints.frontend.insightPickerEndpointModalLogic)'
    }
    actions: {
        openModal: () => void
        closeModal: () => void
        selectInsight: (insight: QueryBasedInsightModel) => void
        clearSelectedInsight: () => void
        toggleShowMoreInsightTypes: () => void
    }
    asyncActions: {
        openModal: () => Promise<any>
        closeModal: () => Promise<any>
        selectInsight: (insight: QueryBasedInsightModel) => Promise<any>
        clearSelectedInsight: () => Promise<any>
        toggleShowMoreInsightTypes: () => Promise<any>
    }
    defaults: {
        isOpen: boolean
        selectedInsight: QueryBasedInsightModel | null
        showMoreInsightTypes: boolean
    }
    events: {}
    key: undefined
    listeners: {
        closeModal: ((
            action: {
                type: 'close modal (products.endpoints.frontend.insightPickerEndpointModalLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['products', 'endpoints', 'frontend', 'insightPickerEndpointModalLogic']
    pathString: 'products.endpoints.frontend.insightPickerEndpointModalLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        isOpen: boolean
        selectedInsight: QueryBasedInsightModel | null
        showMoreInsightTypes: boolean
    }
    reducers: {
        isOpen: (state: boolean, action: any, fullState: any) => boolean
        selectedInsight: (
            state: QueryBasedInsightModel | null,
            action: any,
            fullState: any
        ) => QueryBasedInsightModel | null
        showMoreInsightTypes: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        isOpen: boolean
        selectedInsight: QueryBasedInsightModel | null
        showMoreInsightTypes: boolean
    }
    selectors: {
        isOpen: (state: any, props?: any) => boolean
        selectedInsight: (state: any, props?: any) => QueryBasedInsightModel | null
        showMoreInsightTypes: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        isOpen: boolean
        selectedInsight: QueryBasedInsightModel | null
        showMoreInsightTypes: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}
