// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:38 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DataTableNode } from '../../queries/schema/schema-general'
import type { Breadcrumb } from '../../types'

export interface personsSceneLogicType extends Logic {
    actionCreators: {
        setQuery: (query: DataTableNode) => {
            type: 'set query (scenes.persons.personsSceneLogic)'
            payload: {
                query: DataTableNode
            }
        }
        resetDeletedDistinctId: (distinct_id: string) => {
            type: 'reset deleted distinct id (scenes.persons.personsSceneLogic)'
            payload: {
                distinct_id: string
            }
        }
        setShowDisplayNameNudge: (showDisplayNameNudge: boolean) => {
            type: 'set show display name nudge (scenes.persons.personsSceneLogic)'
            payload: {
                showDisplayNameNudge: boolean
            }
        }
        setIsBannerLoading: (isBannerLoading: boolean) => {
            type: 'set is banner loading (scenes.persons.personsSceneLogic)'
            payload: {
                isBannerLoading: boolean
            }
        }
    }
    actionKeys: {
        'set query (scenes.persons.personsSceneLogic)': 'setQuery'
        'reset deleted distinct id (scenes.persons.personsSceneLogic)': 'resetDeletedDistinctId'
        'set show display name nudge (scenes.persons.personsSceneLogic)': 'setShowDisplayNameNudge'
        'set is banner loading (scenes.persons.personsSceneLogic)': 'setIsBannerLoading'
    }
    actionTypes: {
        setQuery: 'set query (scenes.persons.personsSceneLogic)'
        resetDeletedDistinctId: 'reset deleted distinct id (scenes.persons.personsSceneLogic)'
        setShowDisplayNameNudge: 'set show display name nudge (scenes.persons.personsSceneLogic)'
        setIsBannerLoading: 'set is banner loading (scenes.persons.personsSceneLogic)'
    }
    actions: {
        setQuery: (query: DataTableNode) => void
        resetDeletedDistinctId: (distinct_id: string) => void
        setShowDisplayNameNudge: (showDisplayNameNudge: boolean) => void
        setIsBannerLoading: (isBannerLoading: boolean) => void
    }
    asyncActions: {
        setQuery: (query: DataTableNode) => Promise<any>
        resetDeletedDistinctId: (distinct_id: string) => Promise<any>
        setShowDisplayNameNudge: (showDisplayNameNudge: boolean) => Promise<any>
        setIsBannerLoading: (isBannerLoading: boolean) => Promise<any>
    }
    defaults: {
        query: DataTableNode
        showDisplayNameNudge: boolean
        isBannerLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {
        resetDeletedDistinctId: ((
            action: {
                type: 'reset deleted distinct id (scenes.persons.personsSceneLogic)'
                payload: {
                    distinct_id: string
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'persons', 'personsSceneLogic']
    pathString: 'scenes.persons.personsSceneLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        query: DataTableNode
        showDisplayNameNudge: boolean
        isBannerLoading: boolean
    }
    reducers: {
        query: (state: DataTableNode, action: any, fullState: any) => DataTableNode
        showDisplayNameNudge: (state: boolean, action: any, fullState: any) => boolean
        isBannerLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        query: DataTableNode
        showDisplayNameNudge: boolean
        isBannerLoading: boolean
    }
    selectors: {
        query: (state: any, props?: any) => DataTableNode
        showDisplayNameNudge: (state: any, props?: any) => boolean
        isBannerLoading: (state: any, props?: any) => boolean
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
    }
    sharedListeners: {}
    values: {
        query: DataTableNode
        showDisplayNameNudge: boolean
        isBannerLoading: boolean
        breadcrumbs: Breadcrumb[]
    }
    _isKea: true
    _isKeaWithKey: false
}
