# Generated by Django 5.2.14 on 2026-07-31 20:53

from django.db import migrations, models

from insights.migration_helpers import SafeAddIndexConcurrently


class Migration(migrations.Migration):
    # growth_organizationenrichmentfetch has production rows; CREATE INDEX CONCURRENTLY cannot
    # run inside a transaction, and Insights policy keeps concurrent index builds in their own
    # migration away from regular DDL.
    atomic = False

    dependencies = [
        ("growth", "0006_seed_ai_pilled_prompt_config"),
        ("insights", "0001_initial"),
    ]

    operations = [
        SafeAddIndexConcurrently(
            model_name="organizationenrichmentfetch",
            index=models.Index(
                fields=["organization", "-fetched_at", "-id"],
                name="growth_enrich_fetch_org_ts_id",
            ),
        ),
    ]
