# Generated by Django 4.2.29 on 2026-07-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.team'),
        ),
        migrations.AddField(
            model_name='conversationrestoretoken',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_restore_tokens', to='insights.team'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role_id_legacy__isnull', True), ('user__isnull', False)), models.Q(('role_id_legacy__isnull', False), ('user__isnull', True)), _connector='OR'), name='exactly_one_assignee_type'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'widget_session_id'], name='insights_co_team_id_6dd50d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'distinct_id'], name='insights_co_team_id_06c858_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'status'], name='insights_co_team_id_dc1d71_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', '-ticket_number'], name='con_team_id_ticket_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'session_id'], name='insights_co_team_id_552dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', '-updated_at'], name='insights_con_team_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'status', '-updated_at'], name='insights_con_status_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('team', 'ticket_number'), name='unique_ticket_number_per_team'),
        ),
        migrations.AddIndex(
            model_name='conversationrestoretoken',
            index=models.Index(fields=['team', 'recipient_email'], name='insights_crt_team_email_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationrestoretoken',
            index=models.Index(fields=['expires_at'], name='insights_crt_expires_idx'),
        ),
    ]
