// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:54 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface destinationsSceneLogicType extends Logic {
    actionCreators: {
        setActiveTab: (tab: 'all' | 'history') => {
            type: 'set active tab (scenes.data-pipelines.destinationsSceneLogic)'
            payload: {
                tab: 'all' | 'history'
            }
        }
    }
    actionKeys: {
        'set active tab (scenes.data-pipelines.destinationsSceneLogic)': 'setActiveTab'
    }
    actionTypes: {
        setActiveTab: 'set active tab (scenes.data-pipelines.destinationsSceneLogic)'
    }
    actions: {
        setActiveTab: (tab: 'all' | 'history') => void
    }
    asyncActions: {
        setActiveTab: (tab: 'all' | 'history') => Promise<any>
    }
    defaults: {
        activeTab: 'all' | 'history'
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'data-pipelines', 'destinationsSceneLogic']
    pathString: 'scenes.data-pipelines.destinationsSceneLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        activeTab: 'all' | 'history'
    }
    reducers: {
        activeTab: (state: 'all' | 'history', action: any, fullState: any) => 'all' | 'history'
    }
    selector: (state: any) => {
        activeTab: 'all' | 'history'
    }
    selectors: {
        activeTab: (state: any, props?: any) => 'all' | 'history'
    }
    sharedListeners: {}
    values: {
        activeTab: 'all' | 'history'
    }
    _isKea: true
    _isKeaWithKey: false
}
