[package]
name = "insights-symbol-data"
version = "0.5.0"
authors = [
    "David <david@hanzo.ai>",
    "Olly <oliver@hanzo.ai>",
    "Hugues <hugues@hanzo.ai>",
]
description = "A shared library for serialising/deserialising Insights symbol data"
edition = "2021"
license = "MIT"
homepage = "https://hanzo.ai"


[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
zstd = "0.13"
