[package]
name = "insights-symbol-data"
version = "0.3.0"
authors = [
    "David <david@insights.com>",
    "Olly <oliver@insights.com>",
    "Hugues <hugues@insights.com>",
]
description = "A shared library for serialising/deserialising Hanzo Insights symbol data"
edition = "2021"
license = "MIT"
homepage = "https://insights.com"


[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
