// Generated by kea-typegen on Sun, 02 Aug 2026 21:34:31 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { CodeEditorLogicProps, ModelMarker } from './codeEditorLogic'
import type { FeatureFlagsSet } from '../logic/featureFlagLogic'
import type { InsightsQLMetadataResponse } from '../../queries/schema/schema-general'

export interface codeEditorLogicType extends Logic {
    actionCreators: {
        reloadMetadata: () => {
            type: 'reload metadata (lib.monaco.insightsQLMetadataProvider)'
            payload: {
                value: true
            }
        }
        reloadMetadataSuccess: (
            metadata: [string, InsightsQLMetadataResponse] | null,
            payload?: {
                value: true
            }
        ) => {
            type: 'reload metadata success (lib.monaco.insightsQLMetadataProvider)'
            payload: {
                metadata: [string, InsightsQLMetadataResponse] | null
                payload?: {
                    value: true
                }
            }
        }
        reloadMetadataFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'reload metadata failure (lib.monaco.insightsQLMetadataProvider)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        reloadMetadataSuccessSuccess: (
            modelMarkers: ModelMarker[],
            payload?: {
                metadata: [string, InsightsQLMetadataResponse] | null
                payload?: {
                    value: true
                }
            }
        ) => {
            type: 'reload metadata success success (lib.monaco.insightsQLMetadataProvider)'
            payload: {
                modelMarkers: ModelMarker[]
                payload?: {
                    metadata: [string, InsightsQLMetadataResponse] | null
                    payload?: {
                        value: true
                    }
                }
            }
        }
        reloadMetadataSuccessFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'reload metadata success failure (lib.monaco.insightsQLMetadataProvider)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'reload metadata (lib.monaco.insightsQLMetadataProvider)': 'reloadMetadata'
        'reload metadata success (lib.monaco.insightsQLMetadataProvider)': 'reloadMetadataSuccess'
        'reload metadata failure (lib.monaco.insightsQLMetadataProvider)': 'reloadMetadataFailure'
        'reload metadata success success (lib.monaco.insightsQLMetadataProvider)': 'reloadMetadataSuccessSuccess'
        'reload metadata success failure (lib.monaco.insightsQLMetadataProvider)': 'reloadMetadataSuccessFailure'
    }
    actionTypes: {
        reloadMetadata: 'reload metadata (lib.monaco.insightsQLMetadataProvider)'
        reloadMetadataSuccess: 'reload metadata success (lib.monaco.insightsQLMetadataProvider)'
        reloadMetadataFailure: 'reload metadata failure (lib.monaco.insightsQLMetadataProvider)'
        reloadMetadataSuccessSuccess: 'reload metadata success success (lib.monaco.insightsQLMetadataProvider)'
        reloadMetadataSuccessFailure: 'reload metadata success failure (lib.monaco.insightsQLMetadataProvider)'
    }
    actions: {
        reloadMetadata: () => void
        reloadMetadataSuccess: (
            metadata: [string, InsightsQLMetadataResponse] | null,
            payload?: {
                value: true
            }
        ) => void
        reloadMetadataFailure: (error: string, errorObject?: any) => void
        reloadMetadataSuccessSuccess: (
            modelMarkers: ModelMarker[],
            payload?: {
                metadata: [string, InsightsQLMetadataResponse] | null
                payload?: {
                    value: true
                }
            }
        ) => void
        reloadMetadataSuccessFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        reloadMetadata: () => Promise<any>
        reloadMetadataSuccess: (
            metadata: [string, InsightsQLMetadataResponse] | null,
            payload?: {
                value: true
            }
        ) => Promise<any>
        reloadMetadataFailure: (error: string, errorObject?: any) => Promise<any>
        reloadMetadataSuccessSuccess: (
            modelMarkers: ModelMarker[],
            payload?: {
                metadata: [string, InsightsQLMetadataResponse] | null
                payload?: {
                    value: true
                }
            }
        ) => Promise<any>
        reloadMetadataSuccessFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        metadata: [string, InsightsQLMetadataResponse] | null
        metadataLoading: boolean
        modelMarkers: ModelMarker[]
        modelMarkersLoading: boolean
    }
    events: {}
    key: string
    listeners: {}
    path: ['lib', 'monaco', 'insightsQLMetadataProvider']
    pathString: 'lib.monaco.insightsQLMetadataProvider'
    props: CodeEditorLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        metadata: [string, InsightsQLMetadataResponse] | null
        metadataLoading: boolean
        modelMarkers: ModelMarker[]
        modelMarkersLoading: boolean
    }
    reducers: {
        metadata: (
            state: [string, InsightsQLMetadataResponse] | null,
            action: any,
            fullState: any
        ) => [string, InsightsQLMetadataResponse] | null
        metadataLoading: (state: boolean, action: any, fullState: any) => boolean
        modelMarkers: (state: ModelMarker[], action: any, fullState: any) => ModelMarker[]
        modelMarkersLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        metadata: [string, InsightsQLMetadataResponse] | null
        metadataLoading: boolean
        modelMarkers: ModelMarker[]
        modelMarkersLoading: boolean
    }
    selectors: {
        metadata: (state: any, props?: any) => [string, InsightsQLMetadataResponse] | null
        metadataLoading: (state: any, props?: any) => boolean
        modelMarkers: (state: any, props?: any) => ModelMarker[]
        modelMarkersLoading: (state: any, props?: any) => boolean
        featureFlags: (state: any, props?: any) => FeatureFlagsSet
        hasErrors: (state: any, props?: any) => boolean
        error: (state: any, props?: any) => string | null
    }
    sharedListeners: {}
    values: {
        metadata: [string, InsightsQLMetadataResponse] | null
        metadataLoading: boolean
        modelMarkers: ModelMarker[]
        modelMarkersLoading: boolean
        featureFlags: FeatureFlagsSet
        hasErrors: boolean
        error: string | null
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        hasErrors: (modelMarkers: ModelMarker[]) => boolean
        error: (hasErrors: boolean, modelMarkers: ModelMarker[]) => string | null
    }
}
