// Generated by kea-typegen on Sun, 02 Aug 2026 21:33:55 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface heatmapRecordingLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'heatmaps', 'scenes', 'heatmap', 'heatmapRecordingLogic']
    pathString: 'scenes.heatmaps.scenes.heatmap.heatmapRecordingLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {}
    sharedListeners: {}
    values: {}
    _isKea: true
    _isKeaWithKey: false
}
