// Generated by kea-typegen on Sun, 02 Aug 2026 21:32:58 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { UserProductListItem } from '../../../queries/schema/schema-general'

export interface customProductsLogicType extends Logic {
    actionCreators: {
        loadCustomProducts: () => {
            type: 'load custom products (layout.panel-layout.ProjectTree.customProductsLogic)'
            payload: any
        }
        loadCustomProductsSuccess: (
            customProducts: UserProductListItem[],
            payload?: any
        ) => {
            type: 'load custom products success (layout.panel-layout.ProjectTree.customProductsLogic)'
            payload: {
                customProducts: UserProductListItem[]
                payload?: any
            }
        }
        loadCustomProductsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load custom products failure (layout.panel-layout.ProjectTree.customProductsLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        seed: () => {
            type: 'seed (layout.panel-layout.ProjectTree.customProductsLogic)'
            payload: any
        }
        seedSuccess: (
            customProducts: UserProductListItem[],
            payload?: any
        ) => {
            type: 'seed success (layout.panel-layout.ProjectTree.customProductsLogic)'
            payload: {
                customProducts: UserProductListItem[]
                payload?: any
            }
        }
        seedFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'seed failure (layout.panel-layout.ProjectTree.customProductsLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'load custom products (layout.panel-layout.ProjectTree.customProductsLogic)': 'loadCustomProducts'
        'load custom products success (layout.panel-layout.ProjectTree.customProductsLogic)': 'loadCustomProductsSuccess'
        'load custom products failure (layout.panel-layout.ProjectTree.customProductsLogic)': 'loadCustomProductsFailure'
        'seed (layout.panel-layout.ProjectTree.customProductsLogic)': 'seed'
        'seed success (layout.panel-layout.ProjectTree.customProductsLogic)': 'seedSuccess'
        'seed failure (layout.panel-layout.ProjectTree.customProductsLogic)': 'seedFailure'
    }
    actionTypes: {
        loadCustomProducts: 'load custom products (layout.panel-layout.ProjectTree.customProductsLogic)'
        loadCustomProductsSuccess: 'load custom products success (layout.panel-layout.ProjectTree.customProductsLogic)'
        loadCustomProductsFailure: 'load custom products failure (layout.panel-layout.ProjectTree.customProductsLogic)'
        seed: 'seed (layout.panel-layout.ProjectTree.customProductsLogic)'
        seedSuccess: 'seed success (layout.panel-layout.ProjectTree.customProductsLogic)'
        seedFailure: 'seed failure (layout.panel-layout.ProjectTree.customProductsLogic)'
    }
    actions: {
        loadCustomProducts: () => void
        loadCustomProductsSuccess: (customProducts: UserProductListItem[], payload?: any) => void
        loadCustomProductsFailure: (error: string, errorObject?: any) => void
        seed: () => void
        seedSuccess: (customProducts: UserProductListItem[], payload?: any) => void
        seedFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadCustomProducts: () => Promise<any>
        loadCustomProductsSuccess: (customProducts: UserProductListItem[], payload?: any) => Promise<any>
        loadCustomProductsFailure: (error: string, errorObject?: any) => Promise<any>
        seed: () => Promise<any>
        seedSuccess: (customProducts: UserProductListItem[], payload?: any) => Promise<any>
        seedFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        customProducts: UserProductListItem[]
        customProductsLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['layout', 'panel-layout', 'ProjectTree', 'customProductsLogic']
    pathString: 'layout.panel-layout.ProjectTree.customProductsLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        customProducts: UserProductListItem[]
        customProductsLoading: boolean
    }
    reducers: {
        customProducts: (state: UserProductListItem[], action: any, fullState: any) => UserProductListItem[]
        customProductsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        customProducts: UserProductListItem[]
        customProductsLoading: boolean
    }
    selectors: {
        customProducts: (state: any, props?: any) => UserProductListItem[]
        customProductsLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        customProducts: UserProductListItem[]
        customProductsLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}
