# Generated by Django 4.2.29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import insights.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0004_heatmaps_on_by_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insights_ai", "0003_message_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=insights.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("prompt", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_questions",
                        to="insights.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=insights.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("failed", "Failed")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="insights_ai.question"
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["question", "-started_at"], name="insights_ai_questio_7631f8_idx"),
                    models.Index(fields=["status", "started_at"], name="insights_ai_status_c3231a_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["team", "-created_at"], name="insights_ai_team_id_fc1bcb_idx"),
        ),
    ]
