// Generated by kea-typegen on Sun, 02 Aug 2026 21:37:53 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { NotebookSceneLogicProps } from './notebookSceneLogic'
import type { NotebookTarget, NotebookType } from './types'
import type { JSONContent } from '../../lib/components/RichContentEditor/types'
import type { BuiltLogic } from '../../../../node_modules/.pnpm/kea@4.0.0-pre.3_react@18.3.1/node_modules/kea/lib/index'
import type { notebookLogicType } from './Notebook/notebookLogicType'
import type { Breadcrumb, ProjectTreeRef } from '../../types'
import type { SidePanelSceneContext } from '../../layout/navigation-3000/sidepanel/types'

export interface notebookSceneLogicType extends Logic {
    actionCreators: {
        loadNotebook: () => {
            type: 'load notebook (scenes.notebooks.notebookSceneLogic.*)'
            payload: {
                value: true
            }
        }
        createNotebook: (
            location: NotebookTarget,
            title?: string,
            content?: JSONContent[],
            onCreate?: (notebook: BuiltLogic<notebookLogicType>) => void
        ) => {
            type: 'create notebook (scenes.notebooks.notebookSceneLogic.*)'
            payload: {
                content: JSONContent[] | undefined
                location: NotebookTarget
                onCreate: ((notebook: BuiltLogic<notebookLogicType>) => void) | undefined
                title: string | undefined
            }
        }
    }
    actionKeys: {
        'load notebook (scenes.notebooks.notebookSceneLogic.*)': 'loadNotebook'
        'create notebook (scenes.notebooks.notebookSceneLogic.*)': 'createNotebook'
    }
    actionTypes: {
        loadNotebook: 'load notebook (scenes.notebooks.notebookSceneLogic.*)'
        createNotebook: 'create notebook (scenes.notebooks.notebookSceneLogic.*)'
    }
    actions: {
        loadNotebook: () => void
        createNotebook: (
            location: NotebookTarget,
            title?: string,
            content?: JSONContent[],
            onCreate?: (notebook: BuiltLogic<notebookLogicType>) => void
        ) => void
    }
    asyncActions: {
        loadNotebook: () => Promise<any>
        createNotebook: (
            location: NotebookTarget,
            title?: string,
            content?: JSONContent[],
            onCreate?: (notebook: BuiltLogic<notebookLogicType>) => void
        ) => Promise<any>
    }
    defaults: {}
    events: {}
    key: string
    listeners: {}
    path: ['scenes', 'notebooks', 'notebookSceneLogic', '*']
    pathString: 'scenes.notebooks.notebookSceneLogic.*'
    props: NotebookSceneLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        notebook: (state: any, props?: any) => NotebookType | null
        notebookLoading: (state: any, props?: any) => boolean
        isLocalOnly: (state: any, props?: any) => boolean
        notebooksLoading: (state: any, props?: any) => boolean
        notebookId: (state: any, props?: any) => string
        loading: (state: any, props?: any) => boolean
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
        projectTreeRef: (state: any, props?: any) => ProjectTreeRef | null
        sidePanelContext: (state: any, props?: any) => SidePanelSceneContext | null
    }
    sharedListeners: {}
    values: {
        notebook: NotebookType | null
        notebookLoading: boolean
        isLocalOnly: boolean
        notebooksLoading: boolean
        notebookId: string
        loading: boolean
        breadcrumbs: Breadcrumb[]
        projectTreeRef: ProjectTreeRef | null
        sidePanelContext: SidePanelSceneContext | null
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        notebookId: (shortId: string) => string
        loading: (notebookLoading: boolean, notebooksLoading: boolean) => boolean
        breadcrumbs: (
            notebook: null | import('/home/z/work/hanzo/insights/frontend/src/scenes/notebooks/types').NotebookType,
            loading: boolean
        ) => Breadcrumb[]
        projectTreeRef: (arg: string) => ProjectTreeRef | null
        sidePanelContext: (notebookId: string, isLocalOnly: boolean) => SidePanelSceneContext | null
    }
}
