{{- if not .Values.insights.existingSecret }}
{{- if not .Values.insights.apiKey }}
{{- fail "insights.apiKey is required (or set insights.existingSecret)" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "insights-metrics-agent.fullname" . }}
    labels:
        {{- include "insights-metrics-agent.labels" . | nindent 8 }}
type: Opaque
data:
    insights-api-key: {{ .Values.insights.apiKey | b64enc }}
{{- end }}
