{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "insights-metrics-agent.serviceAccountName" . }}
    labels:
        {{- include "insights-metrics-agent.labels" . | nindent 8 }}
{{- end }}
